In [1]:
import pandas as pd
from Bio import PDB
import csv
import os
from Bio.PDB.MMCIFParser import MMCIFParser
import numpy as np

<h2>Przygotowanie klasy pierwszej - obecnośc motywu</h2>

In [2]:
data = pd.read_csv('./HL_43074.18.csv', sep=',')

dimension = data.shape
motifs_ids = []
motifs_nucs = []
discared = []

for i in range(dimension[0]):                #rows
    nucs, nucs_str = [], ''
    for j in range(dimension[1]):            #columns
        cell = data.iloc[i,j].split('|')
        if cell[-1] in ['A', 'B', 'C', 'D', 'E', 'F']:
            discared.append(cell[0])
            break
        nucs.append(int(cell[-1]))
        nucs_str += cell[-2]
    if cell[0] not in discared:
        motifs_ids.append([cell[0], cell[-3], nucs])
        motifs_nucs.append([cell[0], cell[-3], nucs_str])

motifs_ids.sort(key=lambda x: x[0])
motifs_nucs.sort(key=lambda x: x[0])
print(motifs_ids)
print(motifs_nucs)
print(discared)

[['1G1X', 'D', [590, 591, 592, 593, 594, 649]], ['1G1X', 'J', [726, 727, 728, 729, 730, 731]], ['1G1X', 'E', [726, 727, 728, 729, 730, 731]], ['1G1X', 'I', [590, 591, 592, 593, 594, 649]], ['1JID', 'B', [146, 147, 148, 149, 150, 151]], ['1KH6', 'A', [28, 29, 30, 31, 32, 33]], ['1KXK', 'A', [33, 34, 35, 36, 37, 38]], ['1L9A', 'B', [197, 198, 199, 200, 201, 202]], ['1L9A', 'B', [146, 147, 148, 149, 150, 151]], ['1M5K', 'B', [74, 75, 76, 77, 78, 79]], ['1MFQ', 'A', [197, 198, 199, 200, 201, 202]], ['1MFQ', 'A', [146, 147, 148, 149, 150, 151]], ['1MZP', 'B', [25, 26, 27, 28, 29, 30]], ['1NBS', 'B', [204, 205, 206, 207, 208, 209]], ['1Q96', 'A', [13, 14, 15, 16, 17, 18]], ['1RLG', 'D', [9, 10, 11, 12, 13, 14]], ['1U6B', 'B', [23, 24, 25, 26, 27, 28]], ['1U6B', 'B', [153, 154, 155, 156, 157, 158]], ['1U9S', 'A', [204, 205, 206, 207, 208, 209]], ['1U9S', 'A', [99, 100, 101, 102, 103, 104]], ['1UN6', 'F', [82, 83, 84, 85, 86, 94]], ['2OIU', 'P', [10, 11, 12, 13, 14, 15]], ['2OIU', 'P', [59, 60, 61, 62, 63, 64]], ['2R8S', 'R', [149, 150, 151, 152, 153, 154]], ['2Z75', 'B', [113, 114, 115, 116, 117, 118]], ['3AM1', 'B', [45, 46, 47, 48, 49, 50]], ['3AM1', 'B', [32, 33, 34, 35, 36, 37]], ['3CUL', 'C', [7, 8, 9, 10, 11, 12]], ['3D0U', 'A', [142, 143, 144, 145, 146, 147]], ['3E5C', 'A', [18, 19, 20, 21, 22, 23]], ['3E5C', 'A', [41, 42, 43, 44, 45, 46]], ['3G9C', 'Q', [108, 109, 110, 111, 112, 113]], ['3IGI', 'A', [274, 275, 276, 277, 278, 279]], ['3IGI', 'A', [89, 90, 91, 92, 93, 94]], ['3IWN', 'A', [21, 22, 23, 24, 25, 26]], ['3KTW', 'C', [209, 210, 211, 212, 213, 214]], ['3LQX', 'B', [153, 154, 155, 156, 157, 158]], ['3MOJ', 'A', [2529, 2530, 2531, 2532, 2533, 2534]], ['3MXH', 'R', [31, 32, 33, 34, 35, 36]], ['3NDB', 'M', [208, 209, 210, 211, 212, 213]], ['3NKB', 'B', [49, 50, 51, 52, 53, 54]], ['3NMU', 'E', [18, 19, 20, 21, 22, 23]], ['3NPQ', 'A', [20, 21, 22, 23, 24, 25]], ['3NVI', 'F', [9, 10, 11, 12, 13, 14]], ['3P22', 'A', [17, 18, 19, 20, 21, 22]], ['3PDR', 'X', [68, 69, 70, 71, 72, 73]], ['3RW6', 'H', [27, 28, 29, 30, 31, 32]], ['3SUX', 'X', [65, 66, 67, 68, 69, 70]], ['3V7E', 'C', [105, 106, 107, 108, 109, 110]], ['4AOB', 'A', [73, 74, 75, 76, 77, 78]], ['4AOB', 'A', [49, 50, 51, 52, 53, 54]], ['4BW0', 'A', [9, 10, 11, 12, 13, 14]], ['4C7O', 'E', [19, 20, 21, 22, 23, 24]], ['4ENC', 'A', [28, 29, 30, 31, 32, 33]], ['4FRG', 'B', [46, 47, 48, 49, 50, 51]], ['4JF2', 'A', [8, 9, 10, 11, 12, 13]], ['4K27', 'U', [26, 27, 28, 29, 30, 31]], ['4K50', 'B', [587, 588, 589, 590, 591, 592]], ['4KQY', 'A', [60, 61, 62, 63, 64, 65]], ['4LFB', 'A', [1165, 1166, 1167, 1168, 1169, 1171]], ['4LFB', 'A', [379, 380, 381, 382, 383, 384]], ['4LFB', 'A', [897, 898, 899, 900, 901, 902]], ['4LFB', 'A', [862, 863, 864, 865, 866, 867]], ['4LFB', 'A', [158, 159, 160, 161, 162, 163]], ['4LFB', 'A', [1265, 1266, 1267, 1268, 1269, 1270]], ['4LFB', 'A', [296, 297, 298, 299, 300, 301]], ['4LFB', 'A', [1012, 1013, 1014, 1015, 1016, 1017]], ['4LFB', 'A', [1076, 1077, 1078, 1079, 1080, 1081]], ['4LFB', 'A', [726, 727, 728, 729, 730, 731]], ['4LVW', 'A', [58, 59, 60, 61, 62, 63]], ['4NLF', 'A', [2658, 2659, 2660, 2661, 2662, 2663]], ['4OQU', 'A', [13, 14, 15, 16, 17, 18]], ['4OQU', 'A', [57, 58, 59, 60, 61, 62]], ['4OQU', 'A', [76, 77, 78, 79, 80, 81]], ['4PCJ', 'A', [16, 17, 18, 19, 20, 21]], ['4PLX', 'A', [24, 25, 26, 27, 28, 29]], ['4PQV', 'A', [13, 14, 15, 16, 17, 18]], ['4QK9', 'A', [56, 57, 58, 59, 60, 61]], ['4QK9', 'A', [14, 15, 16, 17, 18, 19]], ['4QLM', 'A', [54, 55, 56, 57, 58, 59]], ['4R4V', 'A', [735, 736, 737, 738, 739, 740]], ['4RUM', 'A', [51, 52, 53, 54, 55, 56]], ['4V88', 'A6', [1121, 1122, 1123, 1124, 1125, 1126]], ['4V88', 'A6', [1084, 1085, 1086, 1087, 1088, 1089]], ['4V88', 'A6', [1296, 1297, 1298, 1299, 1300, 1301]], ['4V88', 'A6', [937, 938, 939, 940, 941, 942]], ['4V88', 'A6', [154, 155, 156, 157, 158, 160]], ['4V88', 'A6', [1778, 1779, 1780, 1781, 1782, 1783]], ['4V88', 'A6', [1501, 1502, 1503, 1504, 1505, 1506]], ['4V88', 'A6', [569, 570, 571, 572, 573, 574]], ['4V9F', '0', [804, 805, 806, 807, 808, 809]], ['4V9F', '0', [2248, 2249, 2250, 2251, 2252, 2253]], ['4V9F', '9', [89, 90, 91, 92, 93, 94]], ['4V9F', '0', [2695, 2696, 2697, 2698, 2699, 2700]], ['4V9F', '0', [1862, 1863, 1864, 1865, 1866, 1867]], ['4V9F', '0', [252, 253, 254, 255, 256, 257]], ['4V9F', '0', [1628, 1629, 1630, 1631, 1632, 1633]], ['4V9F', '0', [1793, 1794, 1795, 1796, 1797, 1799]], ['4V9F', '0', [1054, 1055, 1056, 1057, 1058, 1060]], ['4V9F', '0', [690, 691, 692, 693, 694, 695]], ['4V9F', '0', [2411, 2412, 2413, 2414, 2415, 2416]], ['4V9F', '0', [2876, 2877, 2878, 2879, 2880, 2881]], ['4V9F', '0', [2629, 2630, 2631, 2632, 2633, 2634]], ['4V9F', '0', [468, 469, 470, 471, 472, 473]], ['4V9F', '0', [576, 577, 578, 579, 580, 581]], ['4V9F', '0', [1326, 1327, 1328, 1329, 1330, 1331]], ['4V9F', '0', [1468, 1469, 1470, 1471, 1472, 1474]], ['4V9F', '0', [733, 734, 735, 736, 737, 738]], ['4W90', 'C', [82, 83, 84, 85, 86, 87]], ['4WF9', 'X', [2685, 2686, 2687, 2688, 2689, 2690]], ['4WF9', 'X', [533, 534, 535, 536, 537, 538]], ['4WF9', 'X', [2401, 2402, 2403, 2404, 2405, 2406]], ['4WF9', 'X', [674, 675, 676, 677, 678, 679]], ['4WF9', 'X', [999, 1000, 1001, 1003, 1004, 1006]], ['4WF9', 'X', [2876, 2877, 2878, 2879, 2880, 2881]], ['4WF9', 'X', [508, 509, 510, 511, 512, 513]], ['4WF9', 'X', [2621, 2622, 2623, 2624, 2625, 2626]], ['4WF9', 'X', [1400, 1401, 1402, 1403, 1404, 1405]], ['4WFL', 'A', [81, 82, 83, 84, 85, 86]], ['4Y1M', 'B', [55, 56, 57, 58, 59, 60]], ['4Y1M', 'B', [24, 25, 26, 27, 28, 29]], ['4Y1M', 'B', [81, 82, 83, 84, 85, 86]], ['4YAZ', 'R', [25, 26, 27, 28, 29, 30]], ['4ZT0', 'D', [32, 33, 34, 35, 36, 37]], ['4ZT0', 'D', [72, 73, 74, 75, 76, 77]], ['5B2P', 'B', [35, 36, 37, 38, 39, 40]], ['5B2T', 'A', [72, 73, 74, 75, 76, 77]], ['5B2T', 'A', [32, 33, 34, 35, 36, 37]], ['5BTM', 'A', [26, 27, 28, 29, 30, 31]], ['5D5L', 'A', [8, 9, 10, 11, 12, 13]], ['5DCV', 'D', [26, 27, 28, 29, 30, 31]], ['5DDO', 'A', [11, 12, 13, 14, 15, 16]], ['5DDO', 'B', [11, 12, 13, 14, 15, 16]], ['5DDP', 'A', [11, 12, 13, 14, 15, 16]], ['5F9F', 'F', [10, 11, 12, 13, 14, 15]], ['5F9R', 'A', [90, 91, 92, 93, 94, 95]], ['5FJC', 'A', [49, 50, 51, 52, 53, 54]], ['5FJC', 'A', [73, 74, 75, 76, 77, 78]], ['5FQ5', 'A', [32, 33, 34, 35, 36, 37]], ['5FQ5', 'A', [72, 73, 74, 75, 76, 77]], ['5J7L', 'AA', [379, 380, 381, 382, 383, 384]], ['5J7L', 'AA', [186, 187, 188, 189, 190, 191]], ['5J7L', 'DA', [2658, 2659, 2660, 2661, 2662, 2663]], ['5J7L', 'AA', [897, 898, 899, 900, 901, 902]], ['5J7L', 'DA', [629, 630, 631, 632, 633, 634]], ['5J7L', 'AA', [862, 863, 864, 865, 866, 867]], ['5J7L', 'AA', [158, 159, 160, 161, 162, 163]], ['5J7L', 'DA', [2374, 2375, 2376, 2377, 2378, 2379]], ['5J7L', 'DA', [2856, 2857, 2858, 2859, 2860, 2861]], ['5J7L', 'DA', [462, 463, 464, 465, 466, 467]], ['5J7L', 'AA', [296, 297, 298, 299, 300, 301]], ['5J7L', 'DA', [2594, 2595, 2596, 2597, 2598, 2599]], ['5J7L', 'DA', [2356, 2357, 2358, 2359, 2360, 2361]], ['5J7L', 'AA', [726, 727, 728, 729, 730, 731]], ['5J7L', 'AA', [1265, 1266, 1267, 1268, 1269, 1270]], ['5J7L', 'AA', [1076, 1077, 1078, 1079, 1080, 1081]], ['5J7L', 'DA', [1363, 1364, 1365, 1366, 1367, 1368]], ['5J7L', 'DA', [1222, 1223, 1224, 1225, 1226, 1227]], ['5J7L', 'DA', [1868, 1869, 1870, 1871, 1872, 1873]], ['5M0H', 'A', [21, 22, 23, 24, 25, 26]], ['5M0I', 'F', [12, 13, 14, 15, 16, 17]], ['5M0I', 'E', [12, 13, 14, 15, 16, 17]], ['5M0J', 'F', [12, 13, 14, 15, 16, 17]], ['5M0J', 'E', [12, 13, 14, 15, 16, 17]], ['5TBW', '1', [3025, 3026, 3027, 3028, 3029, 3030]], ['5TBW', '1', [732, 733, 734, 735, 736, 737]], ['5TBW', '1', [599, 600, 601, 602, 603, 604]], ['5TBW', 'AS', [88, 89, 90, 91, 92, 93]], ['5TBW', '1', [1023, 1024, 1025, 1026, 1027, 1029]], ['5TBW', '1', [2220, 2221, 2222, 2223, 2224, 2225]], ['5TBW', '1', [2164, 2165, 2166, 2167, 2168, 2170]], ['5TBW', '1', [844, 845, 846, 847, 848, 849]], ['5TBW', '1', [357, 358, 359, 360, 361, 362]], ['5TBW', '1', [2963, 2964, 2965, 2966, 2967, 2968]], ['5TBW', '1', [1126, 1127, 1128, 1129, 1130, 1132]], ['5TBW', '1', [2744, 2745, 2746, 2747, 2748, 2749]], ['5TBW', '1', [707, 708, 709, 710, 711, 712]], ['5TBW', '1', [1634, 1635, 1636, 1637, 1638, 1639]], ['5TBW', '1', [1403, 1404, 1405, 1406, 1407, 1408]], ['5TBW', '1', [1544, 1545, 1546, 1547, 1548, 1549]], ['5TBW', '1', [1760, 1761, 1762, 1763, 1764, 1765]], ['5TPY', 'A', [62, 63, 64, 65, 66, 67]], ['5TPY', 'A', [13, 14, 15, 16, 17, 18]], ['5U3G', 'B', [47, 48, 49, 50, 51, 52]], ['5UZ6', 'A', [15, 16, 17, 18, 19, 20]], ['5VCI', 'A', [16, 17, 18, 19, 20, 21]], ['5VW1', 'C', [32, 33, 34, 35, 36, 37]], ['5VW1', 'C', [72, 73, 74, 75, 76, 77]], ['5X2G', 'B', [32, 33, 34, 35, 36, 37]], ['5XTM', 'B', [24, 25, 26, 27, 28, 29]], ['5XTM', 'D', [24, 25, 26, 27, 28, 29]], ['5Y7M', 'D', [24, 25, 26, 27, 28, 29]], ['6AZ4', 'A', [20, 21, 22, 23, 24, 25]], ['6CB3', 'B', [50, 51, 52, 53, 54, 55]], ['6CB3', 'B', [76, 77, 78, 79, 80, 81]], ['6CB3', 'B', [20, 21, 22, 23, 24, 25]], ['6CU1', 'A', [42, 43, 44, 45, 46, 47]], ['6CZR', '1a', [875, 876, 877, 878, 879, 880]], ['6CZR', '1a', [375, 376, 377, 378, 379, 380]], ['6CZR', '1a', [292, 293, 294, 295, 296, 297]], ['6CZR', '1a', [840, 841, 842, 843, 844, 845]], ['6CZR', '1a', [1148, 1149, 1150, 1151, 1152, 1153]], ['6CZR', '1a', [153, 154, 155, 156, 157, 158]], ['6CZR', '1a', [1059, 1060, 1061, 1062, 1063, 1064]], ['6CZR', '1a', [710, 711, 712, 713, 714, 715]], ['6DME', 'A', [25, 26, 27, 28, 29, 30]], ['6DVK', 'H', [45, 46, 47, 48, 49, 50]], ['6JDV', 'B', [86, 87, 88, 89, 90, 91]], ['6JDV', 'B', [48, 49, 50, 51, 52, 53]], ['6JOO', 'B', [32, 33, 34, 35, 36, 37]], ['6JQ5', 'B', [45, 46, 47, 48, 49, 50]], ['6JQ5', 'A', [45, 46, 47, 48, 49, 50]], ['6MJ0', 'B', [49, 50, 51, 52, 53, 54]], ['6N2V', 'A', [56, 57, 58, 59, 60, 61]], ['6N2V', 'A', [76, 77, 78, 79, 80, 81]], ['6N2V', 'A', [24, 25, 26, 27, 28, 29]], ['6SVS', 'A', [26, 27, 28, 29, 30, 31]], ['6U8D', 'A', [180, 198, 199, 200, 201, 219]], ['6UFG', 'A', [105, 106, 107, 108, 109, 110]], ['6UFG', 'A', [144, 145, 146, 147, 148, 149]], ['6UFH', 'A', [145, 146, 147, 148, 149, 150]], ['6UFH', 'A', [45, 46, 47, 48, 49, 50]], ['6UFH', 'A', [106, 107, 108, 109, 110, 111]], ['6WPI', 'B', [25, 26, 27, 28, 29, 30]], ['7A0S', 'X', [2637, 2638, 2639, 2640, 2641, 2642]], ['7A0S', 'X', [2353, 2354, 2355, 2356, 2357, 2358]], ['7A0S', 'X', [498, 499, 500, 501, 502, 503]], ['7A0S', 'X', [2831, 2832, 2833, 2834, 2835, 2836]], ['7A0S', 'X', [640, 641, 642, 643, 644, 645]], ['7A0S', 'X', [966, 967, 968, 970, 971, 973]], ['7A0S', 'X', [1856, 1857, 1858, 1859, 1860, 1861]], ['7A0S', 'X', [2573, 2574, 2575, 2576, 2577, 2578]], ['7A0S', 'X', [473, 474, 475, 476, 477, 478]], ['7A0S', 'Y', [88, 89, 90, 91, 92, 93]], ['7A0S', 'X', [146, 147, 148, 149, 150, 151]], ['7A0S', 'X', [1376, 1377, 1378, 1379, 1380, 1381]], ['7RQB', '1A', [2374, 2375, 2376, 2377, 2378, 2379]], ['7RQB', '1A', [1806, 1807, 1808, 1809, 1810, 1811]], ['7RQB', '1A', [2658, 2659, 2660, 2661, 2662, 2663]], ['7RQB', '1A', [487, 488, 489, 491, 492, 493]], ['7RQB', '1A', [629, 630, 631, 632, 633, 634]], ['7RQB', '1A', [955, 956, 957, 959, 960, 962]], ['7RQB', '1B', [86, 87, 88, 89, 90, 91]], ['7RQB', '1A', [462, 463, 464, 465, 466, 467]], ['7RQB', '1A', [2594, 2595, 2596, 2597, 2598, 2599]], ['7RQB', '1A', [1864, 1865, 1866, 1876, 1877, 1878]], ['7RQB', '1A', [2856, 2857, 2858, 2859, 2860, 2861]], ['7RQB', '1A', [1222, 1223, 1224, 1225, 1226, 1227]], ['7RQB', '1A', [1363, 1364, 1365, 1366, 1367, 1368]]]
[['1G1X', 'D', 'CGAAAG'], ['1G1X', 'J', 'CGAAGG'], ['1G1X', 'E', 'CGAAGG'], ['1G1X', 'I', 'CGAAAG'], ['1JID', 'B', 'GGGAGC'], ['1KH6', 'A', 'CGAAAG'], ['1KXK', 'A', 'UGAAAG'], ['1L9A', 'B', 'GGAAAC'], ['1L9A', 'B', 'GGGAGC'], ['1M5K', 'B', 'GGAAAC'], ['1MFQ', 'A', 'GGAAAC'], ['1MFQ', 'A', 'GGGAGC'], ['1MZP', 'B', 'CGCAAG'], ['1NBS', 'B', 'AGAAAU'], ['1Q96', 'A', 'UGAGAA'], ['1RLG', 'D', 'CGAAAG'], ['1U6B', 'B', 'GGAAAC'], ['1U6B', 'B', 'CAAACG'], ['1U9S', 'A', 'GGCAAC'], ['1U9S', 'A', 'GGUAAC'], ['1UN6', 'F', 'GGAAAC'], ['2OIU', 'P', 'CGAAAG'], ['2OIU', 'P', 'CGAAAG'], ['2R8S', 'R', 'GGAAAC'], ['2Z75', 'B', 'GGCGAC'], ['3AM1', 'B', 'CGAGAG'], ['3AM1', 'B', 'CUUCGG'], ['3CUL', 'C', 'CGAAAG'], ['3D0U', 'A', 'CGAAAG'], ['3E5C', 'A', 'GGAAAC'], ['3E5C', 'A', 'CGAAAG'], ['3G9C', 'Q', 'GGUGAC'], ['3IGI', 'A', 'GGAAAC'], ['3IGI', 'A', 'GGCGAC'], ['3IWN', 'A', 'CGAAAG'], ['3KTW', 'C', 'CGGAAG'], ['3LQX', 'B', 'CGAAAG'], ['3MOJ', 'A', 'GGAAAC'], ['3MXH', 'R', 'CGAAAG'], ['3NDB', 'M', 'CGGAAG'], ['3NKB', 'B', 'CGAAAG'], ['3NMU', 'E', 'CGAAAG'], ['3NPQ', 'A', 'CGAGAG'], ['3NVI', 'F', 'CGAAAG'], ['3P22', 'A', 'CGAAAG'], ['3PDR', 'X', 'CCAAAG'], ['3RW6', 'H', 'GGAAAC'], ['3SUX', 'X', 'CGAAAG'], ['3V7E', 'C', 'GGAAAC'], ['4AOB', 'A', 'GGAAAC'], ['4AOB', 'A', 'AAAAAU'], ['4BW0', 'A', 'CGAAAG'], ['4C7O', 'E', 'CGGAAG'], ['4ENC', 'A', 'UGAAAA'], ['4FRG', 'B', 'CGAAAG'], ['4JF2', 'A', 'CGAAAG'], ['4K27', 'U', 'UGAAAG'], ['4K50', 'B', 'UGAAAG'], ['4KQY', 'A', 'CGAAAG'], ['4LFB', 'A', 'CGAAAG'], ['4LFB', 'A', 'CGCAAG'], ['4LFB', 'A', 'CGCAAG'], ['4LFB', 'A', 'CUAACG'], ['4LFB', 'A', 'GGAAAC'], ['4LFB', 'A', 'GGCAAC'], ['4LFB', 'A', 'UGAGAG'], ['4LFB', 'A', 'UGAAAG'], ['4LFB', 'A', 'CGUGAG'], ['4LFB', 'A', 'CGAAGG'], ['4LVW', 'A', 'CGAGAG'], ['4NLF', 'A', 'CGAGAG'], ['4OQU', 'A', 'GGAGAC'], ['4OQU', 'A', 'GGAGAC'], ['4OQU', 'A', 'CGAGAG'], ['4PCJ', 'A', 'UGAAAG'], ['4PLX', 'A', 'CGAAAG'], ['4PQV', 'A', 'CGAAAG'], ['4QK9', 'A', 'CGUAAG'], ['4QK9', 'A', 'CUGAAG'], ['4QLM', 'A', 'CGAAAG'], ['4R4V', 'A', 'CGUAAG'], ['4RUM', 'A', 'CGAAAG'], ['4V88', 'A6', 'CGCAAG'], ['4V88', 'A6', 'AGAAAU'], ['4V88', 'A6', 'AGUGAU'], ['4V88', 'A6', 'CGAAAG'], ['4V88', 'A6', 'GUAAUC'], ['4V88', 'A6', 'GUGAAC'], ['4V88', 'A6', 'CGAGAG'], ['4V88', 'A6', 'CAGCCG'], ['4V9F', '0', 'CGAAAG'], ['4V9F', '0', 'CGGGAG'], ['4V9F', '9', 'CGCGAG'], ['4V9F', '0', 'CGAGAG'], ['4V9F', '0', 'CGCAAG'], ['4V9F', '0', 'CUCACG'], ['4V9F', '0', 'GGAAAC'], ['4V9F', '0', 'CGGAAG'], ['4V9F', '0', 'GGUAAC'], ['4V9F', '0', 'GGAAAC'], ['4V9F', '0', 'CGAAAG'], ['4V9F', '0', 'GGUAAC'], ['4V9F', '0', 'CGUGAG'], ['4V9F', '0', 'UGUGAA'], ['4V9F', '0', 'CGCGAG'], ['4V9F', '0', 'CGAGAG'], ['4V9F', '0', 'GCAACC'], ['4V9F', '0', 'UUCAAG'], ['4W90', 'C', 'CGAAAG'], ['4WF9', 'X', 'CGAGAG'], ['4WF9', 'X', 'CGGAAG'], ['4WF9', 'X', 'CGAAAG'], ['4WF9', 'X', 'CGAAAG'], ['4WF9', 'X', 'UGAAAG'], ['4WF9', 'X', 'GGUGAC'], ['4WF9', 'X', 'CGUGAG'], ['4WF9', 'X', 'CGUGAG'], ['4WF9', 'X', 'CGACAG'], ['4WFL', 'A', 'GGUAAC'], ['4Y1M', 'B', 'UGAAAA'], ['4Y1M', 'B', 'CGAAAG'], ['4Y1M', 'B', 'AGAAAU'], ['4YAZ', 'R', 'CGCGAG'], ['4ZT0', 'D', 'AGAAAU'], ['4ZT0', 'D', 'UGAAAA'], ['5B2P', 'B', 'CGAAAG'], ['5B2T', 'A', 'UGAAAA'], ['5B2T', 'A', 'AGAAAU'], ['5BTM', 'A', 'UGAAAG'], ['5D5L', 'A', 'CGAAAG'], ['5DCV', 'D', 'GGAAAC'], ['5DDO', 'A', 'GGAAAC'], ['5DDO', 'B', 'GGAAAC'], ['5DDP', 'A', 'GGAAAC'], ['5F9F', 'F', 'AGUGAU'], ['5F9R', 'A', 'UGAAAA'], ['5FJC', 'A', 'AGAAAU'], ['5FJC', 'A', 'GGAAAC'], ['5FQ5', 'A', 'AGAAAU'], ['5FQ5', 'A', 'UGAAAA'], ['5J7L', 'AA', 'CGCAAG'], ['5J7L', 'AA', 'CGCAAG'], ['5J7L', 'DA', 'CGAGAG'], ['5J7L', 'AA', 'CGCAAG'], ['5J7L', 'DA', 'GGAAAC'], ['5J7L', 'AA', 'CUAACG'], ['5J7L', 'AA', 'GGAAAC'], ['5J7L', 'DA', 'CGAAAG'], ['5J7L', 'DA', 'AGCGAU'], ['5J7L', 'DA', 'CGUGAG'], ['5J7L', 'AA', 'UGAGAG'], ['5J7L', 'DA', 'CGUGAG'], ['5J7L', 'DA', 'UGACGG'], ['5J7L', 'AA', 'CGAAGG'], ['5J7L', 'AA', 'CGCGAG'], ['5J7L', 'AA', 'UGUGAA'], ['5J7L', 'DA', 'CGAAAG'], ['5J7L', 'DA', 'UGUGAG'], ['5J7L', 'DA', 'CGCAAG'], ['5M0H', 'A', 'UGAAAG'], ['5M0I', 'F', 'CGAAAG'], ['5M0I', 'E', 'CGAAAG'], ['5M0J', 'F', 'CGAAAG'], ['5M0J', 'E', 'CGAAAG'], ['5TBW', '1', 'CGAGAG'], ['5TBW', '1', 'CGCAAG'], ['5TBW', '1', 'CGUAAG'], ['5TBW', 'AS', 'GGUGAC'], ['5TBW', '1', 'CGAAAG'], ['5TBW', '1', 'AGAAAU'], ['5TBW', '1', 'AGAAAU'], ['5TBW', '1', 'GGAAAC'], ['5TBW', '1', 'AGUGAU'], ['5TBW', '1', 'CGUGAG'], ['5TBW', '1', 'GGUAAC'], ['5TBW', '1', 'UGAAAG'], ['5TBW', '1', 'UGAAAG'], ['5TBW', '1', 'GGUAAC'], ['5TBW', '1', 'CGUAAG'], ['5TBW', '1', 'GAAGCU'], ['5TBW', '1', 'ACCUUU'], ['5TPY', 'A', 'CGAAAG'], ['5TPY', 'A', 'CGAAAG'], ['5U3G', 'B', 'CGAAAG'], ['5UZ6', 'A', 'CGAAAG'], ['5VCI', 'A', 'CGAAAG'], ['5VW1', 'C', 'AGAAAU'], ['5VW1', 'C', 'UGAAAA'], ['5X2G', 'B', 'UGAAAA'], ['5XTM', 'B', 'GGAAAC'], ['5XTM', 'D', 'GGAAAC'], ['5Y7M', 'D', 'CGAAAG'], ['6AZ4', 'A', 'UGAAAG'], ['6CB3', 'B', 'GGAAAC'], ['6CB3', 'B', 'CGAAAG'], ['6CB3', 'B', 'GGAAAC'], ['6CU1', 'A', 'CGAAAG'], ['6CZR', '1a', 'CGCAAG'], ['6CZR', '1a', 'CGCAAG'], ['6CZR', '1a', 'UGAGAG'], ['6CZR', '1a', 'CUAACG'], ['6CZR', '1a', 'CGAAAG'], ['6CZR', '1a', 'GGAAAC'], ['6CZR', '1a', 'CGUGAG'], ['6CZR', '1a', 'CGAAGG'], ['6DME', 'A', 'CGAGAG'], ['6DVK', 'H', 'GGAAAC'], ['6JDV', 'B', 'UGAAAA'], ['6JDV', 'B', 'GGAAAC'], ['6JOO', 'B', 'GGAAAC'], ['6JQ5', 'B', 'CGAAAG'], ['6JQ5', 'A', 'CGAAAG'], ['6MJ0', 'B', 'CGAAAG'], ['6N2V', 'A', 'CGAAAG'], ['6N2V', 'A', 'CGAAAG'], ['6N2V', 'A', 'GGAAAC'], ['6SVS', 'A', 'CGAAAG'], ['6U8D', 'A', 'GGAAAC'], ['6UFG', 'A', 'CGAAAG'], ['6UFG', 'A', 'CGAAAG'], ['6UFH', 'A', 'CGAAAG'], ['6UFH', 'A', 'GGAAAC'], ['6UFH', 'A', 'CGAAAG'], ['6WPI', 'B', 'UGAAAG'], ['7A0S', 'X', 'CGAGAG'], ['7A0S', 'X', 'GGAAAC'], ['7A0S', 'X', 'CGGGAG'], ['7A0S', 'X', 'AGCAAU'], ['7A0S', 'X', 'CGAAAG'], ['7A0S', 'X', 'AGCAAU'], ['7A0S', 'X', 'UGCAAG'], ['7A0S', 'X', 'CGUGAG'], ['7A0S', 'X', 'CGUGAG'], ['7A0S', 'Y', 'CGCAGG'], ['7A0S', 'X', 'CGCAAG'], ['7A0S', 'X', 'CGAACG'], ['7RQB', '1A', 'CGAAAG'], ['7RQB', '1A', 'CGUAAG'], ['7RQB', '1A', 'CGAGAG'], ['7RQB', '1A', 'CGGGAG'], ['7RQB', '1A', 'GGAAAC'], ['7RQB', '1A', 'CGAAAG'], ['7RQB', '1B', 'GGCGAC'], ['7RQB', '1A', 'CGUGAG'], ['7RQB', '1A', 'CGUGAG'], ['7RQB', '1A', 'UGCAAG'], ['7RQB', '1A', 'CGCGAG'], ['7RQB', '1A', 'CGCGAG'], ['7RQB', '1A', 'CGAAAG']]
['2IL9', '2ZZM', '3RG5', '3W3S', '2BTE']

In [3]:
motifs_ids[180]

['5TBW', '1', [1760, 1761, 1762, 1763, 1764, 1765]]

In [4]:
pdbl = PDB.PDBList()    #this is okay, because we have all the files but turned out that the dictionary is not sufficient to store the motifs' location because some files (same key) have multiple motifs. That is why cell above was changed and we no longer have the dictionary but this can remain the same.
#pdbl.download_pdb_files(motifs_nucs.keys(), file_format='mmCif', pdir='./mmCIF_files/')           #so this cell was only needed to be executed once therefore no change is applied

#new list of ids to get after changing cell above would be:
pdbl.download_pdb_files(list(map(lambda x: x[0], motifs_ids)), file_format='mmCif', pdir='./mmCIF_files/')

Structure exists: './mmCIF_files/1g1x.cif'
Structure exists: './mmCIF_files/1g1x.cif'
Structure exists: './mmCIF_files/1g1x.cif'
Structure exists: './mmCIF_files/1jid.cif'
Structure exists: './mmCIF_files/1g1x.cif'
Structure exists: './mmCIF_files/1kh6.cif'
Structure exists: './mmCIF_files/1kxk.cif'
Structure exists: './mmCIF_files/1l9a.cif'
Structure exists: './mmCIF_files/1m5k.cif'
Structure exists: './mmCIF_files/1l9a.cif'
Structure exists: './mmCIF_files/1mfq.cif'
Structure exists: './mmCIF_files/1mzp.cif'
Structure exists: './mmCIF_files/1mfq.cif'
Structure exists: './mmCIF_files/1rlg.cif'
Structure exists: './mmCIF_files/1nbs.cif'
Structure exists: './mmCIF_files/1u6b.cif'
Structure exists: './mmCIF_files/1q96.cif'
Structure exists: './mmCIF_files/1u6b.cif'
Structure exists: './mmCIF_files/1u9s.cif'
Structure exists: './mmCIF_files/1u9s.cif'
Structure exists: './mmCIF_files/2oiu.cif'
Structure exists: './mmCIF_files/1un6.cif'
Structure exists: './mmCIF_files/2oiu.cif'
Structure exists: './mmCIF_files/2r8s.cif'
Structure exists: './mmCIF_files/2z75.cif'
Structure exists: './mmCIF_files/3am1.cif'
Structure exists: './mmCIF_files/3e5c.cif'
Structure exists: './mmCIF_files/3igi.cif'
Structure exists: './mmCIF_files/3cul.cif'
Structure exists: './mmCIF_files/3igi.cif'
Structure exists: './mmCIF_files/3d0u.cif'
Structure exists: './mmCIF_files/3g9c.cif'
Structure exists: './mmCIF_files/3am1.cif'
Structure exists: './mmCIF_files/3e5c.cif'
Structure exists: './mmCIF_files/3ktw.cif'
Structure exists: './mmCIF_files/3iwn.cif'
Structure exists: './mmCIF_files/3lqx.cif'
Structure exists: './mmCIF_files/3moj.cif'
Structure exists: './mmCIF_files/3mxh.cif'
Structure exists: './mmCIF_files/3ndb.cif'
Structure exists: './mmCIF_files/3p22.cif'
Structure exists: './mmCIF_files/3nkb.cif'
Structure exists: './mmCIF_files/3npq.cif'
Structure exists: './mmCIF_files/3nmu.cif'
Structure exists: './mmCIF_files/3nvi.cif'
Structure exists: './mmCIF_files/3pdr.cif'
Structure exists: './mmCIF_files/3rw6.cif'
Structure exists: './mmCIF_files/4frg.cif'
Structure exists: './mmCIF_files/3sux.cif'
Structure exists: './mmCIF_files/3v7e.cif'
Structure exists: './mmCIF_files/4bw0.cif'
Structure exists: './mmCIF_files/4aob.cif'
Structure exists: './mmCIF_files/4enc.cif'
Structure exists: './mmCIF_files/4aob.cif'
Structure exists: './mmCIF_files/4jf2.cif'
Structure exists: './mmCIF_files/4c7o.cif'
Structure exists: './mmCIF_files/4k50.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4kqy.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4k27.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4oqu.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4lvw.cif'
Structure exists: './mmCIF_files/4oqu.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4pcj.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4lfb.cif'
Structure exists: './mmCIF_files/4oqu.cif'
Structure exists: './mmCIF_files/4plx.cif'
Structure exists: './mmCIF_files/4pqv.cif'
Structure exists: './mmCIF_files/4nlf.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4qk9.cif'
Structure exists: './mmCIF_files/4qk9.cif'
Structure exists: './mmCIF_files/4qlm.cif'
Structure exists: './mmCIF_files/4r4v.cif'
Structure exists: './mmCIF_files/4rum.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4v88.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4wfl.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4w90.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4y1m.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/4yaz.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4y1m.cif'
Structure exists: './mmCIF_files/5b2p.cif'
Structure exists: './mmCIF_files/5b2t.cif'
Structure exists: './mmCIF_files/4y1m.cif'
Structure exists: './mmCIF_files/5dcv.cif'
Structure exists: './mmCIF_files/4zt0.cif'
Structure exists: './mmCIF_files/4wf9.cif'
Structure exists: './mmCIF_files/5fjc.cif'
Structure exists: './mmCIF_files/5d5l.cif'
Structure exists: './mmCIF_files/5ddo.cif'
Structure exists: './mmCIF_files/5ddp.cif'
Structure exists: './mmCIF_files/4zt0.cif'
Structure exists: './mmCIF_files/5f9f.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5b2t.cif'
Structure exists: './mmCIF_files/5fjc.cif'
Structure exists: './mmCIF_files/5btm.cif'
Structure exists: './mmCIF_files/5fq5.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5ddo.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5fq5.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5f9r.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5m0j.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5m0j.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5m0i.cif'
Structure exists: './mmCIF_files/5m0i.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5m0h.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tpy.cif'
Structure exists: './mmCIF_files/5tpy.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5vci.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Structure exists: './mmCIF_files/6az4.cif'
Structure exists: './mmCIF_files/5u3g.cif'
Downloading PDB structure '6cb3'...
Structure exists: './mmCIF_files/5vw1.cif'
Downloading PDB structure '6cu1'...
Structure exists: './mmCIF_files/5xtm.cif'
Structure exists: './mmCIF_files/5y7m.cif'
Structure exists: './mmCIF_files/5xtm.cif'
Downloading PDB structure '6cb3'...
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/5uz6.cif'
Downloading PDB structure '6cb3'...
Structure exists: './mmCIF_files/5vw1.cif'
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/5x2g.cif'
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/6mj0.cif'
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/6n2v.cif'
Structure exists: './mmCIF_files/6n2v.cif'
Structure exists: './mmCIF_files/6dvk.cif'
Structure exists: './mmCIF_files/6jq5.cif'
Structure exists: './mmCIF_files/6joo.cif'
Structure exists: './mmCIF_files/6jdv.cif'
Structure exists: './mmCIF_files/6czr.cif'
Structure exists: './mmCIF_files/6dme.cif'
Structure exists: './mmCIF_files/6jq5.cif'
Structure exists: './mmCIF_files/6ufh.cif'
Structure exists: './mmCIF_files/6u8d.cif'
Structure exists: './mmCIF_files/6svs.cif'
Structure exists: './mmCIF_files/6ufh.cif'
Structure exists: './mmCIF_files/6jdv.cif'
Structure exists: './mmCIF_files/6ufg.cif'
Structure exists: './mmCIF_files/6ufh.cif'
Structure exists: './mmCIF_files/6n2v.cif'
Structure exists: './mmCIF_files/6ufg.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/6wpi.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7a0s.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'
Structure exists: './mmCIF_files/7rqb.cif'

In [5]:
len(motifs_ids)

249

In [6]:
files = os.listdir('./mmCIF_files/')
files.sort()
print(files)
print(len(files))

['1g1x.cif', '1jid.cif', '1kh6.cif', '1kxk.cif', '1l9a.cif', '1m5k.cif', '1mfq.cif', '1mzp.cif', '1nbs.cif', '1q96.cif', '1rlg.cif', '1u6b.cif', '1u9s.cif', '1un6.cif', '2oiu.cif', '2r8s.cif', '2z75.cif', '3am1.cif', '3cul.cif', '3d0u.cif', '3e5c.cif', '3g9c.cif', '3igi.cif', '3iwn.cif', '3ktw.cif', '3lqx.cif', '3moj.cif', '3mxh.cif', '3ndb.cif', '3nkb.cif', '3nmu.cif', '3npq.cif', '3nvi.cif', '3p22.cif', '3pdr.cif', '3rw6.cif', '3sux.cif', '3v7e.cif', '4aob.cif', '4bw0.cif', '4c7o.cif', '4enc.cif', '4frg.cif', '4jf2.cif', '4k27.cif', '4k50.cif', '4kqy.cif', '4lfb.cif', '4lvw.cif', '4nlf.cif', '4oqu.cif', '4pcj.cif', '4plx.cif', '4pqv.cif', '4qk9.cif', '4qlm.cif', '4r4v.cif', '4rum.cif', '4v88.cif', '4v9f.cif', '4w90.cif', '4wf9.cif', '4wfl.cif', '4y1m.cif', '4yaz.cif', '4zt0.cif', '5b2p.cif', '5b2t.cif', '5btm.cif', '5d5l.cif', '5dcv.cif', '5ddo.cif', '5ddp.cif', '5f9f.cif', '5f9r.cif', '5fjc.cif', '5fq5.cif', '5j7l.cif', '5m0h.cif', '5m0i.cif', '5m0j.cif', '5tbw.cif', '5tpy.cif', '5u3g.cif', '5uz6.cif', '5vci.cif', '5vw1.cif', '5x2g.cif', '5xtm.cif', '5y7m.cif', '6az4.cif', '6cb3.cif', '6cu1.cif', '6czr.cif', '6dme.cif', '6dvk.cif', '6jdv.cif', '6joo.cif', '6jq5.cif', '6mj0.cif', '6n2v.cif', '6svs.cif', '6u8d.cif', '6ufg.cif', '6ufh.cif', '6wpi.cif', '7a0s.cif', '7rqb.cif']
108

In [7]:
df = pd.DataFrame(index = range(len(motifs_ids)), columns=['N1', 'N2', 'N3', 'N4', 'N5', 'N6'])
df

      N1   N2   N3   N4   N5   N6
0    NaN  NaN  NaN  NaN  NaN  NaN
1    NaN  NaN  NaN  NaN  NaN  NaN
2    NaN  NaN  NaN  NaN  NaN  NaN
3    NaN  NaN  NaN  NaN  NaN  NaN
4    NaN  NaN  NaN  NaN  NaN  NaN
..   ...  ...  ...  ...  ...  ...
244  NaN  NaN  NaN  NaN  NaN  NaN
245  NaN  NaN  NaN  NaN  NaN  NaN
246  NaN  NaN  NaN  NaN  NaN  NaN
247  NaN  NaN  NaN  NaN  NaN  NaN
248  NaN  NaN  NaN  NaN  NaN  NaN

[249 rows x 6 columns]

In [8]:
parser = MMCIFParser(QUIET=True)

def get_atom_coordinates(df, seqs, motifs_ids, atom, ref):
    for i, motif in enumerate(motifs_ids):
        ref_seq = ref[i][2]
        motif_cords = []
        file_name = motif[0].lower() + '.cif'
        structure = parser.get_structure(file_name.rstrip('.cif'), f"./mmCIF_files/{file_name}")
        model = structure[0]
        chain = model[motif[1]]
        for j, motif_nuc in enumerate(motif[2]):
            res = chain[motif_nuc]
            if res.resname != ref_seq[j]: 
                print(f'Resname in pdb: {res.resname}    my resanme: {ref_seq[j]}  in {motif[0]}')
                raise Exception('WRONG RESIDUE')
            if atom not in res: raise Exception('Given atom not found in a residue') #at=res['C'] 
            else: at = res[atom]
            motif_cords.append(at.get_coord())
        seqs.append(ref_seq)
        df.iloc[i] = motif_cords
    return df, seqs

In [9]:
def compute_new_coords(res):
    if res.resname in "AG":
        atom_names = ("C1'", "N9", "C2", "N7")
    elif res.resname in "CU":
        atom_names = ("C1'", "N1", "C2", "C5")
    else:
        raise Exception('nucleotide not found')
    atoms = [res[name] for name in atom_names]
    if any(a is None for a in atoms):
        raise ValueError("Missing atom")
    c1p, n1n9, c2, c5n7 = atoms
    # X axis points from N1/N9 into Watson-Crick-Franklin edge
    x_axis = c2.get_coord() - n1n9.get_coord()
    x_axis /= np.linalg.norm(x_axis)

    # Y axis points from N1/N9 perpendicular to base plane
    tmp = c5n7.get_coord() - n1n9.get_coord()
    y_axis = np.cross(x_axis, tmp)
    y_axis /= np.linalg.norm(y_axis)

    # Z axis is just orthogonal to X and Y axis (and points towards Hoogsteen edge)
    z_axis = np.cross(x_axis, y_axis)
    z_axis /= np.linalg.norm(z_axis)

    origin = c1p.get_coord()
    matrix = np.matrix([x_axis, y_axis, z_axis])

    return origin, matrix

In [10]:
def transform(atom, origin, matrix):
    return (atom.get_coord() - origin) * matrix

In [13]:
def get_atom_coordinates_v2(df, motifs_ids, atom, ref):
    for i, motif in enumerate(motifs_ids):
        ref_seq = ref[i][2]
        motif_cords = []
        file_name = motif[0].lower() + '.cif'
        structure = parser.get_structure(file_name.rstrip('.cif'), f"./mmCIF_files/{file_name}")
        model = structure[0]
        chain = model[motif[1]]
        print(f'get atom coordinates i:{i}')
        for j, motif_nuc in enumerate(motif[2]):
            res = chain[motif_nuc]
            if res.resname != ref_seq[j]: 
                print(f'Resname in pdb: {res.resname}    my resanme: {ref_seq[j]}  in {motif[0]}')
                raise Exception('WRONG RESIDUE')
            if j == 0:
                origin, matrix = compute_new_coords(res)

            if atom not in res: raise Exception('Given atom not found in a residue')  
            else: at = res[atom]
            motif_cords.append(transform(at, origin, matrix))

        df.iloc[i] = motif_cords
    return df

In [14]:
database_v2 = get_atom_coordinates_v2(df, motifs_ids, "C1'", motifs_nucs)
print(database_v2)

get atom coordinates i:0
get atom coordinates i:1
get atom coordinates i:2
get atom coordinates i:3
get atom coordinates i:4
get atom coordinates i:5
get atom coordinates i:6
get atom coordinates i:7
get atom coordinates i:8
get atom coordinates i:9
get atom coordinates i:10
get atom coordinates i:11
get atom coordinates i:12
get atom coordinates i:13
get atom coordinates i:14
get atom coordinates i:15
get atom coordinates i:16
get atom coordinates i:17
get atom coordinates i:18
get atom coordinates i:19
get atom coordinates i:20
get atom coordinates i:21
get atom coordinates i:22
get atom coordinates i:23
get atom coordinates i:24
get atom coordinates i:25
get atom coordinates i:26
get atom coordinates i:27
get atom coordinates i:28
get atom coordinates i:29
get atom coordinates i:30
get atom coordinates i:31
get atom coordinates i:32
get atom coordinates i:33
get atom coordinates i:34
get atom coordinates i:35
get atom coordinates i:36
get atom coordinates i:37
get atom coordinates i:38
get atom coordinates i:39
get atom coordinates i:40
get atom coordinates i:41
get atom coordinates i:42
get atom coordinates i:43
get atom coordinates i:44
get atom coordinates i:45
get atom coordinates i:46
get atom coordinates i:47
get atom coordinates i:48
get atom coordinates i:49
get atom coordinates i:50
get atom coordinates i:51
get atom coordinates i:52
get atom coordinates i:53
get atom coordinates i:54
get atom coordinates i:55
get atom coordinates i:56
get atom coordinates i:57
get atom coordinates i:58
get atom coordinates i:59
get atom coordinates i:60
get atom coordinates i:61
get atom coordinates i:62
get atom coordinates i:63
get atom coordinates i:64
get atom coordinates i:65
get atom coordinates i:66
get atom coordinates i:67
get atom coordinates i:68
get atom coordinates i:69
get atom coordinates i:70
get atom coordinates i:71
get atom coordinates i:72
get atom coordinates i:73
get atom coordinates i:74
get atom coordinates i:75
get atom coordinates i:76
get atom coordinates i:77
get atom coordinates i:78
get atom coordinates i:79
get atom coordinates i:80
get atom coordinates i:81
get atom coordinates i:82
get atom coordinates i:83
get atom coordinates i:84
get atom coordinates i:85
get atom coordinates i:86
get atom coordinates i:87
get atom coordinates i:88
get atom coordinates i:89
get atom coordinates i:90
get atom coordinates i:91
get atom coordinates i:92
get atom coordinates i:93
get atom coordinates i:94
get atom coordinates i:95
get atom coordinates i:96
get atom coordinates i:97
get atom coordinates i:98
get atom coordinates i:99
get atom coordinates i:100
get atom coordinates i:101
get atom coordinates i:102
get atom coordinates i:103
get atom coordinates i:104
get atom coordinates i:105
get atom coordinates i:106
get atom coordinates i:107
get atom coordinates i:108
get atom coordinates i:109
get atom coordinates i:110
get atom coordinates i:111
get atom coordinates i:112
get atom coordinates i:113
get atom coordinates i:114
get atom coordinates i:115
get atom coordinates i:116
get atom coordinates i:117
get atom coordinates i:118
get atom coordinates i:119
get atom coordinates i:120
get atom coordinates i:121
get atom coordinates i:122
get atom coordinates i:123
get atom coordinates i:124
get atom coordinates i:125
get atom coordinates i:126
get atom coordinates i:127
get atom coordinates i:128
get atom coordinates i:129
get atom coordinates i:130
get atom coordinates i:131
get atom coordinates i:132
get atom coordinates i:133
get atom coordinates i:134
get atom coordinates i:135
get atom coordinates i:136
get atom coordinates i:137
get atom coordinates i:138
get atom coordinates i:139
get atom coordinates i:140
get atom coordinates i:141
get atom coordinates i:142
get atom coordinates i:143
get atom coordinates i:144
get atom coordinates i:145
get atom coordinates i:146
get atom coordinates i:147
get atom coordinates i:148
get atom coordinates i:149
get atom coordinates i:150
get atom coordinates i:151
get atom coordinates i:152
get atom coordinates i:153
get atom coordinates i:154
get atom coordinates i:155
get atom coordinates i:156
get atom coordinates i:157
get atom coordinates i:158
get atom coordinates i:159
get atom coordinates i:160
get atom coordinates i:161
get atom coordinates i:162
get atom coordinates i:163
get atom coordinates i:164
get atom coordinates i:165
get atom coordinates i:166
get atom coordinates i:167
get atom coordinates i:168
get atom coordinates i:169
get atom coordinates i:170
get atom coordinates i:171
get atom coordinates i:172
get atom coordinates i:173
get atom coordinates i:174
get atom coordinates i:175
get atom coordinates i:176
get atom coordinates i:177
get atom coordinates i:178
get atom coordinates i:179
get atom coordinates i:180
get atom coordinates i:181
get atom coordinates i:182
get atom coordinates i:183
get atom coordinates i:184
get atom coordinates i:185
get atom coordinates i:186
get atom coordinates i:187
get atom coordinates i:188
get atom coordinates i:189
get atom coordinates i:190
get atom coordinates i:191
get atom coordinates i:192
get atom coordinates i:193
get atom coordinates i:194
get atom coordinates i:195
get atom coordinates i:196
get atom coordinates i:197
get atom coordinates i:198
get atom coordinates i:199
get atom coordinates i:200
get atom coordinates i:201
get atom coordinates i:202
get atom coordinates i:203
get atom coordinates i:204
get atom coordinates i:205
get atom coordinates i:206
get atom coordinates i:207
get atom coordinates i:208
get atom coordinates i:209
get atom coordinates i:210
get atom coordinates i:211
get atom coordinates i:212
get atom coordinates i:213
get atom coordinates i:214
get atom coordinates i:215
get atom coordinates i:216
get atom coordinates i:217
get atom coordinates i:218
get atom coordinates i:219
get atom coordinates i:220
get atom coordinates i:221
get atom coordinates i:222
get atom coordinates i:223
get atom coordinates i:224
get atom coordinates i:225
get atom coordinates i:226
get atom coordinates i:227
get atom coordinates i:228
get atom coordinates i:229
get atom coordinates i:230
get atom coordinates i:231
get atom coordinates i:232
get atom coordinates i:233
get atom coordinates i:234
get atom coordinates i:235
get atom coordinates i:236
get atom coordinates i:237
get atom coordinates i:238
get atom coordinates i:239
get atom coordinates i:240
get atom coordinates i:241
get atom coordinates i:242
get atom coordinates i:243
get atom coordinates i:244
get atom coordinates i:245
get atom coordinates i:246
get atom coordinates i:247
get atom coordinates i:248
                     N1                                             N2  \
0    [[[[[0. 0. 0.]]]]]     [[[[[4.536676   3.4729254  0.48034233]]]]]
1    [[[[[0. 0. 0.]]]]]     [[[[[-1.6014824  1.9751408  4.8102007]]]]]
2    [[[[[0. 0. 0.]]]]]        [[[[[3.7277818 0.8293729 4.0235014]]]]]
3    [[[[[0. 0. 0.]]]]]     [[[[[-2.951724  -1.1689231  3.726684 ]]]]]
4    [[[[[0. 0. 0.]]]]]     [[[[[ 4.1216917 -1.8999128  2.96813  ]]]]]
..                  ...                                            ...
244  [[[[[0. 0. 0.]]]]]     [[[[[-2.7558198  4.2601476  2.0261545]]]]]
245  [[[[[0. 0. 0.]]]]]     [[[[[5.002955   2.411758   0.55514073]]]]]
246  [[[[[0. 0. 0.]]]]]  [[[[[-3.9391382  -0.03408813 -3.9700904 ]]]]]
247  [[[[[0. 0. 0.]]]]]     [[[[[3.609532   4.1005445  0.35965553]]]]]
248  [[[[[0. 0. 0.]]]]]     [[[[[-3.428944  -2.214357   3.2601802]]]]]

                                                N3  \
0          [[[[[7.4217796 9.983614  1.2658103]]]]]
1       [[[[[-1.1244587  3.7502747 11.776506 ]]]]]
2       [[[[[ 7.065468  -0.4573351 10.159253 ]]]]]
3    [[[[[-10.044762   -1.4295628   6.722746 ]]]]]
4       [[[[[ 8.53245   -6.106925   7.3941545]]]]]
..                                             ...
244     [[[[[-5.1642327 11.523331   0.7999604]]]]]
245  [[[[[ 9.037789    8.474492   -0.12090778]]]]]
246  [[[[[-11.094664   -0.9893875  -5.5698977]]]]]
247     [[[[[ 6.2353444 10.537656  -2.8332071]]]]]
248  [[[[[-10.123348   -7.245481    4.8659134]]]]]

                                                N4  \
0       [[[[[10.439151   7.174957  -1.7811584]]]]]
1    [[[[[-5.1592617   0.53340614 12.517039  ]]]]]
2       [[[[[ 6.4484572  4.6278653 11.217654 ]]]]]
3       [[[[[-9.504647   3.4176064  6.810903 ]]]]]
4       [[[[[11.214915  -1.2099619  8.714401 ]]]]]
..                                             ...
244     [[[[[-3.3771973 10.797951   5.725317 ]]]]]
245     [[[[[11.341217   4.6650386 -2.014308 ]]]]]
246     [[[[[-8.0267105 -3.290452  -9.318319 ]]]]]
247     [[[[[10.274817   7.8239813 -1.2336954]]]]]
248  [[[[[-12.650587   -2.2217093   6.697694 ]]]]]

                                                N5  \
0       [[[[[12.900384   2.780225  -2.8478267]]]]]
1       [[[[[-9.866037  -0.5892246 10.64534  ]]]]]
2             [[[[[6.600692 9.653525 8.614188]]]]]
3       [[[[[-6.2287717  7.593501   9.633769 ]]]]]
4       [[[[[13.329173   3.4039814  6.692686 ]]]]]
..                                             ...
244     [[[[[-2.0991654  8.937706  10.558783 ]]]]]
245  [[[[[13.538468    0.15294361 -3.4848807 ]]]]]
246     [[[[[ -4.243762  -4.689619 -13.055882]]]]]
247     [[[[[13.498926   4.9764624  2.0965042]]]]]
248  [[[[[-11.017469    1.5819148   9.870329 ]]]]]

                                                   N6
0          [[[[[10.000698  -0.9084511 -3.2807057]]]]]
1          [[[[[-8.773235  -1.129053   5.5766826]]]]]
2             [[[[[3.966319  8.721888  4.6409445]]]]]
3          [[[[[-1.052121   6.4639053  8.025622 ]]]]]
4             [[[[[8.834543  4.3820333 3.7435534]]]]]
..                                                ...
244        [[[[[0.22525167 4.6521425  9.541818  ]]]]]
245        [[[[[ 9.670107  -3.4167085 -2.553907 ]]]]]
246  [[[[[ -0.15208721  -4.251002   -10.051937  ]]]]]
247        [[[[[10.256958   0.7676364  2.4409256]]]]]
248        [[[[[-6.544441   3.1118624  7.676771 ]]]]]

[249 rows x 6 columns]

In [15]:
database, sequences = get_atom_coordinates(df, [], motifs_ids, "C1'", motifs_nucs)
print(database)
print(sequences)

                              N1                           N2  \
0       [72.379, 32.575, 10.796]      [77.895, 33.755, 9.769]
1       [14.263, 65.819, 16.505]     [12.633, 71.007, 16.327]
2       [54.509, 39.342, 49.313]     [60.011, 39.781, 49.868]
3        [2.716, 78.732, 56.751]       [1.84, 82.233, 60.059]
4        [13.564, 1.567, 34.626]      [17.065, 3.703, 38.174]
..                           ...                          ...
244     [90.13, -27.415, -13.33]   [88.613, -27.251, -18.576]
245   [99.603, -27.307, -86.447]   [98.735, -25.749, -91.736]
246      [12.82, -40.452, 49.71]    [13.097, -36.791, 45.491]
247  [85.871, -113.233, -36.136]  [88.489, -108.437, -35.794]
248   [53.276, -26.732, -54.919]   [56.382, -30.921, -55.227]

                              N3                          N4  \
0        [84.753, 31.765, 9.188]    [84.547, 36.507, 11.124]
1          [8.943, 76.9, 18.215]      [7.04, 76.843, 13.362]
2        [66.82, 38.868, 48.066]    [67.582, 37.195, 52.963]
3       [-1.302, 89.045, 61.814]     [2.221, 90.716, 58.883]
4         [20.272, 6.608, 44.34]     [24.028, 9.055, 40.759]
..                           ...                         ...
244     [86.9, -22.725, -24.629]  [83.582, -26.819, -24.172]
245  [101.652, -24.045, -98.223]  [98.279, -20.815, -96.961]
246     [9.362, -32.846, 40.475]    [13.796, -34.92, 38.285]
247  [94.064, -104.485, -32.355]   [90.002, -101.396, -32.8]
248    [61.706, -36.05, -59.476]   [57.471, -40.091, -58.63]

                             N5                           N6
0      [82.675, 41.303, 11.068]     [78.004, 41.475, 11.663]
1         [8.532, 76.432, 8.41]      [11.439, 72.111, 8.645]
2      [65.914, 38.341, 58.251]     [61.112, 38.748, 57.643]
3       [8.213, 91.183, 58.757]      [9.909, 85.912, 58.753]
4        [27.216, 8.24, 36.398]      [23.132, 5.894, 33.628]
..                          ...                          ...
244  [81.266, -31.551, -23.335]   [82.567, -32.633, -18.651]
245  [94.253, -17.913, -95.312]    [93.081, -20.084, -90.57]
246   [18.834, -36.739, 37.041]    [19.426, -39.836, 41.043]
247   [85.863, -98.73, -35.114]  [82.935, -103.078, -36.044]
248  [54.773, -41.524, -54.403]   [52.631, -37.053, -52.796]

[249 rows x 6 columns]
['CGAAAG', 'CGAAGG', 'CGAAGG', 'CGAAAG', 'GGGAGC', 'CGAAAG', 'UGAAAG', 'GGAAAC', 'GGGAGC', 'GGAAAC', 'GGAAAC', 'GGGAGC', 'CGCAAG', 'AGAAAU', 'UGAGAA', 'CGAAAG', 'GGAAAC', 'CAAACG', 'GGCAAC', 'GGUAAC', 'GGAAAC', 'CGAAAG', 'CGAAAG', 'GGAAAC', 'GGCGAC', 'CGAGAG', 'CUUCGG', 'CGAAAG', 'CGAAAG', 'GGAAAC', 'CGAAAG', 'GGUGAC', 'GGAAAC', 'GGCGAC', 'CGAAAG', 'CGGAAG', 'CGAAAG', 'GGAAAC', 'CGAAAG', 'CGGAAG', 'CGAAAG', 'CGAAAG', 'CGAGAG', 'CGAAAG', 'CGAAAG', 'CCAAAG', 'GGAAAC', 'CGAAAG', 'GGAAAC', 'GGAAAC', 'AAAAAU', 'CGAAAG', 'CGGAAG', 'UGAAAA', 'CGAAAG', 'CGAAAG', 'UGAAAG', 'UGAAAG', 'CGAAAG', 'CGAAAG', 'CGCAAG', 'CGCAAG', 'CUAACG', 'GGAAAC', 'GGCAAC', 'UGAGAG', 'UGAAAG', 'CGUGAG', 'CGAAGG', 'CGAGAG', 'CGAGAG', 'GGAGAC', 'GGAGAC', 'CGAGAG', 'UGAAAG', 'CGAAAG', 'CGAAAG', 'CGUAAG', 'CUGAAG', 'CGAAAG', 'CGUAAG', 'CGAAAG', 'CGCAAG', 'AGAAAU', 'AGUGAU', 'CGAAAG', 'GUAAUC', 'GUGAAC', 'CGAGAG', 'CAGCCG', 'CGAAAG', 'CGGGAG', 'CGCGAG', 'CGAGAG', 'CGCAAG', 'CUCACG', 'GGAAAC', 'CGGAAG', 'GGUAAC', 'GGAAAC', 'CGAAAG', 'GGUAAC', 'CGUGAG', 'UGUGAA', 'CGCGAG', 'CGAGAG', 'GCAACC', 'UUCAAG', 'CGAAAG', 'CGAGAG', 'CGGAAG', 'CGAAAG', 'CGAAAG', 'UGAAAG', 'GGUGAC', 'CGUGAG', 'CGUGAG', 'CGACAG', 'GGUAAC', 'UGAAAA', 'CGAAAG', 'AGAAAU', 'CGCGAG', 'AGAAAU', 'UGAAAA', 'CGAAAG', 'UGAAAA', 'AGAAAU', 'UGAAAG', 'CGAAAG', 'GGAAAC', 'GGAAAC', 'GGAAAC', 'GGAAAC', 'AGUGAU', 'UGAAAA', 'AGAAAU', 'GGAAAC', 'AGAAAU', 'UGAAAA', 'CGCAAG', 'CGCAAG', 'CGAGAG', 'CGCAAG', 'GGAAAC', 'CUAACG', 'GGAAAC', 'CGAAAG', 'AGCGAU', 'CGUGAG', 'UGAGAG', 'CGUGAG', 'UGACGG', 'CGAAGG', 'CGCGAG', 'UGUGAA', 'CGAAAG', 'UGUGAG', 'CGCAAG', 'UGAAAG', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'CGAGAG', 'CGCAAG', 'CGUAAG', 'GGUGAC', 'CGAAAG', 'AGAAAU', 'AGAAAU', 'GGAAAC', 'AGUGAU', 'CGUGAG', 'GGUAAC', 'UGAAAG', 'UGAAAG', 'GGUAAC', 'CGUAAG', 'GAAGCU', 'ACCUUU', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'AGAAAU', 'UGAAAA', 'UGAAAA', 'GGAAAC', 'GGAAAC', 'CGAAAG', 'UGAAAG', 'GGAAAC', 'CGAAAG', 'GGAAAC', 'CGAAAG', 'CGCAAG', 'CGCAAG', 'UGAGAG', 'CUAACG', 'CGAAAG', 'GGAAAC', 'CGUGAG', 'CGAAGG', 'CGAGAG', 'GGAAAC', 'UGAAAA', 'GGAAAC', 'GGAAAC', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'GGAAAC', 'CGAAAG', 'GGAAAC', 'CGAAAG', 'CGAAAG', 'CGAAAG', 'GGAAAC', 'CGAAAG', 'UGAAAG', 'CGAGAG', 'GGAAAC', 'CGGGAG', 'AGCAAU', 'CGAAAG', 'AGCAAU', 'UGCAAG', 'CGUGAG', 'CGUGAG', 'CGCAGG', 'CGCAAG', 'CGAACG', 'CGAAAG', 'CGUAAG', 'CGAGAG', 'CGGGAG', 'GGAAAC', 'CGAAAG', 'GGCGAC', 'CGUGAG', 'CGUGAG', 'UGCAAG', 'CGCGAG', 'CGCGAG', 'CGAAAG']

In [16]:
for column in database.columns:
    database[column] = database[column].apply(lambda x: ','.join(map(str, x)))

database['class'] = 1
database

,N1,N2,N3,N4,N5,N6,class
0,"72.379,32.575,10.796","77.895,33.755,9.769","84.753,31.765,9.188","84.547,36.507,11.124","82.675,41.303,11.068","78.004,41.475,11.663",1
1,"14.263,65.819,16.505","12.633,71.007,16.327","8.943,76.9,18.215","7.04,76.843,13.362","8.532,76.432,8.41","11.439,72.111,8.645",1
2,"54.509,39.342,49.313","60.011,39.781,49.868","66.82,38.868,48.066","67.582,37.195,52.963","65.914,38.341,58.251","61.112,38.748,57.643",1
3,"2.716,78.732,56.751","1.84,82.233,60.059","-1.302,89.045,61.814","2.221,90.716,58.883","8.213,91.183,58.757","9.909,85.912,58.753",1
4,"13.564,1.567,34.626","17.065,3.703,38.174","20.272,6.608,44.34","24.028,9.055,40.759","27.216,8.24,36.398","23.132,5.894,33.628",1
...,...,...,...,...,...,...,...
244,"90.13,-27.415,-13.33","88.613,-27.251,-18.576","86.9,-22.725,-24.629","83.582,-26.819,-24.172","81.266,-31.551,-23.335","82.567,-32.633,-18.651",1
245,"99.603,-27.307,-86.447","98.735,-25.749,-91.736","101.652,-24.045,-98.223","98.279,-20.815,-96.961","94.253,-17.913,-95.312","93.081,-20.084,-90.57",1
246,"12.82,-40.452,49.71","13.097,-36.791,45.491","9.362,-32.846,40.475","13.796,-34.92,38.285","18.834,-36.739,37.041","19.426,-39.836,41.043",1
247,"85.871,-113.233,-36.136","88.489,-108.437,-35.794","94.064,-104.485,-32.355","90.002,-101.396,-32.8","85.863,-98.73,-35.114","82.935,-103.078,-36.044",1
248,"53.276,-26.732,-54.919","56.382,-30.921,-55.227","61.706,-36.05,-59.476","57.471,-40.091,-58.63","54.773,-41.524,-54.403","52.631,-37.053,-52.796",1

In [17]:
for column in database_v2.columns:
    database_v2[column] = database_v2[column].apply(lambda x: ','.join(map(str,np.array(x).flatten())))

database_v2['class'] = 1
database_v2

,N1,N2,N3,N4,N5,N6,class
0,"72.379,32.575,10.796","77.895,33.755,9.769","84.753,31.765,9.188","84.547,36.507,11.124","82.675,41.303,11.068","78.004,41.475,11.663",1
1,"14.263,65.819,16.505","12.633,71.007,16.327","8.943,76.9,18.215","7.04,76.843,13.362","8.532,76.432,8.41","11.439,72.111,8.645",1
2,"54.509,39.342,49.313","60.011,39.781,49.868","66.82,38.868,48.066","67.582,37.195,52.963","65.914,38.341,58.251","61.112,38.748,57.643",1
3,"2.716,78.732,56.751","1.84,82.233,60.059","-1.302,89.045,61.814","2.221,90.716,58.883","8.213,91.183,58.757","9.909,85.912,58.753",1
4,"13.564,1.567,34.626","17.065,3.703,38.174","20.272,6.608,44.34","24.028,9.055,40.759","27.216,8.24,36.398","23.132,5.894,33.628",1
...,...,...,...,...,...,...,...
244,"90.13,-27.415,-13.33","88.613,-27.251,-18.576","86.9,-22.725,-24.629","83.582,-26.819,-24.172","81.266,-31.551,-23.335","82.567,-32.633,-18.651",1
245,"99.603,-27.307,-86.447","98.735,-25.749,-91.736","101.652,-24.045,-98.223","98.279,-20.815,-96.961","94.253,-17.913,-95.312","93.081,-20.084,-90.57",1
246,"12.82,-40.452,49.71","13.097,-36.791,45.491","9.362,-32.846,40.475","13.796,-34.92,38.285","18.834,-36.739,37.041","19.426,-39.836,41.043",1
247,"85.871,-113.233,-36.136","88.489,-108.437,-35.794","94.064,-104.485,-32.355","90.002,-101.396,-32.8","85.863,-98.73,-35.114","82.935,-103.078,-36.044",1
248,"53.276,-26.732,-54.919","56.382,-30.921,-55.227","61.706,-36.05,-59.476","57.471,-40.091,-58.63","54.773,-41.524,-54.403","52.631,-37.053,-52.796",1

In [18]:
database.to_csv("database_C1'.csv")

In [19]:
database_v2.to_csv("./modified_coord/C1'_GNRA.csv")

In [20]:
import csv

with open("database_C1'_seqs.csv", 'w', newline='') as f:
     
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for item in sequences:
        write.writerow([item])

<h2> Teraz esktrakcja i przygotowanie danych do klasy przeciwnej - braku motywu </h2>

<h4>Stem motifs</h4>

In [23]:
stems = pd.read_csv('./rnasolo-3.218-dbn-csv/stems_u.txt', sep=' ', header=None, names=['ID', 'start_1', 'end_1', 'seq_1', 'braq_1', 'start_2', 'end_2', 'seq_2', 'braq_2'])
stems['chain'] = list(map(lambda x: x.split('_')[2].rsplit('-motifs.txt:Stem')[0], stems['ID']))
stems['ID'] = list(map(lambda x: x[:x.find('_')], stems['ID']))
stems = stems[stems['braq_1'] != '[[[']
stems = stems[~stems['chain'].str.contains('-')]
stems = stems[~stems['ID'].duplicated()]
stems = stems.reset_index(drop=True)
stems

       ID  start_1  end_1 seq_1 braq_1  start_2  end_2 seq_2 braq_2 chain
0    1A60       18     20   CCC    (((       30     32   GGG    )))     A
1    1B23        9     11   ACA    (((       19     21   UGU    )))     R
2    1BVJ        7      9   GGU    (((       16     18   AUC    )))     A
3    1C2W       30     32   GCC    (((      473    475   GGC    )))     B
4    1C2X       19     21   CGG    (((       62     64   CCG    )))     C
..    ...      ...    ...   ...    ...      ...    ...   ...    ...   ...
478  7P3K       26     28   CCG    (((       40     42   CGG    )))     V
479  7QEP       40     42   GGA    (((       81     83   UCU    )))     1
480  7R81       10     12   GCC    (((       23     25   GGC    )))    t1
481  7RQB        1      3   AGA    (((     2859   2861   UCU    )))    1A
482  7RYG       53     55   AGA    (((      113    115   UCU    )))     A

[483 rows x 10 columns]

In [24]:
stems_ids = stems['ID']
already_downloaded_ids = list(map(lambda x: x[0],motifs_ids))
same_elements = set(stems_ids).intersection(already_downloaded_ids)
different_elements = set(stems_ids).difference(already_downloaded_ids)
print(len(same_elements))
print(len(different_elements))

different_elements = different_elements.intersection([x.rstrip('.cif').upper() for x in files])
print(len(different_elements))
different_elements = list(different_elements)
stem_ids = list(same_elements) + different_elements[:55]
print(len(stem_ids))

### from the first database creation:
stem_ids = [
    '1BVJ', '1CQL', '1F84', '1HS4', '1KUQ', '1KXK', '1LC6', '1M5K', '1MZP', '1P5P',
    '2OIU', '3AM1', '3D0U', '3G9C', '3IGI', '3IWN', '3JBV', '3RW6', '3SUX', '3V7E',
    '4AOB', '4BW0', '4LVW', '4OQU', '4V5O', '4V8M', '4WSM', '5B2P', '5FJ4', '5FJC',
    '5J7L', '5TBW', '5U3G', '5XTM', '5Y7M', '6DU5', '6DVK', '6JDV', '6N2V', '6ORD',
    '6UZ7', '6Z6M', '6ZYM', '7A0S', '7AC7', '7FJ0', '7O80'
]

58
425
0
58

In [25]:
pdbl = PDB.PDBList()   
pdbl.download_pdb_files(stem_ids, file_format='mmCif', pdir='./mmCIF_files/')

Downloading PDB structure '1bvj'...
Downloading PDB structure '1cql'...
Downloading PDB structure '1f84'...
Downloading PDB structure '1hs4'...
Downloading PDB structure '1kuq'...
Structure exists: './mmCIF_files/1kxk.cif'
Downloading PDB structure '1lc6'...
Structure exists: './mmCIF_files/1m5k.cif'
Structure exists: './mmCIF_files/1mzp.cif'
Downloading PDB structure '1p5p'...
Structure exists: './mmCIF_files/3am1.cif'
Structure exists: './mmCIF_files/2oiu.cif'
Structure exists: './mmCIF_files/3d0u.cif'
Structure exists: './mmCIF_files/3g9c.cif'
Structure exists: './mmCIF_files/3igi.cif'
Downloading PDB structure '3jbv'...
Structure exists: './mmCIF_files/3rw6.cif'
Structure exists: './mmCIF_files/3iwn.cif'
Structure exists: './mmCIF_files/3v7e.cif'
Structure exists: './mmCIF_files/3sux.cif'
Structure exists: './mmCIF_files/4aob.cif'
Structure exists: './mmCIF_files/4bw0.cif'
Structure exists: './mmCIF_files/4lvw.cif'
Structure exists: './mmCIF_files/4oqu.cif'
Downloading PDB structure '4v8m'...
Downloading PDB structure '4v5o'...
Downloading PDB structure '4wsm'...
Structure exists: './mmCIF_files/5b2p.cif'
Downloading PDB structure '5fj4'...
Structure exists: './mmCIF_files/5j7l.cif'
Structure exists: './mmCIF_files/5fjc.cif'
Structure exists: './mmCIF_files/5y7m.cif'
Structure exists: './mmCIF_files/5u3g.cif'
Structure exists: './mmCIF_files/5xtm.cif'
Structure exists: './mmCIF_files/6dvk.cif'
Structure exists: './mmCIF_files/5tbw.cif'
Downloading PDB structure '6ord'...
Downloading PDB structure '6du5'...
Structure exists: './mmCIF_files/6jdv.cif'
Structure exists: './mmCIF_files/6n2v.cif'
Downloading PDB structure '6uz7'...
Downloading PDB structure '6z6m'...
Downloading PDB structure '6zym'...
Structure exists: './mmCIF_files/7a0s.cif'
Downloading PDB structure '7ac7'...
Downloading PDB structure '7fj0'...
Downloading PDB structure '7o80'...

In [26]:
stems_complete = []
for index, row in stems.iterrows():
    if row['ID'] in stem_ids:
        if len(stems_complete) == 120:
            break
        seqs = list(range(int(row['start_1']), int(row['end_1']+1))) + list(range(int(row['start_2']), int(row['end_2']+1)))
        stems_complete.append([row['ID'], row['chain'], seqs])

In [27]:
print(len(stems_complete))
stems_complete

47

[['1BVJ', 'A', [7, 8, 9, 16, 17, 18]],
 ['1CQL', 'A', [12, 13, 14, 33, 34, 35]],
 ['1F84', 'A', [10, 11, 12, 19, 20, 21]],
 ['1HS4', 'A', [1, 2, 3, 10, 11, 12]],
 ['1KUQ', 'B', [6, 7, 8, 13, 14, 15]],
 ['1KXK', 'A', [6, 7, 8, 62, 63, 64]],
 ['1LC6', 'A', [7, 8, 9, 15, 16, 17]],
 ['1M5K', 'B', [68, 69, 70, 81, 82, 83]],
 ['1MZP', 'B', [23, 24, 25, 30, 31, 32]],
 ['1P5P', 'A', [23, 24, 25, 58, 59, 60]],
 ['2OIU', 'P', [8, 9, 10, 15, 16, 17]],
 ['3AM1', 'B', [30, 31, 32, 37, 38, 39]],
 ['3D0U', 'A', [79, 80, 81, 108, 109, 110]],
 ['3G9C', 'Q', [28, 29, 30, 42, 43, 44]],
 ['3IGI', 'A', [27, 28, 29, 37, 38, 39]],
 ['3IWN', 'A', [40, 41, 42, 82, 83, 84]],
 ['3JBV', 'W', [10, 11, 12, 23, 24, 25]],
 ['3RW6', 'H', [17, 18, 19, 40, 41, 42]],
 ['3SUX', 'X', [21, 22, 23, 74, 75, 76]],
 ['3V7E', 'C', [15, 16, 17, 38, 39, 40]],
 ['4AOB', 'A', [15, 16, 17, 38, 39, 40]],
 ['4BW0', 'A', [1, 2, 3, 23, 24, 25]],
 ['4LVW', 'A', [18, 19, 20, 65, 66, 67]],
 ['4OQU', 'A', [22, 23, 24, 48, 49, 50]],
 ['4V5O', 'BA', [47, 48, 49, 421, 422, 423]],
 ['4V8M', 'AA', [35, 36, 37, 541, 542, 543]],
 ['4WSM', '3L', [28, 29, 30, 40, 41, 42]],
 ['5B2P', 'B', [22, 23, 24, 50, 51, 52]],
 ['5FJ4', 'H', [1, 2, 3, 33, 34, 35]],
 ['5FJC', 'A', [14, 15, 16, 37, 38, 39]],
 ['5J7L', 'DA', [54, 55, 56, 114, 115, 116]],
 ['5TBW', 'AS', [30, 31, 32, 45, 46, 47]],
 ['5U3G', 'B', [65, 66, 67, 75, 76, 77]],
 ['5XTM', 'B', [5, 6, 7, 38, 39, 40]],
 ['5Y7M', 'D', [5, 6, 7, 43, 44, 45]],
 ['6DU5', 'B', [5, 6, 7, 21, 22, 23]],
 ['6DVK', 'H', [43, 44, 45, 50, 51, 52]],
 ['6JDV', 'B', [79, 80, 81, 97, 98, 99]],
 ['6N2V', 'A', [13, 14, 15, 85, 86, 87]],
 ['6ORD', 'QY', [4, 5, 6, 67, 68, 69]],
 ['6UZ7', '7', [30, 31, 32, 45, 46, 47]],
 ['6Z6M', 'CC', [10, 11, 12, 23, 24, 25]],
 ['6ZYM', '6', [62, 63, 64, 70, 71, 72]],
 ['7A0S', 'X', [53, 54, 55, 112, 113, 114]],
 ['7AC7', '4', [21, 22, 23, 330, 331, 332]],
 ['7FJ0', 'A', [5, 6, 7, 13, 14, 15]],
 ['7O80', 'AT', [10, 11, 12, 23, 24, 25]]]

In [28]:
parser = MMCIFParser(QUIET=True)

def get_atom_coordinates_stem(motifs_ids, atom, ref):
    df = pd.DataFrame(index = range(len(motifs_ids)), columns=['N1', 'N2', 'N3', 'N4', 'N5', 'N6'])
    ids = []
    sequences_stem = []
    for i, motif in enumerate(motifs_ids):
        motif_cords = []
        file_name = motif[0].lower() + '.cif'
        ref_seq = ref[ref['ID'] == motif[0]]['seq_1'] + ref[ref['ID'] == motif[0]]['seq_2']
        ref_seq = ref_seq.reset_index(drop=True)
        if file_name == '7lm1.cif': continue
        structure = parser.get_structure(file_name.rstrip('.cif'), f"./mmCIF_files/{file_name}")
        model = structure[0]
        chain = model[motif[1]]
        if motif[2][0] in chain:
            res = chain[motif[2][0]]
            if ref_seq[0][0] != res.resname:
                motif[2] = [x+1 for x in motif[2]]
        for j, motif_nuc in enumerate(motif[2]):
            if motif_nuc in chain:
                res = chain[motif_nuc]
                if ref_seq[0][j] != res.resname:
                    break
                    # res = chain[motif_nuc+1]
                    # if res.resname != ref_seq[0][j]:
                    #     print('NOOOOOOOOOOOOO')
                    #     print(motif[0])
                    #     break
                if atom not in res:
                    break
                else: 
                    at = res[atom]
                    motif_cords.append(at.get_coord())
            else:
                break
        if len(motif_cords) == 6:
            df.iloc[i] = motif_cords
            ids.append(motif[0])
            sequences_stem.append(ref_seq[0])
    df = df.dropna()
    df['id'] = ids
    return df, sequences_stem

In [29]:
def get_atom_coordinates_stem_v2(motifs_ids, atom, ref):
    df = pd.DataFrame(index = range(len(motifs_ids)), columns=['N1', 'N2', 'N3', 'N4', 'N5', 'N6'])
    ids = []
    sequences_stem = []
    for i, motif in enumerate(motifs_ids):
        motif_cords = []
        file_name = motif[0].lower() + '.cif'
        ref_seq = ref[ref['ID'] == motif[0]]['seq_1'] + ref[ref['ID'] == motif[0]]['seq_2']
        ref_seq = ref_seq.reset_index(drop=True)
        if file_name == '7lm1.cif': continue
        structure = parser.get_structure(file_name.rstrip('.cif'), f"./mmCIF_files/{file_name}")
        model = structure[0]
        chain = model[motif[1]]
        if motif[2][0] in chain:
            res = chain[motif[2][0]]
            if ref_seq[0][0] != res.resname:
                motif[2] = [x+1 for x in motif[2]]
        for j, motif_nuc in enumerate(motif[2]):
            if motif_nuc in chain:
                res = chain[motif_nuc]
                if ref_seq[0][j] != res.resname:
                    break
                if atom not in res:
                    break
                else: 
                    if j == 0:
                        origin, matrix = compute_new_coords(res)
                    at = res[atom]
                    motif_cords.append(transform(at, origin, matrix))
            else:
                break
        if len(motif_cords) == 6:
            df.iloc[i] = motif_cords
            ids.append(motif[0])
            sequences_stem.append(ref_seq[0])
    df = df.dropna()
    df['id'] = ids
    return df

In [30]:
stems_databse, stem_sequences = get_atom_coordinates_stem(stems_complete, "C1'", stems)

In [31]:
stems_databse_v2 = get_atom_coordinates_stem_v2(stems_complete, "C1'", stems)

In [32]:
print(stems_databse.shape)
stems_databse

(47, 7)

,N1,N2,N3,N4,N5,N6,id
0,"[-1.264, -1.463, -36.074]","[-5.8, -0.782, -33.07]","[-8.891, 0.907, -28.61]","[-1.927, 2.48, -20.98]","[-4.557, -1.499, -23.225]","[-6.474, -5.092, -27.273]",1BVJ
1,"[10.986, 5.556, 1.539]","[8.969, 9.517, 3.807]","[9.566, 12.476, 7.74]","[15.764, 11.128, 15.789]","[11.029, 8.959, 14.347]","[7.509, 5.6, 11.425]",1CQL
2,"[-0.509, 3.1, 94.424]","[0.039, 7.051, 91.473]","[-1.542, 11.624, 88.641]","[-12.129, 12.283, 89.413]","[-8.535, 9.594, 85.978]","[-4.571, 6.775, 85.578]",1F84
3,"[13.042, 16.077, 6.456]","[11.758, 19.228, 10.938]","[13.422, 22.227, 15.064]","[23.061, 20.293, 19.62]","[18.312, 17.733, 19.634]","[14.166, 15.26, 17.164]",1HS4
4,"[-15.236, 43.52, 19.317]","[-18.976, 44.11, 14.687]","[-21.254, 41.645, 10.195]","[-15.439, 35.036, 4.52]","[-15.952, 40.878, 5.642]","[-14.767, 44.675, 8.977]",1KUQ
5,"[-6.067, 48.483, 163.995]","[-10.893, 45.857, 164.354]","[-16.028, 45.371, 164.583]","[-21.494, 51.477, 170.534]","[-18.222, 47.648, 171.58]","[-13.094, 45.283, 171.12]",1KXK
6,"[2.362, 3.363, -6.91]","[3.044, 7.358, -10.834]","[1.262, 11.63, -11.511]","[-7.196, 15.553, -7.583]","[-6.729, 11.001, -10.808]","[-5.515, 6.344, -13.74]",1LC6
7,"[106.917, 17.583, 22.625]","[110.563, 20.351, 24.406]","[114.704, 21.665, 28.157]","[115.538, 15.465, 36.712]","[112.386, 20.449, 35.06]","[107.915, 22.181, 32.14]",1M5K
8,"[4.982, 50.152, 2.513]","[3.55, 47.386, 7.49]","[-0.434, 44.58, 10.743]","[-9.486, 50.021, 10.665]","[-4.717, 51.462, 12.577]","[0.282, 52.911, 11.272]",1MZP
9,"[-6.084, 25.218, -11.38]","[-10.403, 25.828, -14.298]","[-12.491, 24.489, -18.976]","[-6.774, 16.46, -23.112]","[-6.322, 22.45, -23.108]","[-3.9, 26.362, -21.334]",1P5P
10,"[-13.581, -10.303, 5.656]","[-12.585, -14.058, 10.274]","[-8.628, -16.941, 13.334]","[-0.805, -21.354, 8.092]","[-5.843, -22.219, 8.449]","[-11.368, -20.53, 7.07]",2OIU
11,"[-10.078, 11.695, 24.78]","[-9.974, 11.259, 19.071]","[-10.636, 9.261, 14.123]","[-9.72, -1.128, 13.66]","[-6.636, 3.173, 14.247]","[-3.558, 7.632, 16.617]",3AM1
12,"[21.486, 40.18, 12.677]","[16.281, 41.477, 12.115]","[12.726, 45.337, 10.594]","[14.796, 55.437, 10.791]","[14.227, 51.477, 14.715]","[15.98, 47.277, 17.893]",3D0U
13,"[10.924, -29.818, 38.945]","[13.46, -33.628, 36.769]","[15.107, -39.271, 37.169]","[7.93, -45.902, 42.014]","[12.253, -42.127, 43.351]","[14.047, -37.983, 45.245]",3G9C
14,"[12.922, 107.947, 322.676]","[13.587, 113.251, 323.272]","[14.927, 118.223, 325.616]","[17.091, 118.314, 335.905]","[12.672, 118.444, 332.522]","[9.49, 115.689, 328.48]",3IGI
15,"[-0.493, 11.989, 35.977]","[-5.34, 9.524, 35.824]","[-8.269, 4.821, 36.74]","[-3.118, -3.782, 33.357]","[-5.924, 0.382, 30.924]","[-5.976, 5.543, 29.491]",3IWN
16,"[180.078, 251.808, 212.075]","[183.094, 249.321, 217.17]","[182.169, 248.018, 222.496]","[178.127, 256.956, 228.275]","[183.058, 255.955, 226.068]","[186.142, 254.839, 221.598]",3JBV
17,"[4.455, -10.027, 5.621]","[6.681, -11.938, 0.449]","[10.823, -14.715, -1.818]","[20.349, -14.009, 2.163]","[17.055, -10.589, -0.894]","[12.425, -7.602, -0.639]",3RW6
18,"[9.558, 29.32, 56.671]","[13.711, 31.334, 59.889]","[17.149, 30.291, 63.764]","[12.374, 23.509, 70.739]","[12.404, 28.78, 70.107]","[9.97, 32.924, 66.678]",3SUX
19,"[26.217, -6.147, -33.161]","[24.794, -0.477, -36.573]","[27.296, 3.539, -38.554]","[35.073, 7.532, -32.558]","[29.549, 7.647, -32.367]","[24.998, 4.78, -31.345]",3V7E
20,"[13.524, -13.205, 12.483]","[7.932, -14.806, 12.501]","[2.722, -12.536, 12.235]","[0.46, -3.064, 16.424]","[1.725, -8.511, 18.448]","[5.3, -12.651, 19.45]",4AOB
21,"[50.13, -10.097, -4.515]","[46.468, -7.096, -1.053]","[42.812, -3.169, -0.961]","[43.386, 6.101, -6.081]","[46.013, 3.364, -1.775]","[49.387, -0.553, -0.077]",4BW0
22,"[-15.523, 1.889, 15.265]","[-13.074, 6.481, 16.864]","[-11.289, 11.186, 15.181]","[-7.007, 10.189, 5.212]","[-5.232, 9.465, 10.319]","[-5.377, 5.49, 14.754]",4LVW
23,"[-36.576, 16.48, -19.194]","[-40.5, 18.849, -16.312]","[-45.019, 21.787, -14.981]","[-47.061, 28.316, -23.41]","[-44.515, 28.386, -18.918]","[-40.033, 25.948, -16.575]",4OQU
24,"[-65.282, 7.358, -33.268]","[-61.971, 6.459, -29.398]","[-58.367, 9.138, -25.74]","[-51.798, 17.153, -28.649]","[-52.117, 10.867, -30.049]","[-54.714, 7.113, -32.205]",4V5O
25,"[-55.678, 78.968, -23.405]","[-52.933, 81.653, -21.077]","[-49.781, 84.002, -16.785]","[-45.376, 78.865, -9.068]","[-49.946, 82.71, -11.78]","[-54.905, 82.271, -14.051]",4V8M
26,"[-76.095, 141.242, 92.259]","[-76.626, 139.884, 87.176]","[-74.311, 138.795, 83.114]","[-65.273, 141.951, 81.315]","[-68.965, 145.907, 81.99]","[-73.477, 148.608, 85.745]",4WSM
27,"[-14.669, -2.435, 7.676]","[-15.511, 2.776, 7.899]","[-15.301, 7.235, 5.525]","[-8.16, 7.436, -1.466]","[-7.857, 8.104, 3.875]","[-7.566, 5.619, 8.535]",5B2P
28,"[6.352, -31.56, -35.505]","[2.869, -34.424, -31.633]","[3.443, -37.136, -27.675]","[12.241, -43.178, -26.397]","[7.329, -43.672, -29.451]","[4.496, -41.963, -33.685]",5FJ4
29,"[-13.531, 13.036, 11.196]","[-8.03, 14.79, 11.991]","[-3.071, 12.929, 12.434]","[-0.852, 3.793, 17.254]","[-2.612, 9.097, 18.882]","[-6.494, 12.917, 18.965]",5FJC
30,"[-38.979, -59.115, 51.548]","[-34.733, -58.894, 48.554]","[-29.442, -57.926, 46.095]","[-21.999, -57.64, 53.62]","[-25.466, -54.344, 50.829]","[-30.61, -52.684, 49.829]",5J7L
31,"[266.282, 89.975, 208.617]","[261.234, 92.065, 209.85]","[255.446, 92.095, 211.522]","[250.519, 86.279, 203.989]","[252.803, 90.767, 203.621]","[257.556, 94.252, 204.192]",5TBW
32,"[14.022, 37.509, 202.848]","[9.334, 36.206, 200.766]","[5.363, 32.176, 200.113]","[9.016, 22.213, 200.566]","[7.964, 26.694, 196.282]","[10.693, 31.563, 194.799]",5U3G
33,"[40.956, -3.656, 10.909]","[41.315, -1.781, 15.973]","[40.412, 0.817, 21.319]","[30.188, 3.923, 22.124]","[35.149, 5.539, 20.314]","[39.661, 5.369, 16.479]",5XTM
34,"[229.753, 68.353, 63.482]","[232.11, 64.031, 61.589]","[235.539, 59.778, 61.113]","[245.068, 60.928, 65.407]","[242.859, 63.05, 61.288]","[238.704, 65.742, 58.438]",5Y7M
35,"[48.308, 32.456, -24.132]","[50.465, 36.545, -20.864]","[48.517, 41.795, -19.03]","[40.8, 47.113, -22.697]","[46.256, 46.497, -23.981]","[50.339, 43.351, -26.514]",6DU5
36,"[-39.012, 1.268, 3.468]","[-35.416, 5.195, 3.663]","[-30.183, 8.105, 5.326]","[-25.603, 4.166, 14.08]","[-29.952, 6.856, 12.859]","[-34.905, 8.116, 10.864]",6DVK
37,"[47.045, 19.557, 32.905]","[50.857, 22.309, 36.335]","[52.524, 24.577, 40.775]","[46.799, 28.69, 48.777]","[47.897, 29.917, 42.887]","[47.746, 29.121, 37.613]",6JDV
38,"[6.192, -16.831, 11.011]","[4.996, -21.817, 9.247]","[2.632, -25.3, 5.26]","[-4.223, -21.558, -1.674]","[-4.046, -23.072, 3.807]","[-2.719, -22.405, 9.343]",6N2V
39,"[-59.701, 103.197, 142.145]","[-61.055, 100.923, 136.762]","[-62.54, 96.917, 133.233]","[-61.067, 86.459, 138.484]","[-57.302, 91.176, 135.413]","[-54.518, 96.653, 134.586]",6ORD
40,"[144.944, 135.842, 160.85]","[141.722, 136.743, 165.871]","[140.727, 139.441, 171.215]","[150.305, 138.811, 176.697]","[146.788, 134.948, 175.229]","[144.34, 132.162, 170.982]",6UZ7
41,"[243.023, 252.877, 222.431]","[238.68, 252.046, 225.912]","[235.656, 253.336, 230.131]","[240.538, 259.138, 237.576]","[240.397, 253.971, 236.161]","[241.608, 250.04, 232.691]",6Z6M
42,"[239.225, 218.386, 245.76]","[236.106, 222.441, 248.415]","[231.013, 224.758, 249.926]","[223.341, 223.994, 242.503]","[227.774, 226.551, 242.693]","[233.418, 227.058, 243.375]",6ZYM
43,"[6.163, 575.387, 120.335]","[5.693, 574.387, 125.39]","[4.855, 574.705, 131.077]","[-2.435, 581.79, 134.019]","[3.253, 581.292, 133.167]","[7.373, 580.683, 129.565]",7A0S
44,"[203.964, 269.272, 208.19]","[206.317, 271.224, 203.988]","[208.696, 270.502, 198.812]","[210.637, 260.322, 196.96]","[213.336, 264.2, 199.926]","[213.658, 267.609, 203.929]",7AC7
45,"[-4.834, 0.946, -0.653]","[-4.271, 4.282, -4.17]","[-1.641, 7.222, -8.69]","[8.277, 4.596, -7.34]","[5.957, 6.514, -3.148]","[3.019, 7.434, 0.64]",7FJ0
46,"[280.883, 252.161, 278.416]","[279.566, 257.598, 278.714]","[275.696, 261.207, 280.7]","[265.642, 258.946, 280.482]","[269.278, 259.908, 276.856]","[273.786, 258.438, 274.348]",7O80

In [33]:
stems_databse_v2

,N1,N2,N3,N4,N5,N6,id
0,[[[[[0. 0. 0.]]]]],[[[[[ 0.1967634 1.7065583 -5.206921 ]]]]],[[[[[ -1.8509951 2.9861887 -10.35161 ]]]]],[[[[[-11.074493 -1.899972 -10.842573]]]]],[[[[[ -5.951877 -2.9711628 -11.475597 ]]]]],[[[[[ -0.35487747 -3.4461186 -10.284439 ]]]]],1BVJ
1,[[[[[0. 0. 0.]]]]],[[[[[-0.32010102 3.842625 -3.1675544 ]]]]],[[[[[-3.546488 7.150039 -4.965335]]]]],[[[[[-13.7470665 7.2168217 -3.984296 ]]]]],[[[[[-10.3328285 4.368113 -7.05545 ]]]]],[[[[[-6.4717097 0.37884438 -8.23395 ]]]]],1CQL
2,[[[[[0. 0. 0.]]]]],[[[[[-2.3096297 4.1723547 1.3697441]]]]],[[[[[-3.937821 8.253744 4.8516083]]]]],[[[[[-0.77549934 5.4845014 14.621248 ]]]]],[[[[[-5.306065 4.3803306 11.427254 ]]]]],[[[[[-7.0191984 2.995915 7.0719557]]]]],1F84
3,[[[[[0. 0. 0.]]]]],[[[[[-4.4216266 2.983667 -1.7924101]]]]],[[[[[-8.965636 5.592419 -0.6377877]]]]],[[[[[-14.892649 2.6081092 7.9279747]]]]],[[[[[-13.947266 0.4536518 3.0729392]]]]],[[[[[-10.662772 -1.5214107 -0.76335967]]]]],1HS4
4,[[[[[0. 0. 0.]]]]],[[[[[ 2.6273482 -5.002062 1.9618884]]]]],[[[[[ 7.458419 -7.4975963 3.3317964]]]]],[[[[[16.086285 -5.246367 -2.1628017]]]]],[[[[[10.93544 -8.211173 -2.737012]]]]],[[[[[ 5.865732 -7.746144 -3.7496688]]]]],1KUQ
5,[[[[[0. 0. 0.]]]]],[[[[[ 4.751488 1.934773 -1.9987661]]]]],[[[[[ 7.9888496 3.830345 -5.546042 ]]]]],[[[[[ 8.3527775 -0.20271301 -14.829191 ]]]]],[[[[[ 9.869243 -1.9515891 -10.235377 ]]]]],[[[[[ 8.735752 -3.2614372 -4.84087 ]]]]],1KXK
6,[[[[[0. 0. 0.]]]]],[[[[[-0.889753 5.515664 0.7802017]]]]],[[[[[1.8696816 9.195768 1.6323743]]]]],[[[[[11.304867 9.202397 5.2839684]]]]],[[[[[6.7027383 7.1679993 7.737753 ]]]]],[[[[[1.7943826 4.9962287 9.455173 ]]]]],1LC6
7,[[[[[0. 0. 0.]]]]],[[[[[2.2725105 4.1304665 1.3791546]]]]],[[[[[2.6143777 9.78297 2.3155327]]]]],[[[[[-5.701447 15.629414 -0.6827655]]]]],[[[[[-0.5558474 13.492459 -3.2245555]]]]],[[[[[ 1.7824018 8.914191 -5.480243 ]]]]],1M5K
8,[[[[[0. 0. 0.]]]]],[[[[[5.834018 0.6311016 0.19453967]]]]],[[[[[10.921588 1.4518738 -2.593088 ]]]]],[[[[[ 11.480655 -5.088221 -10.867377]]]]],[[[[[11.211769 -6.2632904 -5.669058 ]]]]],[[[[[ 8.045762 -6.3166556 -1.3370647]]]]],1MZP
9,[[[[[0. 0. 0.]]]]],[[[[[-1.7240174 -4.034096 2.880003 ]]]]],[[[[[-0.5753989 -9.049628 4.12958 ]]]]],[[[[[ 9.5144205 -11.079214 1.2431006]]]]],[[[[[ 4.185732 -11.198722 -1.5273209]]]]],[[[[[ 1.2295582 -8.982023 -4.792926 ]]]]],1P5P
10,[[[[[0. 0. 0.]]]]],[[[[[-5.8511972 -1.4296172 -0.37100172]]]]],[[[[[-9.7844410e+00 -5.6401772e+00 -5.0680637e...,[[[[[ -7.2948885 -14.882976 -4.0701976]]]]],[[[[[ -8.284809 -10.243769 -6.007965]]]]],[[[[[-6.479307 -4.658196 -6.9143386]]]]],2OIU
11,[[[[[0. 0. 0.]]]]],[[[[[-0.41419554 -5.5971513 1.1375182 ]]]]],[[[[[ 0.14729309 -10.318571 3.6486664 ]]]]],[[[[[ 9.133512 -11.217822 8.885456]]]]],[[[[[ 7.3722105 -11.232286 3.8603354]]]]],[[[[[ 5.7368393 -9.504074 -1.5537671]]]]],3AM1
12,[[[[[0. 0. 0.]]]]],[[[[[ 2.8906732 -2.3430426 -3.9043872]]]]],[[[[[ 3.577113 -2.9127884 -9.294681 ]]]]],[[[[[ -3.9809926 -1.6762279 -16.199726 ]]]]],[[[[[ -2.9747317 -5.375888 -12.112784 ]]]]],[[[[[-3.0150316 -7.1873994 -6.865929 ]]]]],3D0U
13,[[[[[0. 0. 0.]]]]],[[[[[-1.0177526 -0.77139425 4.9042306 ]]]]],[[[[[ 0.1816498 0.79161847 10.457113 ]]]]],[[[[[ 2.668673 11.309867 11.918177]]]]],[[[[[ 5.1873293 6.218478 10.3495245]]]]],[[[[[7.368486 3.177209 7.1917396]]]]],3G9C
14,[[[[[0. 0. 0.]]]]],[[[[[ 3.165636 3.8612425 -1.9998574]]]]],[[[[[ 4.8702636 8.291855 -5.077943 ]]]]],[[[[[ -1.418283 11.496978 -12.871281]]]]],[[[[[ 2.5070777 7.665435 -11.922629 ]]]]],[[[[[ 4.132371 2.9259703 -8.931185 ]]]]],3IGI
15,[[[[[0. 0. 0.]]]]],[[[[[5.211737 0.5647933 1.4532194]]]]],[[[[[10.19264 2.9032485 0.33137196]]]]],[[[[[12.483374 2.5947483 -9.995606 ]]]]],[[[[[12.433501 -1.1108677 -5.824522 ]]]]],[[[[[ 9.492959 -4.1429214 -2.5302887]]]]],3IWN
16,[[[[[0. 0. 0.]]]]],[[[[[ 5.64756 -2.050249 -2.267588]]]]],[[[[[ 7.744651 -5.4835095 -6.106161 ]]]]],[[[[[ 3.4988346 -15.988104 -4.988677 ]]]]],[[[[[ 6.9122686 -13.067972 -1.8249931]]]]],[[[[[ 7.8858275 -8.541665 1.224926 ]]]]],3JBV
17,[[[[[0. 0. 0.]]]]],[[[[[5.357592 1.4041067 2.1636248]]]]],[[[[[9.642008 4.754921 1.5132375]]]]],[[[[[12.576648 7.657501 -7.9764614]]]]],[[[[[12.977156 2.889844 -4.9762745]]]]],[[[[[ 9.95282 -1.2005702 -2.8441405]]]]],3RW6
18,[[[[[0. 0. 0.]]]]],[[[[[2.8725939 4.424496 1.9573361]]]]],[[[[[2.7649522 9.603746 2.9999783]]]]],[[[[[-3.3385444 14.412357 -4.5545793]]]]],[[[[[ 1.7558825 12.946372 -4.2691655]]]]],[[[[[ 5.080284 8.086608 -4.7006493]]]]],3SUX
19,[[[[[0. 0. 0.]]]]],[[[[[ 5.042404 1.6691431 -4.1956773]]]]],[[[[[ 6.6085963 5.750516 -6.879341 ]]]]],[[[[[ -1.025644 11.269594 -11.741029]]]]],[[[[[ 1.4207354 6.389624 -12.615915 ]]]]],[[[[[ 1.9236383 1.2117298 -10.909375 ]]]]],3V7E
20,[[[[[0. 0. 0.]]]]],[[[[[ 5.4380274 0.98658377 -1.8134222 ]]]]],[[[[[ 8.2698345 2.745786 -6.4236097]]]]],[[[[[ 4.9220934 0.64448667 -16.260292 ]]]]],[[[[[ 7.2926326 -2.4086504 -11.740834 ]]]]],[[[[[ 6.9424243 -4.7947474 -6.730033 ]]]]],4AOB
21,[[[[[0. 0. 0.]]]]],[[[[[-2.4841938 -5.286948 0.5278902]]]]],[[[[[-6.152465 -8.594413 -1.569866]]]]],[[[[[-15.8106365 -5.913968 -5.035661 ]]]]],[[[[[-12.918721 -6.2253213 -0.08855915]]]]],[[[[[-9.103164 -4.237017 3.242828]]]]],4BW0
22,[[[[[0. 0. 0.]]]]],[[[[[1.1200262 4.724269 2.4632683]]]]],[[[[[1.702566 9.936196 1.655682]]]]],[[[[[ 6.496395 11.694632 -7.969162]]]]],[[[[[ 8.189859 10.595791 -2.901521]]]]],[[[[[8.892008 6.0300574 0.86038566]]]]],4LVW
23,[[[[[0. 0. 0.]]]]],[[[[[-0.75008184 -5.351556 -0.33778548]]]]],[[[[[ -2.3036823 -10.347425 -2.1958447]]]]],[[[[[-10.167366 -8.63362 -9.48083 ]]]]],[[[[[-9.633639 -9.609951 -4.4383097]]]]],[[[[[-7.639565 -7.07568 0.15766001]]]]],4OQU
24,[[[[[0. 0. 0.]]]]],[[[[[ 2.2802734 -4.6312227 0.31613493]]]]],[[[[[ 5.3342776 -7.9956584 3.9078562]]]]],[[[[[13.314065 -4.350621 10.144121]]]]],[[[[[12.519107 -4.998847 3.778321]]]]],[[[[[ 9.990275 -3.5968657 -0.35988277]]]]],4V5O
25,[[[[[0. 0. 0.]]]]],[[[[[1.431591 3.8438919 1.8272607]]]]],[[[[[2.0478091 9.479543 3.1440303]]]]],[[[[[-5.4430423 16.49609 3.1533713]]]]],[[[[[-0.16146755 13.471128 0.7082844 ]]]]],[[[[[ 1.0504364 9.480092 -2.8335724]]]]],4V8M
26,[[[[[0. 0. 0.]]]]],[[[[[ 5.0540977 -1.5489314 -0.1411581]]]]],[[[[[ 9.611797 -0.12369239 -0.6321895 ]]]]],[[[[[11.988392 8.027794 -5.405779]]]]],[[[[[ 9.406759 4.297564 -8.43181 ]]]]],[[[[[ 4.2070503 0.54936945 -9.248945 ]]]]],4WSM
27,[[[[[0. 0. 0.]]]]],[[[[[-3.3686728 2.7372403 -3.012103 ]]]]],[[[[[-4.000746 5.9606647 -6.855627 ]]]]],[[[[[ 3.8919418 11.976263 -8.049955 ]]]]],[[[[[-0.25214267 12.270568 -4.6142216 ]]]]],[[[[[-2.1708808e+00 1.0551997e+01 5.3523779e...,5B2P
28,[[[[[0. 0. 0.]]]]],[[[[[-2.1306062 4.0169353 -3.827654 ]]]]],[[[[[-5.8943934 4.4081297 -6.8328276]]]]],[[[[[-10.1848545 -4.319435 -11.411626 ]]]]],[[[[[ -5.4706903 -1.0728123 -12.378475 ]]]]],[[[[[ -0.5494945 0.28887916 -10.704868 ]]]]],5FJ4
29,[[[[[0. 0. 0.]]]]],[[[[[4.818912 1.9467857 2.6377363]]]]],[[[[[6.7111516 3.307159 7.414771 ]]]]],[[[[[ 0.7756019 8.134843 14.700757 ]]]]],[[[[[3.1789563 9.570604 9.597534 ]]]]],[[[[[3.3412244 9.0134 4.181594 ]]]]],5FJC
30,[[[[[0. 0. 0.]]]]],[[[[[4.776338 1.9616233 0.61644685]]]]],[[[[[10.160157 4.344148 0.05387831]]]]],[[[[[10.044885 11.681047 -7.5790915]]]]],[[[[[10.978555 6.281581 -6.7744875]]]]],[[[[[ 9.012582 1.2818224 -5.6109924]]]]],5J7L
31,[[[[[0. 0. 0.]]]]],[[[[[ 2.9749668 -2.0806556 4.2651143]]]]],[[[[[ 7.784184 -4.132929 7.2579613]]]]],[[[[[ 10.799694 -12.80353 1.7285148]]]]],[[[[[ 6.6129084 -11.995525 4.4326143]]]]],[[[[[ 1.6887577 -8.925715 5.6121645]]]]],5TBW
32,[[[[[0. 0. 0.]]]]],[[[[[3.5990396 0.15041256 3.8773918 ]]]]],[[[[[8.814983 1.7832236 5.4786463]]]]],[[[[[15.881914 2.4788158 -2.41981 ]]]]],[[[[[13.808142 -1.760037 1.7359447]]]]],[[[[[ 9.0388 -4.9906454 2.1487842]]]]],5U3G
33,[[[[[0. 0. 0.]]]]],[[[[[ 5.29456 -0.77299154 0.8116105 ]]]]],[[[[[10.815596 -3.0100868 1.622973 ]]]]],[[[[[ 10.781284 -13.516553 -0.48378396]]]]],[[[[[ 9.882052 -9.829538 3.528246]]]]],[[[[[ 6.669177 -5.615204 6.176091]]]]],5XTM
34,[[[[[0. 0. 0.]]]]],[[[[[ 3.75846 3.6480446 -0.619908 ]]]]],[[[[[ 7.3140907 7.082652 -2.993424 ]]]]],[[[[[ 11.014076 4.235687 -12.415075]]]]],[[[[[11.823787 2.4005005 -7.6901236]]]]],[[[[[10.281471 0.4697207 -2.539715 ]]]]],5Y7M
35,[[[[[0. 0. 0.]]]]],[[[[[1.0339106 3.076047 4.6391096]]]]],[[[[[-0.03331184 2.3292806 10.385774 ]]]]],[[[[[-6.3432264 -4.2403307 14.664241 ]]]]],[[[[[-6.7831836 0.9186203 12.43092 ]]]]],[[[[[-7.190533 4.164591 7.710535]]]]],6DU5
36,[[[[[0. 0. 0.]]]]],[[[[[ 4.257542 3.203405 -0.04594226]]]]],[[[[[7.4267173 8.538922 0.28045034]]]]],[[[[[ 1.5094247 17.225471 -1.3487072]]]]],[[[[[ 3.2872458 13.16342 -4.173566 ]]]]],[[[[[ 3.9798777 8.078207 -6.112817 ]]]]],6DVK
37,[[[[[0. 0. 0.]]]]],[[[[[ 4.70984 3.3051915 -0.87342906]]]]],[[[[[ 9.033292 4.8933606 -3.407559 ]]]]],[[[[[ 15.109739 -0.47089028 -10.337637 ]]]]],[[[[[13.70751 -0.7254822 -4.3901877]]]]],[[[[[10.582557 -1.4560467 -0.12726998]]]]],6JDV
38,[[[[[0. 0. 0.]]]]],[[[[[-2.000516 4.523746 2.2217038]]]]],[[[[[-3.4870775 10.109223 1.7650614]]]]],[[[[[ 0.21376944 15.973177 -6.0446587 ]]]]],[[[[[ 1.9778144 13.804522 -1.0898662]]]]],[[[[[3.796775 9.645491 2.4097004]]]]],6N2V
39,[[[[[0. 0. 0.]]]]],[[[[[ 1.3185505 -2.740158 5.1705093]]]]],[[[[[ 4.150125 -3.4936428 9.873857 ]]]]],[[[[[14.217835 2.6234424 9.295175 ]]]]],[[[[[11.681579 -3.2148137 6.984642 ]]]]],[[[[[ 8.059458 -6.973029 3.6397762]]]]],6ORD
40,[[[[[0. 0. 0.]]]]],[[[[[-4.199411 0.89151525 -4.2395325 ]]]]],[[[[[-9.810557 2.348783 -6.03366 ]]]]],[[[[[-16.612833 -3.5422435 0.38599968]]]]],[[[[[-13.145783 -5.0965323 -3.488389 ]]]]],[[[[[-7.765721 -5.467945 -5.1341515]]]]],6UZ7
41,[[[[[0. 0. 0.]]]]],[[[[[-0.08833694 -0.9437742 -5.5471697 ]]]]],[[[[[ -2.6134756 -1.839925 -10.176325 ]]]]],[[[[[-12.30539 -6.1041117 -9.277055 ]]]]],[[[[[-7.253159 -7.877394 -9.052282]]]]],[[[[[-2.497504 -8.137401 -6.5470214]]]]],6Z6M
42,[[[[[0. 0. 0.]]]]],[[[[[ 0.11694169 -0.34807718 5.7519855 ]]]]],[[[[[ 1.0063362 -3.3218095 10.646492 ]]]]],[[[[[ -1.9866483 -13.590818 10.281152 ]]]]],[[[[[-4.5907054 -9.185476 10.087198 ]]]]],[[[[[-5.8287015 -4.004384 8.037675 ]]]]],6ZYM
43,[[[[[0. 0. 0.]]]]],[[[[[ 4.558356 -2.1796312 -1.115586 ]]]]],[[[[[ 8.951703 -5.818523 -1.8916441]]]]],[[[[[ 6.057333 -15.632083 -4.5958624]]]]],[[[[[ 7.299415 -12.438378 0.05007118]]]]],[[[[[ 5.794868 -8.338811 3.4041162]]]]],7A0S
44,[[[[[0. 0. 0.]]]]],[[[[[ 0.9959622 -3.764049 -3.44146 ]]]]],[[[[[ 2.8397202 -9.06741 -4.6443243]]]]],[[[[[ 7.9995747 -13.196358 3.5506668]]]]],[[[[[ 9.496795 -9.565311 -0.4109733]]]]],[[[[[ 9.07591 -4.9269037 -2.8720772]]]]],7AC7
45,[[[[[0. 0. 0.]]]]],[[[[[ 2.8460255 -1.3132155 -3.7404227]]]]],[[[[[ 7.705209 -1.4724793 -7.25523 ]]]]],[[[[[12.350889 7.4211664 -4.72426 ]]]]],[[[[[ 7.39198 7.879582 -6.07817 ]]]]],[[[[[ 2.5376158 7.55502 -6.4743958]]]]],7FJ0
46,[[[[[0. 0. 0.]]]]],[[[[[0.28716153 1.7968769 5.2983923 ]]]]],[[[[[ 3.2877355 1.343152 10.066703 ]]]]],[[[[[ 7.2323093 -7.689353 13.082829 ]]]]],[[[[[ 2.4004233 -5.769239 12.572946 ]]]]],[[[[[-1.5249946 -3.9537125 9.399944 ]]]]],7O80

In [34]:
structure = parser.get_structure('1CQL', f"./mmCIF_files/1CQL.cif")
model = structure[0]
print(model)

<Model id=0>

In [35]:
stems[stems['ID'] == '1CQL']

     ID  start_1  end_1 seq_1 braq_1  start_2  end_2 seq_2 braq_2 chain
5  1CQL       12     14   GGU    (((       33     35   GCC    )))     A

In [36]:
chain = model['A']
res = chain[14]
print(res)
at = res["C1'"]
at.get_coord()
#res.resname == 'G'

<Residue U het=  resseq=14 icode= >

array([ 9.566, 12.476,  7.74 ], dtype=float32)

In [37]:
stems_database = stems_databse.drop('id', axis=1)

for column in stems_database.columns:
    stems_database[column] = stems_database[column].apply(lambda x: ','.join(map(str, x)))
    
stems_database['class'] = 0
stems_database

,N1,N2,N3,N4,N5,N6,class
0,"-1.264,-1.463,-36.074","-5.8,-0.782,-33.07","-8.891,0.907,-28.61","-1.927,2.48,-20.98","-4.557,-1.499,-23.225","-6.474,-5.092,-27.273",0
1,"10.986,5.556,1.539","8.969,9.517,3.807","9.566,12.476,7.74","15.764,11.128,15.789","11.029,8.959,14.347","7.509,5.6,11.425",0
2,"-0.509,3.1,94.424","0.039,7.051,91.473","-1.542,11.624,88.641","-12.129,12.283,89.413","-8.535,9.594,85.978","-4.571,6.775,85.578",0
3,"13.042,16.077,6.456","11.758,19.228,10.938","13.422,22.227,15.064","23.061,20.293,19.62","18.312,17.733,19.634","14.166,15.26,17.164",0
4,"-15.236,43.52,19.317","-18.976,44.11,14.687","-21.254,41.645,10.195","-15.439,35.036,4.52","-15.952,40.878,5.642","-14.767,44.675,8.977",0
5,"-6.067,48.483,163.995","-10.893,45.857,164.354","-16.028,45.371,164.583","-21.494,51.477,170.534","-18.222,47.648,171.58","-13.094,45.283,171.12",0
6,"2.362,3.363,-6.91","3.044,7.358,-10.834","1.262,11.63,-11.511","-7.196,15.553,-7.583","-6.729,11.001,-10.808","-5.515,6.344,-13.74",0
7,"106.917,17.583,22.625","110.563,20.351,24.406","114.704,21.665,28.157","115.538,15.465,36.712","112.386,20.449,35.06","107.915,22.181,32.14",0
8,"4.982,50.152,2.513","3.55,47.386,7.49","-0.434,44.58,10.743","-9.486,50.021,10.665","-4.717,51.462,12.577","0.282,52.911,11.272",0
9,"-6.084,25.218,-11.38","-10.403,25.828,-14.298","-12.491,24.489,-18.976","-6.774,16.46,-23.112","-6.322,22.45,-23.108","-3.9,26.362,-21.334",0
10,"-13.581,-10.303,5.656","-12.585,-14.058,10.274","-8.628,-16.941,13.334","-0.805,-21.354,8.092","-5.843,-22.219,8.449","-11.368,-20.53,7.07",0
11,"-10.078,11.695,24.78","-9.974,11.259,19.071","-10.636,9.261,14.123","-9.72,-1.128,13.66","-6.636,3.173,14.247","-3.558,7.632,16.617",0
12,"21.486,40.18,12.677","16.281,41.477,12.115","12.726,45.337,10.594","14.796,55.437,10.791","14.227,51.477,14.715","15.98,47.277,17.893",0
13,"10.924,-29.818,38.945","13.46,-33.628,36.769","15.107,-39.271,37.169","7.93,-45.902,42.014","12.253,-42.127,43.351","14.047,-37.983,45.245",0
14,"12.922,107.947,322.676","13.587,113.251,323.272","14.927,118.223,325.616","17.091,118.314,335.905","12.672,118.444,332.522","9.49,115.689,328.48",0
15,"-0.493,11.989,35.977","-5.34,9.524,35.824","-8.269,4.821,36.74","-3.118,-3.782,33.357","-5.924,0.382,30.924","-5.976,5.543,29.491",0
16,"180.078,251.808,212.075","183.094,249.321,217.17","182.169,248.018,222.496","178.127,256.956,228.275","183.058,255.955,226.068","186.142,254.839,221.598",0
17,"4.455,-10.027,5.621","6.681,-11.938,0.449","10.823,-14.715,-1.818","20.349,-14.009,2.163","17.055,-10.589,-0.894","12.425,-7.602,-0.639",0
18,"9.558,29.32,56.671","13.711,31.334,59.889","17.149,30.291,63.764","12.374,23.509,70.739","12.404,28.78,70.107","9.97,32.924,66.678",0
19,"26.217,-6.147,-33.161","24.794,-0.477,-36.573","27.296,3.539,-38.554","35.073,7.532,-32.558","29.549,7.647,-32.367","24.998,4.78,-31.345",0
20,"13.524,-13.205,12.483","7.932,-14.806,12.501","2.722,-12.536,12.235","0.46,-3.064,16.424","1.725,-8.511,18.448","5.3,-12.651,19.45",0
21,"50.13,-10.097,-4.515","46.468,-7.096,-1.053","42.812,-3.169,-0.961","43.386,6.101,-6.081","46.013,3.364,-1.775","49.387,-0.553,-0.077",0
22,"-15.523,1.889,15.265","-13.074,6.481,16.864","-11.289,11.186,15.181","-7.007,10.189,5.212","-5.232,9.465,10.319","-5.377,5.49,14.754",0
23,"-36.576,16.48,-19.194","-40.5,18.849,-16.312","-45.019,21.787,-14.981","-47.061,28.316,-23.41","-44.515,28.386,-18.918","-40.033,25.948,-16.575",0
24,"-65.282,7.358,-33.268","-61.971,6.459,-29.398","-58.367,9.138,-25.74","-51.798,17.153,-28.649","-52.117,10.867,-30.049","-54.714,7.113,-32.205",0
25,"-55.678,78.968,-23.405","-52.933,81.653,-21.077","-49.781,84.002,-16.785","-45.376,78.865,-9.068","-49.946,82.71,-11.78","-54.905,82.271,-14.051",0
26,"-76.095,141.242,92.259","-76.626,139.884,87.176","-74.311,138.795,83.114","-65.273,141.951,81.315","-68.965,145.907,81.99","-73.477,148.608,85.745",0
27,"-14.669,-2.435,7.676","-15.511,2.776,7.899","-15.301,7.235,5.525","-8.16,7.436,-1.466","-7.857,8.104,3.875","-7.566,5.619,8.535",0
28,"6.352,-31.56,-35.505","2.869,-34.424,-31.633","3.443,-37.136,-27.675","12.241,-43.178,-26.397","7.329,-43.672,-29.451","4.496,-41.963,-33.685",0
29,"-13.531,13.036,11.196","-8.03,14.79,11.991","-3.071,12.929,12.434","-0.852,3.793,17.254","-2.612,9.097,18.882","-6.494,12.917,18.965",0
30,"-38.979,-59.115,51.548","-34.733,-58.894,48.554","-29.442,-57.926,46.095","-21.999,-57.64,53.62","-25.466,-54.344,50.829","-30.61,-52.684,49.829",0
31,"266.282,89.975,208.617","261.234,92.065,209.85","255.446,92.095,211.522","250.519,86.279,203.989","252.803,90.767,203.621","257.556,94.252,204.192",0
32,"14.022,37.509,202.848","9.334,36.206,200.766","5.363,32.176,200.113","9.016,22.213,200.566","7.964,26.694,196.282","10.693,31.563,194.799",0
33,"40.956,-3.656,10.909","41.315,-1.781,15.973","40.412,0.817,21.319","30.188,3.923,22.124","35.149,5.539,20.314","39.661,5.369,16.479",0
34,"229.753,68.353,63.482","232.11,64.031,61.589","235.539,59.778,61.113","245.068,60.928,65.407","242.859,63.05,61.288","238.704,65.742,58.438",0
35,"48.308,32.456,-24.132","50.465,36.545,-20.864","48.517,41.795,-19.03","40.8,47.113,-22.697","46.256,46.497,-23.981","50.339,43.351,-26.514",0
36,"-39.012,1.268,3.468","-35.416,5.195,3.663","-30.183,8.105,5.326","-25.603,4.166,14.08","-29.952,6.856,12.859","-34.905,8.116,10.864",0
37,"47.045,19.557,32.905","50.857,22.309,36.335","52.524,24.577,40.775","46.799,28.69,48.777","47.897,29.917,42.887","47.746,29.121,37.613",0
38,"6.192,-16.831,11.011","4.996,-21.817,9.247","2.632,-25.3,5.26","-4.223,-21.558,-1.674","-4.046,-23.072,3.807","-2.719,-22.405,9.343",0
39,"-59.701,103.197,142.145","-61.055,100.923,136.762","-62.54,96.917,133.233","-61.067,86.459,138.484","-57.302,91.176,135.413","-54.518,96.653,134.586",0
40,"144.944,135.842,160.85","141.722,136.743,165.871","140.727,139.441,171.215","150.305,138.811,176.697","146.788,134.948,175.229","144.34,132.162,170.982",0
41,"243.023,252.877,222.431","238.68,252.046,225.912","235.656,253.336,230.131","240.538,259.138,237.576","240.397,253.971,236.161","241.608,250.04,232.691",0
42,"239.225,218.386,245.76","236.106,222.441,248.415","231.013,224.758,249.926","223.341,223.994,242.503","227.774,226.551,242.693","233.418,227.058,243.375",0
43,"6.163,575.387,120.335","5.693,574.387,125.39","4.855,574.705,131.077","-2.435,581.79,134.019","3.253,581.292,133.167","7.373,580.683,129.565",0
44,"203.964,269.272,208.19","206.317,271.224,203.988","208.696,270.502,198.812","210.637,260.322,196.96","213.336,264.2,199.926","213.658,267.609,203.929",0
45,"-4.834,0.946,-0.653","-4.271,4.282,-4.17","-1.641,7.222,-8.69","8.277,4.596,-7.34","5.957,6.514,-3.148","3.019,7.434,0.64",0
46,"280.883,252.161,278.416","279.566,257.598,278.714","275.696,261.207,280.7","265.642,258.946,280.482","269.278,259.908,276.856","273.786,258.438,274.348",0

In [38]:
stems_database.to_csv("stems_database_C1'.csv")

In [39]:
stems_database_v22 = stems_databse_v2.drop('id', axis=1)

for column in stems_database_v22.columns:
    stems_database_v22[column] = stems_database_v22[column].apply(lambda x: ','.join(map(str,np.array(x).flatten())))
stems_database_v22['class'] = 0
stems_database_v22
stems_database_v22.to_csv("./modified_coord/stems_C1'.csv")

In [40]:
with open("stems_database_C1'_seqs.csv", 'w', newline='') as f:
     
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for item in stem_sequences:
        write.writerow([item])

<h4>Hairpins</h4>

In [41]:
hairpins = pd.read_csv('./rnasolo-3.218-dbn-csv/hairpins_u.txt', sep=' ', header=None, names=['ID', 'start', 'end', 'seq', 'braq'])
hairpins['chain'] = list(map(lambda x: x.split('_')[2].rsplit('-motifs.txt:Hairpin')[0], hairpins['ID']))
hairpins['ID'] = list(map(lambda x: x[:x.find('_')], hairpins['ID']))
hairpins = hairpins[~hairpins['chain'].str.contains('-')]
hairpins = hairpins[~hairpins['ID'].duplicated()]
haripins = hairpins.reset_index(drop=True)
hairpins

       ID  start  end     seq    braq chain
0    17RA      9   14  GAUUAC  (....)     A
1    1A1T      8   13  CGGAGG  (....)     B
3    1A9L     17   22  CGAGAG  (....)     A
4    1AFX      4    9  GUGAAC  (....)     A
5    1AJF      7   12  GGAAAC  (....)     A
..    ...    ...  ...     ...     ...   ...
785  7R81    223  228  CUUCGG  (....)    A2
787  7RQB    116  121  GGGAAC  (....)    1A
789  7RYG    122  127  GGGAAC  (....)     A
791  7SAM     22   27  UUACAA  (....)     A
792  7SC6     22   27  UUACAA  (....)     C

[624 rows x 6 columns]

In [42]:
hairpins_ids = hairpins['ID']
already_downloaded_ids = list(map(lambda x: x[0],motifs_ids))
same_elements = set(hairpins_ids).intersection(already_downloaded_ids)
different_elements = set(hairpins_ids).difference(already_downloaded_ids)
print(len(same_elements))
print(len(different_elements))
different_elements = list(different_elements)[:70]
hairpin_ids = list(same_elements) + list(different_elements)
print(len(hairpin_ids))


###first database
hairpin_ids = [
    '4V8M', '3DHS', '2N6T', '1FYP', '4XWF', '4ZNP', '2LI4', '2M5U', '4PCJ', '3E5C',
    '1N8X', '5TBW', '1K4B', '5IEM', '2PCV', '4PLX', '1JUR', '1U63', '2JSE', '2LU0',
    '1QWA', '1Q96', '2HW8', '4W90', '4UER', '3V7E', '3IGI', '2NCI', '2CZJ', '3G9C',
    '5Y7M', '1I6U', '4V5O', '1ZBN', '5UF3', '1Z2J', '3J7P', '5FJC', '4A4S', '3P22',
    '2N6X', '3CUL', '1ZIG', '4JF2', '1CQL', '5U3G', '1OOA', '2L2J', '1F9L'
]

103
521
173

In [43]:
pdbl = PDB.PDBList()   
pdbl.download_pdb_files(hairpin_ids, file_format='mmCif', pdir='./mmCIF_files/')

Structure exists: './mmCIF_files/4v8m.cif' Downloading PDB structure '3dhs'...

Downloading PDB structure '2n6t'...
Downloading PDB structure '1fyp'...
Downloading PDB structure '4xwf'...
Downloading PDB structure '4znp'...
Downloading PDB structure '2li4'...
Downloading PDB structure '2m5u'...
Structure exists: './mmCIF_files/4pcj.cif'
Structure exists: './mmCIF_files/3e5c.cif'
Downloading PDB structure '1n8x'...
Structure exists: './mmCIF_files/5tbw.cif'
Downloading PDB structure '5iem'...
Downloading PDB structure '1k4b'...
Downloading PDB structure '2pcv'...
Downloading PDB structure '1jur'...
Structure exists: './mmCIF_files/4plx.cif'
Downloading PDB structure '1u63'...
Downloading PDB structure '2jse'...
Downloading PDB structure '2lu0'...
Downloading PDB structure '1qwa'...
Structure exists: './mmCIF_files/1q96.cif'
Downloading PDB structure '2hw8'...
Structure exists: './mmCIF_files/4w90.cif'
Downloading PDB structure '4uer'...
Structure exists: './mmCIF_files/3v7e.cif'
Structure exists: './mmCIF_files/3igi.cif'
Downloading PDB structure '2nci'...
Downloading PDB structure '2czj'...
Structure exists: './mmCIF_files/3g9c.cif'
Structure exists: './mmCIF_files/5y7m.cif'
Downloading PDB structure '1i6u'...
Structure exists: './mmCIF_files/4v5o.cif'
Downloading PDB structure '1zbn'...
Downloading PDB structure '5uf3'...
Downloading PDB structure '1z2j'...
Downloading PDB structure '3j7p'...
Structure exists: './mmCIF_files/5fjc.cif'
Downloading PDB structure '4a4s'...
Structure exists: './mmCIF_files/3p22.cif'
Downloading PDB structure '2n6x'...
Structure exists: './mmCIF_files/3cul.cif'
Downloading PDB structure '1zig'...
Structure exists: './mmCIF_files/4jf2.cif'
Structure exists: './mmCIF_files/1cql.cif'
Structure exists: './mmCIF_files/5u3g.cif'
Downloading PDB structure '1ooa'...
Downloading PDB structure '2l2j'...
Downloading PDB structure '1f9l'...

In [44]:
hairpins_complete = []
for index, row in hairpins.iterrows():
    if row['ID'] in hairpin_ids:
        if len(hairpins_complete) == 140:
            break
        seqs = list(range(int(row['start']), int(row['end']+1)))
        hairpins_complete.append([row['ID'], row['chain'], seqs])

In [45]:
hairpins_complete = []
for id in hairpin_ids:
    row = hairpins[hairpins['ID'] == id].reset_index()
    seqs = list(range(int(row['start']), int(row['end']+1)))
    hairpins_complete.append([row['ID'][0], row['chain'][0], seqs])

C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))
C:\Users\jmp\AppData\Local\Temp\ipykernel_18208\2870336157.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  seqs = list(range(int(row['start']), int(row['end']+1)))

In [46]:
print(len(hairpins_complete))
hairpins_complete

49

[['4V8M', 'AA', [282, 283, 284, 285, 286, 287]],
 ['3DHS', 'A', [31, 32, 33, 34, 35, 36]],
 ['2N6T', 'A', [19, 20, 21, 22, 23, 24]],
 ['1FYP', 'A', [11, 12, 13, 14, 15, 16]],
 ['4XWF', 'A', [24, 25, 26, 27, 28, 29]],
 ['4ZNP', 'A', [26, 27, 28, 29, 30, 31]],
 ['2LI4', 'A', [14, 15, 16, 17, 18, 19]],
 ['2M5U', 'A', [9, 10, 11, 12, 13, 14]],
 ['4PCJ', 'A', [15, 16, 17, 18, 19, 20]],
 ['3E5C', 'A', [17, 18, 19, 20, 21, 22]],
 ['1N8X', 'A', [15, 16, 17, 18, 19, 20]],
 ['5TBW', 'AS', [36, 37, 38, 39, 40, 41]],
 ['1K4B', 'A', [5, 6, 7, 8, 9, 10]],
 ['5IEM', 'A', [25, 26, 27, 28, 29, 30]],
 ['2PCV', 'A', [15, 16, 17, 18, 19, 20]],
 ['4PLX', 'A', [23, 24, 25, 26, 27, 28]],
 ['1JUR', 'A', [8, 9, 10, 11, 12, 13]],
 ['1U63', 'D', [20, 21, 22, 23, 24, 25]],
 ['2JSE', 'A', [9, 10, 11, 12, 13, 14]],
 ['2LU0', 'A', [14, 15, 16, 17, 18, 19]],
 ['1QWA', 'A', [8, 9, 10, 11, 12, 13]],
 ['1Q96', 'A', [12, 13, 14, 15, 16, 17]],
 ['2HW8', 'B', [14, 15, 16, 17, 18, 19]],
 ['4W90', 'C', [14, 15, 16, 17, 18, 19]],
 ['4UER', 'A', [190, 191, 192, 193, 194, 195]],
 ['3V7E', 'C', [65, 66, 67, 68, 69, 70]],
 ['3IGI', 'A', [88, 89, 90, 91, 92, 93]],
 ['2NCI', 'A', [14, 15, 16, 17, 18, 19]],
 ['2CZJ', 'H', [25, 26, 27, 28, 29, 30]],
 ['3G9C', 'Q', [107, 108, 109, 110, 111, 112]],
 ['5Y7M', 'D', [23, 24, 25, 26, 27, 28]],
 ['1I6U', 'C', [16, 17, 18, 19, 20, 21]],
 ['4V5O', 'BA', [185, 186, 187, 188, 189, 190]],
 ['1ZBN', 'A', [13, 14, 15, 16, 17, 18]],
 ['5UF3', 'A', [10, 11, 12, 13, 14, 15]],
 ['1Z2J', 'A', [19, 20, 21, 22, 23, 24]],
 ['3J7P', 'S2', [197, 198, 199, 200, 201, 202]],
 ['5FJC', 'A', [48, 49, 50, 51, 52, 53]],
 ['4A4S', 'A', [9, 10, 11, 12, 13, 14]],
 ['3P22', 'A', [16, 17, 18, 19, 20, 21]],
 ['2N6X', 'A', [20, 21, 22, 23, 24, 25]],
 ['3CUL', 'C', [6, 7, 8, 9, 10, 11]],
 ['1ZIG', 'A', [4, 5, 6, 7, 8, 9]],
 ['4JF2', 'A', [7, 8, 9, 10, 11, 12]],
 ['1CQL', 'A', [21, 22, 23, 24, 25, 26]],
 ['5U3G', 'B', [17, 18, 19, 20, 21, 22]],
 ['1OOA', 'C', [13, 14, 15, 16, 17, 18]],
 ['2L2J', 'A', [19, 20, 21, 22, 23, 24]],
 ['1F9L', 'A', [9, 10, 11, 12, 13, 14]]]

In [47]:
set1 = {(item[0], item[1], tuple(item[2])) for item in motifs_ids}
set2 = {(item[0], item[1], tuple(item[2])) for item in hairpins_complete}
print(len(set2))

dif = set2.difference(set1)
print(len(dif))
hairpins_result = [list(item) for item in dif]
hairpins_result

49
49

[['2N6T', 'A', (19, 20, 21, 22, 23, 24)],
 ['2LU0', 'A', (14, 15, 16, 17, 18, 19)],
 ['2PCV', 'A', (15, 16, 17, 18, 19, 20)],
 ['4ZNP', 'A', (26, 27, 28, 29, 30, 31)],
 ['4V5O', 'BA', (185, 186, 187, 188, 189, 190)],
 ['4PLX', 'A', (23, 24, 25, 26, 27, 28)],
 ['1F9L', 'A', (9, 10, 11, 12, 13, 14)],
 ['2M5U', 'A', (9, 10, 11, 12, 13, 14)],
 ['2L2J', 'A', (19, 20, 21, 22, 23, 24)],
 ['3V7E', 'C', (65, 66, 67, 68, 69, 70)],
 ['3P22', 'A', (16, 17, 18, 19, 20, 21)],
 ['4JF2', 'A', (7, 8, 9, 10, 11, 12)],
 ['4W90', 'C', (14, 15, 16, 17, 18, 19)],
 ['5TBW', 'AS', (36, 37, 38, 39, 40, 41)],
 ['4UER', 'A', (190, 191, 192, 193, 194, 195)],
 ['3J7P', 'S2', (197, 198, 199, 200, 201, 202)],
 ['1ZIG', 'A', (4, 5, 6, 7, 8, 9)],
 ['1U63', 'D', (20, 21, 22, 23, 24, 25)],
 ['4XWF', 'A', (24, 25, 26, 27, 28, 29)],
 ['3E5C', 'A', (17, 18, 19, 20, 21, 22)],
 ['1OOA', 'C', (13, 14, 15, 16, 17, 18)],
 ['3IGI', 'A', (88, 89, 90, 91, 92, 93)],
 ['2JSE', 'A', (9, 10, 11, 12, 13, 14)],
 ['3G9C', 'Q', (107, 108, 109, 110, 111, 112)],
 ['1N8X', 'A', (15, 16, 17, 18, 19, 20)],
 ['2CZJ', 'H', (25, 26, 27, 28, 29, 30)],
 ['5UF3', 'A', (10, 11, 12, 13, 14, 15)],
 ['5IEM', 'A', (25, 26, 27, 28, 29, 30)],
 ['1JUR', 'A', (8, 9, 10, 11, 12, 13)],
 ['4A4S', 'A', (9, 10, 11, 12, 13, 14)],
 ['1Q96', 'A', (12, 13, 14, 15, 16, 17)],
 ['1ZBN', 'A', (13, 14, 15, 16, 17, 18)],
 ['4V8M', 'AA', (282, 283, 284, 285, 286, 287)],
 ['3CUL', 'C', (6, 7, 8, 9, 10, 11)],
 ['2NCI', 'A', (14, 15, 16, 17, 18, 19)],
 ['5U3G', 'B', (17, 18, 19, 20, 21, 22)],
 ['2HW8', 'B', (14, 15, 16, 17, 18, 19)],
 ['1QWA', 'A', (8, 9, 10, 11, 12, 13)],
 ['5Y7M', 'D', (23, 24, 25, 26, 27, 28)],
 ['1I6U', 'C', (16, 17, 18, 19, 20, 21)],
 ['1CQL', 'A', (21, 22, 23, 24, 25, 26)],
 ['1Z2J', 'A', (19, 20, 21, 22, 23, 24)],
 ['3DHS', 'A', (31, 32, 33, 34, 35, 36)],
 ['5FJC', 'A', (48, 49, 50, 51, 52, 53)],
 ['2N6X', 'A', (20, 21, 22, 23, 24, 25)],
 ['2LI4', 'A', (14, 15, 16, 17, 18, 19)],
 ['4PCJ', 'A', (15, 16, 17, 18, 19, 20)],
 ['1FYP', 'A', (11, 12, 13, 14, 15, 16)],
 ['1K4B', 'A', (5, 6, 7, 8, 9, 10)]]

In [48]:
parser = MMCIFParser(QUIET=True)

def get_atom_coordinates_hairpins(motifs_ids, atom, ref):
    df = pd.DataFrame(index = range(len(motifs_ids)), columns=['N1', 'N2', 'N3', 'N4', 'N5', 'N6'])
    ids = []
    har_seqs = []
    for i, motif in enumerate(motifs_ids):
        motif_cords = []
        file_name = motif[0].lower() + '.cif'
        ref_seq = ref[ref['ID'] == motif[0]]['seq'] 
        ref_seq = ref_seq.reset_index(drop=True)
        try:
            structure = parser.get_structure(file_name.rstrip('.cif'), f"./mmCIF_files/{file_name}")
        except:
            continue
        model = structure[0]
        chain = model[motif[1]]
        if motif[2][0] in chain:
            res = chain[motif[2][0]]
            if ref_seq[0][0] != res.resname:
                motif[2] = [x+1 for x in motif[2]]
        for j, motif_nuc in enumerate(motif[2]):
            if motif_nuc in chain:
                res = chain[motif_nuc]
                if ref_seq[0][j] != res.resname:
                    break
                if atom not in res:
                    break
                else: 
                    if j == 0:
                        origin, matrix = compute_new_coords(res)
                    at = res[atom]
                    motif_cords.append(transform(at, origin, matrix))
                    #motif_cords.append(at.get_coord())
            else:
                break
        if len(motif_cords) == 6:
            df.iloc[i] = motif_cords
            ids.append(motif[0])
            har_seqs.append(ref_seq[0])
    df = df.dropna()
    df['id'] = ids
    return df, har_seqs

In [49]:
hairpins_database, hairpins_seqs = get_atom_coordinates_hairpins(hairpins_complete, "C1'", hairpins)

In [50]:
hairpins_database_v2, hairpins_seqs = get_atom_coordinates_hairpins(hairpins_complete, "C1'", hairpins)

In [51]:
print(hairpins_database.shape)
hairpins_database

(49, 7)

,N1,N2,N3,N4,N5,N6,id
0,[[[[[0. 0. 0.]]]]],[[[[[-3.5438871 -3.7049432 -1.9025155]]]]],[[[[[-10.670662 -6.7294884 -0.29298866]]]]],[[[[[ -7.1047683 -10.030145 0.7923429]]]]],[[[[[ -2.7276278 -12.569199 -0.10655075]]]]],[[[[[ 1.3539786 -9.955008 -0.63923395]]]]],4V8M
1,[[[[[0. 0. 0.]]]]],[[[[[3.2748575 2.7976556 3.4341345]]]]],[[[[[8.722706 4.628001 7.9560637]]]]],[[[[[ 8.683278 12.148081 7.5423665]]]]],[[[[[10.46743 8.432603 3.820609]]]]],[[[[[ 7.2815456 7.799743 -0.7760303]]]]],3DHS
2,[[[[[0. 0. 0.]]]]],[[[[[-3.765347 2.8136775 -0.0731273]]]]],[[[[[-9.014613 4.661433 -3.6008794]]]]],[[[[[-8.947884 3.229589 3.5086875]]]]],[[[[[-12.385256 -0.88492656 -0.6513611 ]]]]],[[[[[-9.215199 -4.7842894 -1.722468 ]]]]],2N6T
3,[[[[[0. 0. 0.]]]]],[[[[[ 4.725794 1.4314231 -1.1761868]]]]],[[[[[10.733843 3.4463108 -0.25155854]]]]],[[[[[ 7.720665 1.2580003 -5.8517604]]]]],[[[[[12.745872 -1.6779963 -2.7549987]]]]],[[[[[ 9.269367 -5.079226 -0.8578677]]]]],1FYP
4,[[[[[0. 0. 0.]]]]],[[[[[-4.4977455 -1.8578837 1.46054 ]]]]],[[[[[-9.8582325 -2.1914153 4.2049766]]]]],[[[[[-10.616344 -3.8231697 8.41621 ]]]]],[[[[[-7.322173 -4.724035 13.072586]]]]],[[[[[-3.542713 -6.839065 7.431893]]]]],4XWF
5,[[[[[0. 0. 0.]]]]],[[[[[ 2.8700333 -1.41784 -4.333919 ]]]]],[[[[[ 5.1611686 0.01616359 -11.265916 ]]]]],[[[[[ 2.7648158 -5.373918 -11.357915 ]]]]],[[[[[ -6.5704017 -7.7533526 -12.466473 ]]]]],[[[[[-2.2912853 -8.581898 -6.5130644]]]]],4ZNP
6,[[[[[0. 0. 0.]]]]],[[[[[2.8770201 5.350844 1.0936072]]]]],[[[[[ 5.5740023 11.031859 -2.0318766]]]]],[[[[[ 9.201934 8.400317 -4.3453407]]]]],[[[[[11.744288 4.175626 -4.807808]]]]],[[[[[10.049747 0.10989866 -2.7653608 ]]]]],2LI4
7,[[[[[0. 0. 0.]]]]],[[[[[2.13481 2.2455022 2.8448048]]]]],[[[[[5.7237797 2.1924856 5.6122313]]]]],[[[[[8.904104 1.018796 9.466712]]]]],[[[[[ 5.845484 -0.76218015 13.805674 ]]]]],[[[[[ 1.3478925 -1.0442612 10.564959 ]]]]],2M5U
8,[[[[[0. 0. 0.]]]]],[[[[[ 2.1815383 1.0921854 -4.6980658]]]]],[[[[[ 7.4276114 3.0605164 -9.164961 ]]]]],[[[[[ 3.0011876 5.334844 -10.743189 ]]]]],[[[[[ -1.9035447 5.0571647 -11.853862 ]]]]],[[[[[-4.869855 3.142378 -8.576637]]]]],4PCJ
9,[[[[[0. 0. 0.]]]]],[[[[[ 3.0323246 3.4098723 -2.2674346]]]]],[[[[[ 3.8844934 10.167394 -6.689329 ]]]]],[[[[[ 7.0462456 6.514834 -8.438076 ]]]]],[[[[[10.476157 2.6535945 -8.175081 ]]]]],[[[[[ 8.683509 -1.1454211 -6.1606207]]]]],3E5C
10,[[[[[0. 0. 0.]]]]],[[[[[4.1453547 0.11495352 3.7782202 ]]]]],[[[[[11.891469 1.2981744 5.2004976]]]]],[[[[[10.517482 -2.958532 8.196037]]]]],[[[[[ 7.169651 -6.088097 10.252987]]]]],[[[[[ 2.3871691 -7.694583 7.110977 ]]]]],1N8X
11,[[[[[0. 0. 0.]]]]],[[[[[ 3.522296 0.753767 -4.598769]]]]],[[[[[ 6.578985 -1.4615481 -8.2507 ]]]]],[[[[[ 9.275682 -4.4741826 -15.034794 ]]]]],[[[[[ 11.754175 -5.55272 -10.116366]]]]],[[[[[ 8.983301 -5.760249 -1.6730454]]]]],5TBW
12,[[[[[0. 0. 0.]]]]],[[[[[ 2.921881 3.3927553 -1.9646646]]]]],[[[[[ 1.7232323 6.98591 -5.3706217]]]]],[[[[[ 7.8145223 4.8958416 -7.3492246]]]]],[[[[[ 10.756077 1.7865896 -10.887982 ]]]]],[[[[[ 9.491957 -0.7162842 -6.020857 ]]]]],1K4B
13,[[[[[0. 0. 0.]]]]],[[[[[-3.4002397 3.221215 -2.883709 ]]]]],[[[[[-9.921826 5.44378 -2.6653204]]]]],[[[[[-4.171551 9.843835 -5.568583]]]]],[[[[[-5.325094 12.851778 -1.016015]]]]],[[[[[-1.5698957 10.459758 2.3892636]]]]],5IEM
14,[[[[[0. 0. 0.]]]]],[[[[[ 1.436187 -3.6158767 -3.698961 ]]]]],[[[[[ 0.02744126 -7.804154 -8.550084 ]]]]],[[[[[ 5.1827393 -7.373542 -8.814829 ]]]]],[[[[[ 9.093543 -3.6497273 -7.7550898]]]]],[[[[[ 9.324729 0.1348033 -4.1056037]]]]],2PCV
15,[[[[[0. 0. 0.]]]]],[[[[[-3.4753857 -2.5530534 3.3884075]]]]],[[[[[-7.80139 -2.8196812 8.84007 ]]]]],[[[[[-5.856683 -7.480961 8.34202 ]]]]],[[[[[ -4.6962624 -11.565577 5.219216 ]]]]],[[[[[ -2.1587062 -10.295794 1.5081666]]]]],4PLX
16,[[[[[0. 0. 0.]]]]],[[[[[ 1.6920376 1.2679031 -5.785238 ]]]]],[[[[[ 4.9823318 4.7535615 -8.617673 ]]]]],[[[[[ 7.775089 0.7121029 -9.859068 ]]]]],[[[[[ 9.211085 -3.824872 -7.8082895]]]]],[[[[[ 6.9266195 -6.903377 -4.81322 ]]]]],1JUR
17,[[[[[0. 0. 0.]]]]],[[[[[-1.5932267 8.332013 -2.5340328]]]]],[[[[[ 3.6580794 2.5874114 -4.8155475]]]]],[[[[[ 9.492568 1.8321595 -7.3923817]]]]],[[[[[14.208347 -0.06424522 -5.394563 ]]]]],[[[[[9.828057 2.8186436 1.2235307]]]]],1U63
18,[[[[[0. 0. 0.]]]]],[[[[[ 1.5449314 -4.224141 2.6870646]]]]],[[[[[ 2.9859 -11.382388 4.4391613]]]]],[[[[[ 1.0382228 -10.283411 9.254776 ]]]]],[[[[[ 1.1315937 -6.2460847 13.114492 ]]]]],[[[[[-0.08138227 -2.391768 10.373361 ]]]]],2JSE
19,[[[[[0. 0. 0.]]]]],[[[[[ 2.2133045 4.6331563 -1.1209974]]]]],[[[[[ 5.0684156 11.404979 -0.51033235]]]]],[[[[[ 5.359246 10.697373 -5.6201158]]]]],[[[[[ 5.880747 6.5824513 -10.092964 ]]]]],[[[[[ 3.6728592 2.6461303 -10.1552925]]]]],2LU0
20,[[[[[0. 0. 0.]]]]],[[[[[ 0.1741414 5.1472917 -1.466552 ]]]]],[[[[[ 1.7010086 10.185057 -5.904903 ]]]]],[[[[[-3.1345696 11.472218 -0.5018791]]]]],[[[[[-5.5351763 10.007546 -6.561138 ]]]]],[[[[[-6.5950937 5.128483 -5.9147873]]]]],1QWA
21,[[[[[0. 0. 0.]]]]],[[[[[0.8114064 5.3671994 0.76951694]]]]],[[[[[-0.72292066 12.466543 -0.983001 ]]]]],[[[[[ 4.3210087 12.190811 0.47091985]]]]],[[[[[ 8.119691 10.34057 3.4459252]]]]],[[[[[8.332611 5.721991 2.8807201]]]]],1Q96
22,[[[[[0. 0. 0.]]]]],[[[[[ 3.5560799 2.7883987 -2.6453655]]]]],[[[[[ 9.997341 4.6355333 -3.1635149]]]]],[[[[[ 4.7909026 6.5326667 -8.14758 ]]]]],[[[[[ 8.407814 1.8248885 -10.940578 ]]]]],[[[[[ 5.0080633 -0.916469 -9.425853 ]]]]],2HW8
23,[[[[[0. 0. 0.]]]]],[[[[[-4.356507 7.5448236 1.6624836]]]]],[[[[[ 0.54427147 10.1128 -2.1955726 ]]]]],[[[[[ 5.22344 8.861865 -4.391129]]]]],[[[[[10.675365 4.3476753 -7.232042 ]]]]],[[[[[10.6486025 4.2104354 -1.6021109]]]]],4W90
24,[[[[[0. 0. 0.]]]]],[[[[[ 5.1172028 -1.3224163 -0.6744344]]]]],[[[[[ 8.848634 -2.8387482 -0.6236274]]]]],[[[[[ 9.533474 -4.989544 3.880011]]]]],[[[[[10.799891 -8.552836 7.9931297]]]]],[[[[[ 6.471106 -7.2581267 5.279246 ]]]]],4UER
25,[[[[[0. 0. 0.]]]]],[[[[[ 4.144762 -2.1879153 -2.0528407]]]]],[[[[[ 7.765231 0.06917286 -8.473996 ]]]]],[[[[[ 7.530019 -5.1728973 -2.8385582]]]]],[[[[[13.402426 -2.9394827 -0.6940148]]]]],[[[[[9.851795 0.11296535 1.8227459 ]]]]],3V7E
26,[[[[[0. 0. 0.]]]]],[[[[[ 4.015763 3.7630692 -0.58391154]]]]],[[[[[ 6.510495 10.019863 -4.0835958]]]]],[[[[[10.404858 6.2852507 -3.597763 ]]]]],[[[[[13.87188 2.5845351 -1.8958873]]]]],[[[[[10.492225 -1.2707663 -1.066926 ]]]]],3IGI
27,[[[[[0. 0. 0.]]]]],[[[[[-0.67687774 4.9550858 2.4509869 ]]]]],[[[[[ 0.2868786 10.421534 6.3006124]]]]],[[[[[-6.800039 7.7662554 3.0806618]]]]],[[[[[-4.6875634 13.477901 0.02192497]]]]],[[[[[-2.320022 9.637743 -3.3337574]]]]],2NCI
28,[[[[[0. 0. 0.]]]]],[[[[[4.4476967 2.5940402 2.0031896]]]]],[[[[[7.7883935 5.287223 7.266458 ]]]]],[[[[[9.518322 4.6145 0.54010653]]]]],[[[[[13.357318 0.77087665 2.2794933 ]]]]],[[[[[10.274188 -1.8491212 0.03866541]]]]],2CZJ
29,[[[[[0. 0. 0.]]]]],[[[[[-1.7199191 1.9578706 -5.2175517]]]]],[[[[[-6.0523024 6.387149 -9.093741 ]]]]],[[[[[ -6.0514765 1.6266658 -11.211388 ]]]]],[[[[[ -4.2922945 -2.819615 -13.398305 ]]]]],[[[[[-2.0290275 -5.026986 -9.462573 ]]]]],3G9C
30,[[[[[0. 0. 0.]]]]],[[[[[2.9325528 4.201006 1.5650347]]]]],[[[[[ 5.0430436 11.081758 1.6283066]]]]],[[[[[9.337952 8.288127 2.325546]]]]],[[[[[11.619959 4.40727 4.7433133]]]]],[[[[[ 9.701393 -0.07406108 4.514863 ]]]]],5Y7M
31,[[[[[0. 0. 0.]]]]],[[[[[ 0.27961087 -1.4798398 4.991447 ]]]]],[[[[[ 1.4590063 0.2072773 11.630555 ]]]]],[[[[[-0.2799412 -6.9099226 8.5652895]]]]],[[[[[-5.448218 -5.0559564 12.128038 ]]]]],[[[[[-6.711768 -3.127031 7.925332]]]]],1I6U
32,[[[[[0. 0. 0.]]]]],[[[[[-1.0720751 -4.338127 3.6284492]]]]],[[[[[-0.06491542 -7.4121456 6.5416946 ]]]]],[[[[[ -1.2670016 -13.280396 2.9039378]]]]],[[[[[ 6.6572523 -14.092081 2.43798 ]]]]],[[[[[ -0.39790988 -10.796235 -0.14797038]]]]],4V5O
33,[[[[[0. 0. 0.]]]]],[[[[[-5.629143 1.742555 3.1652732]]]]],[[[[[-4.9675016 7.171194 2.8018062]]]]],[[[[[-2.7514977 6.9903555 -1.76012 ]]]]],[[[[[-7.5074463 7.3515463 -6.2240467]]]]],[[[[[-1.8709354 5.07608 -9.567377 ]]]]],1ZBN
34,[[[[[0. 0. 0.]]]]],[[[[[ 5.3654594 5.8228393 -2.0932746]]]]],[[[[[ 8.78272 1.201987 -6.205616]]]]],[[[[[10.78567 -3.0974503 -4.716566 ]]]]],[[[[[12.503976 -6.0998363 -0.8871083]]]]],[[[[[ 9.060494 -6.302117 2.6118188]]]]],5UF3
35,[[[[[0. 0. 0.]]]]],[[[[[ 1.2225335 4.8320923 -0.3372116]]]]],[[[[[ 3.9620144 8.35824 -2.8834472]]]]],[[[[[ 7.56484 11.602406 -0.25550735]]]]],[[[[[7.998368 9.507133 3.3585553]]]]],[[[[[7.1560283 5.1719675 6.016839 ]]]]],1Z2J
36,[[[[[0. 0. 0.]]]]],[[[[[-2.2972324 -5.0240993 0.30986357]]]]],[[[[[ -2.8192558 -11.590214 4.1950903]]]]],[[[[[ -2.161128 -12.070811 -0.8606236]]]]],[[[[[ -4.9628935 -11.268103 -4.878889 ]]]]],[[[[[-5.276856 -6.6413445 -5.9767056]]]]],3J7P
37,[[[[[0. 0. 0.]]]]],[[[[[ 0.23784602 -1.8510833 5.293739 ]]]]],[[[[[ 3.7550635 -4.867634 11.008118 ]]]]],[[[[[-0.694721 -6.9614763 10.584135 ]]]]],[[[[[-5.878017 -6.7600794 9.95448 ]]]]],[[[[[-7.057581 -5.2618804 5.593775 ]]]]],5FJC
38,[[[[[0. 0. 0.]]]]],[[[[[ 1.256896 -4.9353127 0.60715914]]]]],[[[[[ 5.933649 -10.472454 2.3188324]]]]],[[[[[ 3.5166788 -11.567701 -1.9935789]]]]],[[[[[ -0.40189886 -11.461012 -5.2300878 ]]]]],[[[[[-2.7019167 -7.4826107 -6.612133 ]]]]],4A4S
39,[[[[[0. 0. 0.]]]]],[[[[[-4.908823 0.58207786 2.3863864 ]]]]],[[[[[-12.195141 0.5751297 3.4452195]]]]],[[[[[-10.326402 3.2967913 7.043878 ]]]]],[[[[[-6.68363 2.9323244 10.894603 ]]]]],[[[[[-1.8971426 2.8279965 10.229935 ]]]]],3P22
40,[[[[[0. 0. 0.]]]]],[[[[[-1.6437637 3.8053422 3.0609834]]]]],[[[[[-0.9066739 9.067933 6.6297593]]]]],[[[[[-7.5870247 6.685252 3.9659793]]]]],[[[[[-5.4648333 12.281635 1.2446487]]]]],[[[[[-3.2678196 9.851127 -2.3457332]]]]],2N6X
41,[[[[[0. 0. 0.]]]]],[[[[[-1.8631366 0.4842954 5.105202 ]]]]],[[[[[-3.7642798 -1.4136908 11.629391 ]]]]],[[[[[-6.4598355 3.066067 10.332536 ]]]]],[[[[[-5.576955 8.079649 8.721577]]]]],[[[[[-4.477625 8.562953 4.0737453]]]]],3CUL
42,[[[[[0. 0. 0.]]]]],[[[[[ 4.6700864 0.94945097 -2.0393653 ]]]]],[[[[[11.617462 4.297488 -0.01918197]]]]],[[[[[10.125802 4.772961 -4.9923573]]]]],[[[[[ 8.875765 3.7337708 -9.749812 ]]]]],[[[[[ 4.5997176 2.6389413 -9.140457 ]]]]],1ZIG
43,[[[[[0. 0. 0.]]]]],[[[[[-4.364952 -0.12355682 3.260706 ]]]]],[[[[[-11.414663 -0.27248904 4.6292276 ]]]]],[[[[[-9.4207 2.4551182 8.368152 ]]]]],[[[[[-5.579653 2.9028475 11.8917055]]]]],[[[[[-1.0826992 2.5377612 10.226369 ]]]]],4JF2
44,[[[[[0. 0. 0.]]]]],[[[[[ 2.3786757 4.319788 -1.255034 ]]]]],[[[[[ 3.4028652 10.172615 -4.4596624]]]]],[[[[[ 5.147479 7.1218596 -7.5206137]]]]],[[[[[ 8.263217 3.7551875 -8.788775 ]]]]],[[[[[ 9.158224 0.3072158 -5.5878296]]]]],1CQL
45,[[[[[0. 0. 0.]]]]],[[[[[ 2.6780841 -0.658606 4.377392 ]]]]],[[[[[ 6.283086 -0.3701228 9.019831 ]]]]],[[[[[ 0.7314091 -6.543709 11.983854 ]]]]],[[[[[-0.6608583 0.2906443 14.427138 ]]]]],[[[[[-2.51666 2.220636 10.000626]]]]],5U3G
46,[[[[[0. 0. 0.]]]]],[[[[[-0.00760901 -0.02235329 5.2808394 ]]]]],[[[[[ 4.5469356 -0.28623402 9.958129 ]]]]],[[[[[ 9.542906 -3.426835 15.9349785]]]]],[[[[[7.8113785 0.32033905 8.670085 ]]]]],[[[[[9.093323 0.95648706 4.84858 ]]]]],1OOA
47,[[[[[0. 0. 0.]]]]],[[[[[ 1.169767 5.076643 -1.9698019]]]]],[[[[[ 1.9220662 11.612395 -0.5324397]]]]],[[[[[ 2.9527514 8.892046 -7.4942474]]]]],[[[[[ 8.489534 10.036923 -4.986317]]]]],[[[[[ 8.882084 4.8308105 -3.2102327]]]]],2L2J
48,[[[[[0. 0. 0.]]]]],[[[[[ 2.8364363 -4.221756 -3.5412753]]]]],[[[[[ 6.166371 -6.2806096 -9.5906315]]]]],[[[[[ 1.7903731 -9.214501 -9.783133 ]]]]],[[[[[ -1.8620794 -11.5328245 -7.2901726]]]]],[[[[[-3.7991729 -9.642437 -2.2840796]]]]],1F9L

In [52]:
hairpins_database_v2

,N1,N2,N3,N4,N5,N6,id
0,[[[[[0. 0. 0.]]]]],[[[[[-3.5438871 -3.7049432 -1.9025155]]]]],[[[[[-10.670662 -6.7294884 -0.29298866]]]]],[[[[[ -7.1047683 -10.030145 0.7923429]]]]],[[[[[ -2.7276278 -12.569199 -0.10655075]]]]],[[[[[ 1.3539786 -9.955008 -0.63923395]]]]],4V8M
1,[[[[[0. 0. 0.]]]]],[[[[[3.2748575 2.7976556 3.4341345]]]]],[[[[[8.722706 4.628001 7.9560637]]]]],[[[[[ 8.683278 12.148081 7.5423665]]]]],[[[[[10.46743 8.432603 3.820609]]]]],[[[[[ 7.2815456 7.799743 -0.7760303]]]]],3DHS
2,[[[[[0. 0. 0.]]]]],[[[[[-3.765347 2.8136775 -0.0731273]]]]],[[[[[-9.014613 4.661433 -3.6008794]]]]],[[[[[-8.947884 3.229589 3.5086875]]]]],[[[[[-12.385256 -0.88492656 -0.6513611 ]]]]],[[[[[-9.215199 -4.7842894 -1.722468 ]]]]],2N6T
3,[[[[[0. 0. 0.]]]]],[[[[[ 4.725794 1.4314231 -1.1761868]]]]],[[[[[10.733843 3.4463108 -0.25155854]]]]],[[[[[ 7.720665 1.2580003 -5.8517604]]]]],[[[[[12.745872 -1.6779963 -2.7549987]]]]],[[[[[ 9.269367 -5.079226 -0.8578677]]]]],1FYP
4,[[[[[0. 0. 0.]]]]],[[[[[-4.4977455 -1.8578837 1.46054 ]]]]],[[[[[-9.8582325 -2.1914153 4.2049766]]]]],[[[[[-10.616344 -3.8231697 8.41621 ]]]]],[[[[[-7.322173 -4.724035 13.072586]]]]],[[[[[-3.542713 -6.839065 7.431893]]]]],4XWF
5,[[[[[0. 0. 0.]]]]],[[[[[ 2.8700333 -1.41784 -4.333919 ]]]]],[[[[[ 5.1611686 0.01616359 -11.265916 ]]]]],[[[[[ 2.7648158 -5.373918 -11.357915 ]]]]],[[[[[ -6.5704017 -7.7533526 -12.466473 ]]]]],[[[[[-2.2912853 -8.581898 -6.5130644]]]]],4ZNP
6,[[[[[0. 0. 0.]]]]],[[[[[2.8770201 5.350844 1.0936072]]]]],[[[[[ 5.5740023 11.031859 -2.0318766]]]]],[[[[[ 9.201934 8.400317 -4.3453407]]]]],[[[[[11.744288 4.175626 -4.807808]]]]],[[[[[10.049747 0.10989866 -2.7653608 ]]]]],2LI4
7,[[[[[0. 0. 0.]]]]],[[[[[2.13481 2.2455022 2.8448048]]]]],[[[[[5.7237797 2.1924856 5.6122313]]]]],[[[[[8.904104 1.018796 9.466712]]]]],[[[[[ 5.845484 -0.76218015 13.805674 ]]]]],[[[[[ 1.3478925 -1.0442612 10.564959 ]]]]],2M5U
8,[[[[[0. 0. 0.]]]]],[[[[[ 2.1815383 1.0921854 -4.6980658]]]]],[[[[[ 7.4276114 3.0605164 -9.164961 ]]]]],[[[[[ 3.0011876 5.334844 -10.743189 ]]]]],[[[[[ -1.9035447 5.0571647 -11.853862 ]]]]],[[[[[-4.869855 3.142378 -8.576637]]]]],4PCJ
9,[[[[[0. 0. 0.]]]]],[[[[[ 3.0323246 3.4098723 -2.2674346]]]]],[[[[[ 3.8844934 10.167394 -6.689329 ]]]]],[[[[[ 7.0462456 6.514834 -8.438076 ]]]]],[[[[[10.476157 2.6535945 -8.175081 ]]]]],[[[[[ 8.683509 -1.1454211 -6.1606207]]]]],3E5C
10,[[[[[0. 0. 0.]]]]],[[[[[4.1453547 0.11495352 3.7782202 ]]]]],[[[[[11.891469 1.2981744 5.2004976]]]]],[[[[[10.517482 -2.958532 8.196037]]]]],[[[[[ 7.169651 -6.088097 10.252987]]]]],[[[[[ 2.3871691 -7.694583 7.110977 ]]]]],1N8X
11,[[[[[0. 0. 0.]]]]],[[[[[ 3.522296 0.753767 -4.598769]]]]],[[[[[ 6.578985 -1.4615481 -8.2507 ]]]]],[[[[[ 9.275682 -4.4741826 -15.034794 ]]]]],[[[[[ 11.754175 -5.55272 -10.116366]]]]],[[[[[ 8.983301 -5.760249 -1.6730454]]]]],5TBW
12,[[[[[0. 0. 0.]]]]],[[[[[ 2.921881 3.3927553 -1.9646646]]]]],[[[[[ 1.7232323 6.98591 -5.3706217]]]]],[[[[[ 7.8145223 4.8958416 -7.3492246]]]]],[[[[[ 10.756077 1.7865896 -10.887982 ]]]]],[[[[[ 9.491957 -0.7162842 -6.020857 ]]]]],1K4B
13,[[[[[0. 0. 0.]]]]],[[[[[-3.4002397 3.221215 -2.883709 ]]]]],[[[[[-9.921826 5.44378 -2.6653204]]]]],[[[[[-4.171551 9.843835 -5.568583]]]]],[[[[[-5.325094 12.851778 -1.016015]]]]],[[[[[-1.5698957 10.459758 2.3892636]]]]],5IEM
14,[[[[[0. 0. 0.]]]]],[[[[[ 1.436187 -3.6158767 -3.698961 ]]]]],[[[[[ 0.02744126 -7.804154 -8.550084 ]]]]],[[[[[ 5.1827393 -7.373542 -8.814829 ]]]]],[[[[[ 9.093543 -3.6497273 -7.7550898]]]]],[[[[[ 9.324729 0.1348033 -4.1056037]]]]],2PCV
15,[[[[[0. 0. 0.]]]]],[[[[[-3.4753857 -2.5530534 3.3884075]]]]],[[[[[-7.80139 -2.8196812 8.84007 ]]]]],[[[[[-5.856683 -7.480961 8.34202 ]]]]],[[[[[ -4.6962624 -11.565577 5.219216 ]]]]],[[[[[ -2.1587062 -10.295794 1.5081666]]]]],4PLX
16,[[[[[0. 0. 0.]]]]],[[[[[ 1.6920376 1.2679031 -5.785238 ]]]]],[[[[[ 4.9823318 4.7535615 -8.617673 ]]]]],[[[[[ 7.775089 0.7121029 -9.859068 ]]]]],[[[[[ 9.211085 -3.824872 -7.8082895]]]]],[[[[[ 6.9266195 -6.903377 -4.81322 ]]]]],1JUR
17,[[[[[0. 0. 0.]]]]],[[[[[-1.5932267 8.332013 -2.5340328]]]]],[[[[[ 3.6580794 2.5874114 -4.8155475]]]]],[[[[[ 9.492568 1.8321595 -7.3923817]]]]],[[[[[14.208347 -0.06424522 -5.394563 ]]]]],[[[[[9.828057 2.8186436 1.2235307]]]]],1U63
18,[[[[[0. 0. 0.]]]]],[[[[[ 1.5449314 -4.224141 2.6870646]]]]],[[[[[ 2.9859 -11.382388 4.4391613]]]]],[[[[[ 1.0382228 -10.283411 9.254776 ]]]]],[[[[[ 1.1315937 -6.2460847 13.114492 ]]]]],[[[[[-0.08138227 -2.391768 10.373361 ]]]]],2JSE
19,[[[[[0. 0. 0.]]]]],[[[[[ 2.2133045 4.6331563 -1.1209974]]]]],[[[[[ 5.0684156 11.404979 -0.51033235]]]]],[[[[[ 5.359246 10.697373 -5.6201158]]]]],[[[[[ 5.880747 6.5824513 -10.092964 ]]]]],[[[[[ 3.6728592 2.6461303 -10.1552925]]]]],2LU0
20,[[[[[0. 0. 0.]]]]],[[[[[ 0.1741414 5.1472917 -1.466552 ]]]]],[[[[[ 1.7010086 10.185057 -5.904903 ]]]]],[[[[[-3.1345696 11.472218 -0.5018791]]]]],[[[[[-5.5351763 10.007546 -6.561138 ]]]]],[[[[[-6.5950937 5.128483 -5.9147873]]]]],1QWA
21,[[[[[0. 0. 0.]]]]],[[[[[0.8114064 5.3671994 0.76951694]]]]],[[[[[-0.72292066 12.466543 -0.983001 ]]]]],[[[[[ 4.3210087 12.190811 0.47091985]]]]],[[[[[ 8.119691 10.34057 3.4459252]]]]],[[[[[8.332611 5.721991 2.8807201]]]]],1Q96
22,[[[[[0. 0. 0.]]]]],[[[[[ 3.5560799 2.7883987 -2.6453655]]]]],[[[[[ 9.997341 4.6355333 -3.1635149]]]]],[[[[[ 4.7909026 6.5326667 -8.14758 ]]]]],[[[[[ 8.407814 1.8248885 -10.940578 ]]]]],[[[[[ 5.0080633 -0.916469 -9.425853 ]]]]],2HW8
23,[[[[[0. 0. 0.]]]]],[[[[[-4.356507 7.5448236 1.6624836]]]]],[[[[[ 0.54427147 10.1128 -2.1955726 ]]]]],[[[[[ 5.22344 8.861865 -4.391129]]]]],[[[[[10.675365 4.3476753 -7.232042 ]]]]],[[[[[10.6486025 4.2104354 -1.6021109]]]]],4W90
24,[[[[[0. 0. 0.]]]]],[[[[[ 5.1172028 -1.3224163 -0.6744344]]]]],[[[[[ 8.848634 -2.8387482 -0.6236274]]]]],[[[[[ 9.533474 -4.989544 3.880011]]]]],[[[[[10.799891 -8.552836 7.9931297]]]]],[[[[[ 6.471106 -7.2581267 5.279246 ]]]]],4UER
25,[[[[[0. 0. 0.]]]]],[[[[[ 4.144762 -2.1879153 -2.0528407]]]]],[[[[[ 7.765231 0.06917286 -8.473996 ]]]]],[[[[[ 7.530019 -5.1728973 -2.8385582]]]]],[[[[[13.402426 -2.9394827 -0.6940148]]]]],[[[[[9.851795 0.11296535 1.8227459 ]]]]],3V7E
26,[[[[[0. 0. 0.]]]]],[[[[[ 4.015763 3.7630692 -0.58391154]]]]],[[[[[ 6.510495 10.019863 -4.0835958]]]]],[[[[[10.404858 6.2852507 -3.597763 ]]]]],[[[[[13.87188 2.5845351 -1.8958873]]]]],[[[[[10.492225 -1.2707663 -1.066926 ]]]]],3IGI
27,[[[[[0. 0. 0.]]]]],[[[[[-0.67687774 4.9550858 2.4509869 ]]]]],[[[[[ 0.2868786 10.421534 6.3006124]]]]],[[[[[-6.800039 7.7662554 3.0806618]]]]],[[[[[-4.6875634 13.477901 0.02192497]]]]],[[[[[-2.320022 9.637743 -3.3337574]]]]],2NCI
28,[[[[[0. 0. 0.]]]]],[[[[[4.4476967 2.5940402 2.0031896]]]]],[[[[[7.7883935 5.287223 7.266458 ]]]]],[[[[[9.518322 4.6145 0.54010653]]]]],[[[[[13.357318 0.77087665 2.2794933 ]]]]],[[[[[10.274188 -1.8491212 0.03866541]]]]],2CZJ
29,[[[[[0. 0. 0.]]]]],[[[[[-1.7199191 1.9578706 -5.2175517]]]]],[[[[[-6.0523024 6.387149 -9.093741 ]]]]],[[[[[ -6.0514765 1.6266658 -11.211388 ]]]]],[[[[[ -4.2922945 -2.819615 -13.398305 ]]]]],[[[[[-2.0290275 -5.026986 -9.462573 ]]]]],3G9C
30,[[[[[0. 0. 0.]]]]],[[[[[2.9325528 4.201006 1.5650347]]]]],[[[[[ 5.0430436 11.081758 1.6283066]]]]],[[[[[9.337952 8.288127 2.325546]]]]],[[[[[11.619959 4.40727 4.7433133]]]]],[[[[[ 9.701393 -0.07406108 4.514863 ]]]]],5Y7M
31,[[[[[0. 0. 0.]]]]],[[[[[ 0.27961087 -1.4798398 4.991447 ]]]]],[[[[[ 1.4590063 0.2072773 11.630555 ]]]]],[[[[[-0.2799412 -6.9099226 8.5652895]]]]],[[[[[-5.448218 -5.0559564 12.128038 ]]]]],[[[[[-6.711768 -3.127031 7.925332]]]]],1I6U
32,[[[[[0. 0. 0.]]]]],[[[[[-1.0720751 -4.338127 3.6284492]]]]],[[[[[-0.06491542 -7.4121456 6.5416946 ]]]]],[[[[[ -1.2670016 -13.280396 2.9039378]]]]],[[[[[ 6.6572523 -14.092081 2.43798 ]]]]],[[[[[ -0.39790988 -10.796235 -0.14797038]]]]],4V5O
33,[[[[[0. 0. 0.]]]]],[[[[[-5.629143 1.742555 3.1652732]]]]],[[[[[-4.9675016 7.171194 2.8018062]]]]],[[[[[-2.7514977 6.9903555 -1.76012 ]]]]],[[[[[-7.5074463 7.3515463 -6.2240467]]]]],[[[[[-1.8709354 5.07608 -9.567377 ]]]]],1ZBN
34,[[[[[0. 0. 0.]]]]],[[[[[ 5.3654594 5.8228393 -2.0932746]]]]],[[[[[ 8.78272 1.201987 -6.205616]]]]],[[[[[10.78567 -3.0974503 -4.716566 ]]]]],[[[[[12.503976 -6.0998363 -0.8871083]]]]],[[[[[ 9.060494 -6.302117 2.6118188]]]]],5UF3
35,[[[[[0. 0. 0.]]]]],[[[[[ 1.2225335 4.8320923 -0.3372116]]]]],[[[[[ 3.9620144 8.35824 -2.8834472]]]]],[[[[[ 7.56484 11.602406 -0.25550735]]]]],[[[[[7.998368 9.507133 3.3585553]]]]],[[[[[7.1560283 5.1719675 6.016839 ]]]]],1Z2J
36,[[[[[0. 0. 0.]]]]],[[[[[-2.2972324 -5.0240993 0.30986357]]]]],[[[[[ -2.8192558 -11.590214 4.1950903]]]]],[[[[[ -2.161128 -12.070811 -0.8606236]]]]],[[[[[ -4.9628935 -11.268103 -4.878889 ]]]]],[[[[[-5.276856 -6.6413445 -5.9767056]]]]],3J7P
37,[[[[[0. 0. 0.]]]]],[[[[[ 0.23784602 -1.8510833 5.293739 ]]]]],[[[[[ 3.7550635 -4.867634 11.008118 ]]]]],[[[[[-0.694721 -6.9614763 10.584135 ]]]]],[[[[[-5.878017 -6.7600794 9.95448 ]]]]],[[[[[-7.057581 -5.2618804 5.593775 ]]]]],5FJC
38,[[[[[0. 0. 0.]]]]],[[[[[ 1.256896 -4.9353127 0.60715914]]]]],[[[[[ 5.933649 -10.472454 2.3188324]]]]],[[[[[ 3.5166788 -11.567701 -1.9935789]]]]],[[[[[ -0.40189886 -11.461012 -5.2300878 ]]]]],[[[[[-2.7019167 -7.4826107 -6.612133 ]]]]],4A4S
39,[[[[[0. 0. 0.]]]]],[[[[[-4.908823 0.58207786 2.3863864 ]]]]],[[[[[-12.195141 0.5751297 3.4452195]]]]],[[[[[-10.326402 3.2967913 7.043878 ]]]]],[[[[[-6.68363 2.9323244 10.894603 ]]]]],[[[[[-1.8971426 2.8279965 10.229935 ]]]]],3P22
40,[[[[[0. 0. 0.]]]]],[[[[[-1.6437637 3.8053422 3.0609834]]]]],[[[[[-0.9066739 9.067933 6.6297593]]]]],[[[[[-7.5870247 6.685252 3.9659793]]]]],[[[[[-5.4648333 12.281635 1.2446487]]]]],[[[[[-3.2678196 9.851127 -2.3457332]]]]],2N6X
41,[[[[[0. 0. 0.]]]]],[[[[[-1.8631366 0.4842954 5.105202 ]]]]],[[[[[-3.7642798 -1.4136908 11.629391 ]]]]],[[[[[-6.4598355 3.066067 10.332536 ]]]]],[[[[[-5.576955 8.079649 8.721577]]]]],[[[[[-4.477625 8.562953 4.0737453]]]]],3CUL
42,[[[[[0. 0. 0.]]]]],[[[[[ 4.6700864 0.94945097 -2.0393653 ]]]]],[[[[[11.617462 4.297488 -0.01918197]]]]],[[[[[10.125802 4.772961 -4.9923573]]]]],[[[[[ 8.875765 3.7337708 -9.749812 ]]]]],[[[[[ 4.5997176 2.6389413 -9.140457 ]]]]],1ZIG
43,[[[[[0. 0. 0.]]]]],[[[[[-4.364952 -0.12355682 3.260706 ]]]]],[[[[[-11.414663 -0.27248904 4.6292276 ]]]]],[[[[[-9.4207 2.4551182 8.368152 ]]]]],[[[[[-5.579653 2.9028475 11.8917055]]]]],[[[[[-1.0826992 2.5377612 10.226369 ]]]]],4JF2
44,[[[[[0. 0. 0.]]]]],[[[[[ 2.3786757 4.319788 -1.255034 ]]]]],[[[[[ 3.4028652 10.172615 -4.4596624]]]]],[[[[[ 5.147479 7.1218596 -7.5206137]]]]],[[[[[ 8.263217 3.7551875 -8.788775 ]]]]],[[[[[ 9.158224 0.3072158 -5.5878296]]]]],1CQL
45,[[[[[0. 0. 0.]]]]],[[[[[ 2.6780841 -0.658606 4.377392 ]]]]],[[[[[ 6.283086 -0.3701228 9.019831 ]]]]],[[[[[ 0.7314091 -6.543709 11.983854 ]]]]],[[[[[-0.6608583 0.2906443 14.427138 ]]]]],[[[[[-2.51666 2.220636 10.000626]]]]],5U3G
46,[[[[[0. 0. 0.]]]]],[[[[[-0.00760901 -0.02235329 5.2808394 ]]]]],[[[[[ 4.5469356 -0.28623402 9.958129 ]]]]],[[[[[ 9.542906 -3.426835 15.9349785]]]]],[[[[[7.8113785 0.32033905 8.670085 ]]]]],[[[[[9.093323 0.95648706 4.84858 ]]]]],1OOA
47,[[[[[0. 0. 0.]]]]],[[[[[ 1.169767 5.076643 -1.9698019]]]]],[[[[[ 1.9220662 11.612395 -0.5324397]]]]],[[[[[ 2.9527514 8.892046 -7.4942474]]]]],[[[[[ 8.489534 10.036923 -4.986317]]]]],[[[[[ 8.882084 4.8308105 -3.2102327]]]]],2L2J
48,[[[[[0. 0. 0.]]]]],[[[[[ 2.8364363 -4.221756 -3.5412753]]]]],[[[[[ 6.166371 -6.2806096 -9.5906315]]]]],[[[[[ 1.7903731 -9.214501 -9.783133 ]]]]],[[[[[ -1.8620794 -11.5328245 -7.2901726]]]]],[[[[[-3.7991729 -9.642437 -2.2840796]]]]],1F9L

In [53]:
# hairpins_database_v2 = hairpins_database_v2.drop('id', axis=1)

# for column in hairpins_database_v2.columns:
#     hairpins_database_v2[column] = hairpins_database_v2[column].apply(lambda x: ','.join(map(str,np.array(x).flatten())))
    
hairpins_database_v2['class'] = 0
hairpins_database_v2

,N1,N2,N3,N4,N5,N6,id,class
0,[[[[[0. 0. 0.]]]]],[[[[[-3.5438871 -3.7049432 -1.9025155]]]]],[[[[[-10.670662 -6.7294884 -0.29298866]]]]],[[[[[ -7.1047683 -10.030145 0.7923429]]]]],[[[[[ -2.7276278 -12.569199 -0.10655075]]]]],[[[[[ 1.3539786 -9.955008 -0.63923395]]]]],4V8M,0
1,[[[[[0. 0. 0.]]]]],[[[[[3.2748575 2.7976556 3.4341345]]]]],[[[[[8.722706 4.628001 7.9560637]]]]],[[[[[ 8.683278 12.148081 7.5423665]]]]],[[[[[10.46743 8.432603 3.820609]]]]],[[[[[ 7.2815456 7.799743 -0.7760303]]]]],3DHS,0
2,[[[[[0. 0. 0.]]]]],[[[[[-3.765347 2.8136775 -0.0731273]]]]],[[[[[-9.014613 4.661433 -3.6008794]]]]],[[[[[-8.947884 3.229589 3.5086875]]]]],[[[[[-12.385256 -0.88492656 -0.6513611 ]]]]],[[[[[-9.215199 -4.7842894 -1.722468 ]]]]],2N6T,0
3,[[[[[0. 0. 0.]]]]],[[[[[ 4.725794 1.4314231 -1.1761868]]]]],[[[[[10.733843 3.4463108 -0.25155854]]]]],[[[[[ 7.720665 1.2580003 -5.8517604]]]]],[[[[[12.745872 -1.6779963 -2.7549987]]]]],[[[[[ 9.269367 -5.079226 -0.8578677]]]]],1FYP,0
4,[[[[[0. 0. 0.]]]]],[[[[[-4.4977455 -1.8578837 1.46054 ]]]]],[[[[[-9.8582325 -2.1914153 4.2049766]]]]],[[[[[-10.616344 -3.8231697 8.41621 ]]]]],[[[[[-7.322173 -4.724035 13.072586]]]]],[[[[[-3.542713 -6.839065 7.431893]]]]],4XWF,0
5,[[[[[0. 0. 0.]]]]],[[[[[ 2.8700333 -1.41784 -4.333919 ]]]]],[[[[[ 5.1611686 0.01616359 -11.265916 ]]]]],[[[[[ 2.7648158 -5.373918 -11.357915 ]]]]],[[[[[ -6.5704017 -7.7533526 -12.466473 ]]]]],[[[[[-2.2912853 -8.581898 -6.5130644]]]]],4ZNP,0
6,[[[[[0. 0. 0.]]]]],[[[[[2.8770201 5.350844 1.0936072]]]]],[[[[[ 5.5740023 11.031859 -2.0318766]]]]],[[[[[ 9.201934 8.400317 -4.3453407]]]]],[[[[[11.744288 4.175626 -4.807808]]]]],[[[[[10.049747 0.10989866 -2.7653608 ]]]]],2LI4,0
7,[[[[[0. 0. 0.]]]]],[[[[[2.13481 2.2455022 2.8448048]]]]],[[[[[5.7237797 2.1924856 5.6122313]]]]],[[[[[8.904104 1.018796 9.466712]]]]],[[[[[ 5.845484 -0.76218015 13.805674 ]]]]],[[[[[ 1.3478925 -1.0442612 10.564959 ]]]]],2M5U,0
8,[[[[[0. 0. 0.]]]]],[[[[[ 2.1815383 1.0921854 -4.6980658]]]]],[[[[[ 7.4276114 3.0605164 -9.164961 ]]]]],[[[[[ 3.0011876 5.334844 -10.743189 ]]]]],[[[[[ -1.9035447 5.0571647 -11.853862 ]]]]],[[[[[-4.869855 3.142378 -8.576637]]]]],4PCJ,0
9,[[[[[0. 0. 0.]]]]],[[[[[ 3.0323246 3.4098723 -2.2674346]]]]],[[[[[ 3.8844934 10.167394 -6.689329 ]]]]],[[[[[ 7.0462456 6.514834 -8.438076 ]]]]],[[[[[10.476157 2.6535945 -8.175081 ]]]]],[[[[[ 8.683509 -1.1454211 -6.1606207]]]]],3E5C,0
10,[[[[[0. 0. 0.]]]]],[[[[[4.1453547 0.11495352 3.7782202 ]]]]],[[[[[11.891469 1.2981744 5.2004976]]]]],[[[[[10.517482 -2.958532 8.196037]]]]],[[[[[ 7.169651 -6.088097 10.252987]]]]],[[[[[ 2.3871691 -7.694583 7.110977 ]]]]],1N8X,0
11,[[[[[0. 0. 0.]]]]],[[[[[ 3.522296 0.753767 -4.598769]]]]],[[[[[ 6.578985 -1.4615481 -8.2507 ]]]]],[[[[[ 9.275682 -4.4741826 -15.034794 ]]]]],[[[[[ 11.754175 -5.55272 -10.116366]]]]],[[[[[ 8.983301 -5.760249 -1.6730454]]]]],5TBW,0
12,[[[[[0. 0. 0.]]]]],[[[[[ 2.921881 3.3927553 -1.9646646]]]]],[[[[[ 1.7232323 6.98591 -5.3706217]]]]],[[[[[ 7.8145223 4.8958416 -7.3492246]]]]],[[[[[ 10.756077 1.7865896 -10.887982 ]]]]],[[[[[ 9.491957 -0.7162842 -6.020857 ]]]]],1K4B,0
13,[[[[[0. 0. 0.]]]]],[[[[[-3.4002397 3.221215 -2.883709 ]]]]],[[[[[-9.921826 5.44378 -2.6653204]]]]],[[[[[-4.171551 9.843835 -5.568583]]]]],[[[[[-5.325094 12.851778 -1.016015]]]]],[[[[[-1.5698957 10.459758 2.3892636]]]]],5IEM,0
14,[[[[[0. 0. 0.]]]]],[[[[[ 1.436187 -3.6158767 -3.698961 ]]]]],[[[[[ 0.02744126 -7.804154 -8.550084 ]]]]],[[[[[ 5.1827393 -7.373542 -8.814829 ]]]]],[[[[[ 9.093543 -3.6497273 -7.7550898]]]]],[[[[[ 9.324729 0.1348033 -4.1056037]]]]],2PCV,0
15,[[[[[0. 0. 0.]]]]],[[[[[-3.4753857 -2.5530534 3.3884075]]]]],[[[[[-7.80139 -2.8196812 8.84007 ]]]]],[[[[[-5.856683 -7.480961 8.34202 ]]]]],[[[[[ -4.6962624 -11.565577 5.219216 ]]]]],[[[[[ -2.1587062 -10.295794 1.5081666]]]]],4PLX,0
16,[[[[[0. 0. 0.]]]]],[[[[[ 1.6920376 1.2679031 -5.785238 ]]]]],[[[[[ 4.9823318 4.7535615 -8.617673 ]]]]],[[[[[ 7.775089 0.7121029 -9.859068 ]]]]],[[[[[ 9.211085 -3.824872 -7.8082895]]]]],[[[[[ 6.9266195 -6.903377 -4.81322 ]]]]],1JUR,0
17,[[[[[0. 0. 0.]]]]],[[[[[-1.5932267 8.332013 -2.5340328]]]]],[[[[[ 3.6580794 2.5874114 -4.8155475]]]]],[[[[[ 9.492568 1.8321595 -7.3923817]]]]],[[[[[14.208347 -0.06424522 -5.394563 ]]]]],[[[[[9.828057 2.8186436 1.2235307]]]]],1U63,0
18,[[[[[0. 0. 0.]]]]],[[[[[ 1.5449314 -4.224141 2.6870646]]]]],[[[[[ 2.9859 -11.382388 4.4391613]]]]],[[[[[ 1.0382228 -10.283411 9.254776 ]]]]],[[[[[ 1.1315937 -6.2460847 13.114492 ]]]]],[[[[[-0.08138227 -2.391768 10.373361 ]]]]],2JSE,0
19,[[[[[0. 0. 0.]]]]],[[[[[ 2.2133045 4.6331563 -1.1209974]]]]],[[[[[ 5.0684156 11.404979 -0.51033235]]]]],[[[[[ 5.359246 10.697373 -5.6201158]]]]],[[[[[ 5.880747 6.5824513 -10.092964 ]]]]],[[[[[ 3.6728592 2.6461303 -10.1552925]]]]],2LU0,0
20,[[[[[0. 0. 0.]]]]],[[[[[ 0.1741414 5.1472917 -1.466552 ]]]]],[[[[[ 1.7010086 10.185057 -5.904903 ]]]]],[[[[[-3.1345696 11.472218 -0.5018791]]]]],[[[[[-5.5351763 10.007546 -6.561138 ]]]]],[[[[[-6.5950937 5.128483 -5.9147873]]]]],1QWA,0
21,[[[[[0. 0. 0.]]]]],[[[[[0.8114064 5.3671994 0.76951694]]]]],[[[[[-0.72292066 12.466543 -0.983001 ]]]]],[[[[[ 4.3210087 12.190811 0.47091985]]]]],[[[[[ 8.119691 10.34057 3.4459252]]]]],[[[[[8.332611 5.721991 2.8807201]]]]],1Q96,0
22,[[[[[0. 0. 0.]]]]],[[[[[ 3.5560799 2.7883987 -2.6453655]]]]],[[[[[ 9.997341 4.6355333 -3.1635149]]]]],[[[[[ 4.7909026 6.5326667 -8.14758 ]]]]],[[[[[ 8.407814 1.8248885 -10.940578 ]]]]],[[[[[ 5.0080633 -0.916469 -9.425853 ]]]]],2HW8,0
23,[[[[[0. 0. 0.]]]]],[[[[[-4.356507 7.5448236 1.6624836]]]]],[[[[[ 0.54427147 10.1128 -2.1955726 ]]]]],[[[[[ 5.22344 8.861865 -4.391129]]]]],[[[[[10.675365 4.3476753 -7.232042 ]]]]],[[[[[10.6486025 4.2104354 -1.6021109]]]]],4W90,0
24,[[[[[0. 0. 0.]]]]],[[[[[ 5.1172028 -1.3224163 -0.6744344]]]]],[[[[[ 8.848634 -2.8387482 -0.6236274]]]]],[[[[[ 9.533474 -4.989544 3.880011]]]]],[[[[[10.799891 -8.552836 7.9931297]]]]],[[[[[ 6.471106 -7.2581267 5.279246 ]]]]],4UER,0
25,[[[[[0. 0. 0.]]]]],[[[[[ 4.144762 -2.1879153 -2.0528407]]]]],[[[[[ 7.765231 0.06917286 -8.473996 ]]]]],[[[[[ 7.530019 -5.1728973 -2.8385582]]]]],[[[[[13.402426 -2.9394827 -0.6940148]]]]],[[[[[9.851795 0.11296535 1.8227459 ]]]]],3V7E,0
26,[[[[[0. 0. 0.]]]]],[[[[[ 4.015763 3.7630692 -0.58391154]]]]],[[[[[ 6.510495 10.019863 -4.0835958]]]]],[[[[[10.404858 6.2852507 -3.597763 ]]]]],[[[[[13.87188 2.5845351 -1.8958873]]]]],[[[[[10.492225 -1.2707663 -1.066926 ]]]]],3IGI,0
27,[[[[[0. 0. 0.]]]]],[[[[[-0.67687774 4.9550858 2.4509869 ]]]]],[[[[[ 0.2868786 10.421534 6.3006124]]]]],[[[[[-6.800039 7.7662554 3.0806618]]]]],[[[[[-4.6875634 13.477901 0.02192497]]]]],[[[[[-2.320022 9.637743 -3.3337574]]]]],2NCI,0
28,[[[[[0. 0. 0.]]]]],[[[[[4.4476967 2.5940402 2.0031896]]]]],[[[[[7.7883935 5.287223 7.266458 ]]]]],[[[[[9.518322 4.6145 0.54010653]]]]],[[[[[13.357318 0.77087665 2.2794933 ]]]]],[[[[[10.274188 -1.8491212 0.03866541]]]]],2CZJ,0
29,[[[[[0. 0. 0.]]]]],[[[[[-1.7199191 1.9578706 -5.2175517]]]]],[[[[[-6.0523024 6.387149 -9.093741 ]]]]],[[[[[ -6.0514765 1.6266658 -11.211388 ]]]]],[[[[[ -4.2922945 -2.819615 -13.398305 ]]]]],[[[[[-2.0290275 -5.026986 -9.462573 ]]]]],3G9C,0
30,[[[[[0. 0. 0.]]]]],[[[[[2.9325528 4.201006 1.5650347]]]]],[[[[[ 5.0430436 11.081758 1.6283066]]]]],[[[[[9.337952 8.288127 2.325546]]]]],[[[[[11.619959 4.40727 4.7433133]]]]],[[[[[ 9.701393 -0.07406108 4.514863 ]]]]],5Y7M,0
31,[[[[[0. 0. 0.]]]]],[[[[[ 0.27961087 -1.4798398 4.991447 ]]]]],[[[[[ 1.4590063 0.2072773 11.630555 ]]]]],[[[[[-0.2799412 -6.9099226 8.5652895]]]]],[[[[[-5.448218 -5.0559564 12.128038 ]]]]],[[[[[-6.711768 -3.127031 7.925332]]]]],1I6U,0
32,[[[[[0. 0. 0.]]]]],[[[[[-1.0720751 -4.338127 3.6284492]]]]],[[[[[-0.06491542 -7.4121456 6.5416946 ]]]]],[[[[[ -1.2670016 -13.280396 2.9039378]]]]],[[[[[ 6.6572523 -14.092081 2.43798 ]]]]],[[[[[ -0.39790988 -10.796235 -0.14797038]]]]],4V5O,0
33,[[[[[0. 0. 0.]]]]],[[[[[-5.629143 1.742555 3.1652732]]]]],[[[[[-4.9675016 7.171194 2.8018062]]]]],[[[[[-2.7514977 6.9903555 -1.76012 ]]]]],[[[[[-7.5074463 7.3515463 -6.2240467]]]]],[[[[[-1.8709354 5.07608 -9.567377 ]]]]],1ZBN,0
34,[[[[[0. 0. 0.]]]]],[[[[[ 5.3654594 5.8228393 -2.0932746]]]]],[[[[[ 8.78272 1.201987 -6.205616]]]]],[[[[[10.78567 -3.0974503 -4.716566 ]]]]],[[[[[12.503976 -6.0998363 -0.8871083]]]]],[[[[[ 9.060494 -6.302117 2.6118188]]]]],5UF3,0
35,[[[[[0. 0. 0.]]]]],[[[[[ 1.2225335 4.8320923 -0.3372116]]]]],[[[[[ 3.9620144 8.35824 -2.8834472]]]]],[[[[[ 7.56484 11.602406 -0.25550735]]]]],[[[[[7.998368 9.507133 3.3585553]]]]],[[[[[7.1560283 5.1719675 6.016839 ]]]]],1Z2J,0
36,[[[[[0. 0. 0.]]]]],[[[[[-2.2972324 -5.0240993 0.30986357]]]]],[[[[[ -2.8192558 -11.590214 4.1950903]]]]],[[[[[ -2.161128 -12.070811 -0.8606236]]]]],[[[[[ -4.9628935 -11.268103 -4.878889 ]]]]],[[[[[-5.276856 -6.6413445 -5.9767056]]]]],3J7P,0
37,[[[[[0. 0. 0.]]]]],[[[[[ 0.23784602 -1.8510833 5.293739 ]]]]],[[[[[ 3.7550635 -4.867634 11.008118 ]]]]],[[[[[-0.694721 -6.9614763 10.584135 ]]]]],[[[[[-5.878017 -6.7600794 9.95448 ]]]]],[[[[[-7.057581 -5.2618804 5.593775 ]]]]],5FJC,0
38,[[[[[0. 0. 0.]]]]],[[[[[ 1.256896 -4.9353127 0.60715914]]]]],[[[[[ 5.933649 -10.472454 2.3188324]]]]],[[[[[ 3.5166788 -11.567701 -1.9935789]]]]],[[[[[ -0.40189886 -11.461012 -5.2300878 ]]]]],[[[[[-2.7019167 -7.4826107 -6.612133 ]]]]],4A4S,0
39,[[[[[0. 0. 0.]]]]],[[[[[-4.908823 0.58207786 2.3863864 ]]]]],[[[[[-12.195141 0.5751297 3.4452195]]]]],[[[[[-10.326402 3.2967913 7.043878 ]]]]],[[[[[-6.68363 2.9323244 10.894603 ]]]]],[[[[[-1.8971426 2.8279965 10.229935 ]]]]],3P22,0
40,[[[[[0. 0. 0.]]]]],[[[[[-1.6437637 3.8053422 3.0609834]]]]],[[[[[-0.9066739 9.067933 6.6297593]]]]],[[[[[-7.5870247 6.685252 3.9659793]]]]],[[[[[-5.4648333 12.281635 1.2446487]]]]],[[[[[-3.2678196 9.851127 -2.3457332]]]]],2N6X,0
41,[[[[[0. 0. 0.]]]]],[[[[[-1.8631366 0.4842954 5.105202 ]]]]],[[[[[-3.7642798 -1.4136908 11.629391 ]]]]],[[[[[-6.4598355 3.066067 10.332536 ]]]]],[[[[[-5.576955 8.079649 8.721577]]]]],[[[[[-4.477625 8.562953 4.0737453]]]]],3CUL,0
42,[[[[[0. 0. 0.]]]]],[[[[[ 4.6700864 0.94945097 -2.0393653 ]]]]],[[[[[11.617462 4.297488 -0.01918197]]]]],[[[[[10.125802 4.772961 -4.9923573]]]]],[[[[[ 8.875765 3.7337708 -9.749812 ]]]]],[[[[[ 4.5997176 2.6389413 -9.140457 ]]]]],1ZIG,0
43,[[[[[0. 0. 0.]]]]],[[[[[-4.364952 -0.12355682 3.260706 ]]]]],[[[[[-11.414663 -0.27248904 4.6292276 ]]]]],[[[[[-9.4207 2.4551182 8.368152 ]]]]],[[[[[-5.579653 2.9028475 11.8917055]]]]],[[[[[-1.0826992 2.5377612 10.226369 ]]]]],4JF2,0
44,[[[[[0. 0. 0.]]]]],[[[[[ 2.3786757 4.319788 -1.255034 ]]]]],[[[[[ 3.4028652 10.172615 -4.4596624]]]]],[[[[[ 5.147479 7.1218596 -7.5206137]]]]],[[[[[ 8.263217 3.7551875 -8.788775 ]]]]],[[[[[ 9.158224 0.3072158 -5.5878296]]]]],1CQL,0
45,[[[[[0. 0. 0.]]]]],[[[[[ 2.6780841 -0.658606 4.377392 ]]]]],[[[[[ 6.283086 -0.3701228 9.019831 ]]]]],[[[[[ 0.7314091 -6.543709 11.983854 ]]]]],[[[[[-0.6608583 0.2906443 14.427138 ]]]]],[[[[[-2.51666 2.220636 10.000626]]]]],5U3G,0
46,[[[[[0. 0. 0.]]]]],[[[[[-0.00760901 -0.02235329 5.2808394 ]]]]],[[[[[ 4.5469356 -0.28623402 9.958129 ]]]]],[[[[[ 9.542906 -3.426835 15.9349785]]]]],[[[[[7.8113785 0.32033905 8.670085 ]]]]],[[[[[9.093323 0.95648706 4.84858 ]]]]],1OOA,0
47,[[[[[0. 0. 0.]]]]],[[[[[ 1.169767 5.076643 -1.9698019]]]]],[[[[[ 1.9220662 11.612395 -0.5324397]]]]],[[[[[ 2.9527514 8.892046 -7.4942474]]]]],[[[[[ 8.489534 10.036923 -4.986317]]]]],[[[[[ 8.882084 4.8308105 -3.2102327]]]]],2L2J,0
48,[[[[[0. 0. 0.]]]]],[[[[[ 2.8364363 -4.221756 -3.5412753]]]]],[[[[[ 6.166371 -6.2806096 -9.5906315]]]]],[[[[[ 1.7903731 -9.214501 -9.783133 ]]]]],[[[[[ -1.8620794 -11.5328245 -7.2901726]]]]],[[[[[-3.7991729 -9.642437 -2.2840796]]]]],1F9L,0

In [54]:
hairpins_database = hairpins_database.drop('id', axis=1)

for column in hairpins_database.columns:
    hairpins_database[column] = hairpins_database[column].apply(lambda x: ','.join(map(str, x)))
    
hairpins_database['class'] = 0
hairpins_database.to_csv("hairpins_database_C1'.csv")

In [55]:
hairpins_database_v2.to_csv("./modified_coord/hairpins_C1'.csv")

In [56]:
with open("hairpins_database_C1'_seqs.csv", 'w', newline='') as f:
     
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for item in hairpins_seqs:
        write.writerow([item])

corrected: 344 (109 above) -> class 1    PDB ID 1F9L

<h3>Internal loops</h3>

In [57]:
loops = pd.read_csv('./rnasolo-3.218-dbn-csv/loops_u.txt', sep=' ', header=None, names=['ID', 'start_1', 'end_1', 'seq_1', 'braq_1', 'start_2', 'end_2', 'seq_2', 'braq_2'])
loops['chain'] = list(map(lambda x: x.split('_')[2].rsplit('-motifs.txt:Loop')[0], loops['ID']))
loops['ID'] = list(map(lambda x: x[:x.find('_')], loops['ID']))
#loops = loops[~loops['braq_1'].str.contains('[')]
loops = loops[~loops['chain'].str.contains('-')]
loops = loops[~loops['ID'].duplicated()]
loops = loops.reset_index(drop=True)
loops

       ID  start_1  end_1 seq_1 braq_1  start_2  end_2 seq_2 braq_2 chain
0    1C2W       77     79   GUC    (.(      107    109   GGC    ).)     B
1    1C2X        8     10   CGG    (.(      110    112   CUG    ).)     C
2    1D0T        3      5   GUC    (.(       12     14   GUC    ).)     A
3    1F1T        2      4   GAC    (.(       30     32   GAC    ).)     A
4    1FYP        4      6   GUC    (.(       22     24   GUC    ).)     A
..    ...      ...    ...   ...    ...      ...    ...   ...    ...   ...
336  7R81       10     12   GAU    [.[     1113   1115   AAU    ].]    A2
337  7RQB      574    576   CCU    (.(      585    587   AUG    ).)    1A
338  7RYG      275    277   UUA    (.(      351    353   UAA    ).)     A
339  7SAM       96     98   GGC    (.(      110    112   GUC    ).)     A
340  7SC6       96     98   GGC    (.(      110    112   GUC    ).)     C

[341 rows x 10 columns]

In [58]:
stems_ids = loops['ID']
already_downloaded_ids = list(map(lambda x: x[0],motifs_ids))
same_elements = set(stems_ids).intersection(already_downloaded_ids)
different_elements = set(stems_ids).difference(already_downloaded_ids)
print(len(same_elements))
print(len(different_elements))
different_elements = list(different_elements)[:120]
loops_ids = list(same_elements) + list(different_elements)
print(len(loops_ids))


####first database
loops_ids = [
    "1C2X", "1FYP", "1JO7", "1MZP", "1P5M", "1P5P", "1RHT", "1XWU", "2GV4", "2HGH",
    "2L2J", "2LUN", "2LWK", "2N6S", "3D0U", "3IGI", "3IYR", "3J7O", "3JBV", "3RW6",
    "3V7E", "4AOB", "4P8Z", "4Y1M", "5AOX", "5B2P", "5F5F", "5F9R", "5FJC", "5O60",
    "5T7V", "5ZEY", "6B44", "6CHR", "6DU5", "6JQ6", "6O8W", "6ORD", "6Q9A", "6SGB",
    "6UZ7", "6Y2L", "6YDW", "6ZMO", "7AC7", "7AQC", "7D1A", "7JQQ", "7L0Z", "7MDZ",
    "7NSH", "7O80"
]

31
310
151

In [59]:
pdbl = PDB.PDBList()   
pdbl.download_pdb_files(loops_ids, file_format='mmCif', pdir='./mmCIF_files/')

Downloading PDB structure '1c2x'...
Structure exists: './mmCIF_files/1fyp.cif'
Downloading PDB structure '1jo7'...
Structure exists: './mmCIF_files/1mzp.cif'
Downloading PDB structure '1p5m'...
Structure exists: './mmCIF_files/1p5p.cif'
Downloading PDB structure '1rht'...
Downloading PDB structure '1xwu'...
Downloading PDB structure '2gv4'...
Downloading PDB structure '2hgh'...
Structure exists: './mmCIF_files/2l2j.cif'
Downloading PDB structure '2lun'...
Downloading PDB structure '2lwk'...
Downloading PDB structure '2n6s'...
Structure exists: './mmCIF_files/3d0u.cif'
Structure exists: './mmCIF_files/3igi.cif'
Downloading PDB structure '3iyr'...
Downloading PDB structure '3j7o'...
Structure exists: './mmCIF_files/3jbv.cif'
Structure exists: './mmCIF_files/3rw6.cif'
Structure exists: './mmCIF_files/3v7e.cif'
Structure exists: './mmCIF_files/4aob.cif'
Structure exists: './mmCIF_files/4y1m.cif'
Downloading PDB structure '4p8z'...
Downloading PDB structure '5aox'...
Structure exists: './mmCIF_files/5b2p.cif'
Downloading PDB structure '5f5f'...
Structure exists: './mmCIF_files/5f9r.cif'
Structure exists: './mmCIF_files/5fjc.cif'
Downloading PDB structure '5o60'...
Downloading PDB structure '5t7v'...
Downloading PDB structure '5zey'...
Downloading PDB structure '6b44'...
Downloading PDB structure '6chr'...
Structure exists: './mmCIF_files/6du5.cif'
Downloading PDB structure '6jq6'...
Downloading PDB structure '6o8w'...
Structure exists: './mmCIF_files/6ord.cif'
Downloading PDB structure '6q9a'...
Downloading PDB structure '6sgb'...
Downloading PDB structure '6y2l'...
Structure exists: './mmCIF_files/6uz7.cif'
Downloading PDB structure '6ydw'...
Downloading PDB structure '6zmo'...
Downloading PDB structure '7aqc'...
Structure exists: './mmCIF_files/7ac7.cif'
Downloading PDB structure '7d1a'...
Downloading PDB structure '7jqq'...
Downloading PDB structure '7l0z'...
Downloading PDB structure '7mdz'...
Downloading PDB structure '7nsh'...
Structure exists: './mmCIF_files/7o80.cif'

In [60]:
loops_complete = []
for index, row in loops.iterrows():
    if row['ID'] in loops_ids:
        if len(loops_complete) == 150:
            break
        seqs = list(range(int(row['start_1']), int(row['end_1']+1))) + list(range(int(row['start_2']), int(row['end_2']+1)))
        loops_complete.append([row['ID'], row['chain'], seqs])          

print(len(loops_complete))
loops_complete

52

[['1C2X', 'C', [8, 9, 10, 110, 111, 112]],
 ['1FYP', 'A', [4, 5, 6, 22, 23, 24]],
 ['1JO7', 'A', [2, 3, 4, 28, 29, 30]],
 ['1MZP', 'B', [4, 5, 6, 50, 51, 52]],
 ['1P5M', 'A', [25, 26, 27, 34, 35, 36]],
 ['1P5P', 'A', [25, 26, 27, 56, 57, 58]],
 ['1RHT', 'A', [3, 4, 5, 19, 20, 21]],
 ['1XWU', 'A', [4, 5, 6, 10, 11, 12]],
 ['2GV4', 'A', [5, 6, 7, 16, 17, 18]],
 ['2HGH', 'B', [30, 31, 32, 37, 38, 39]],
 ['2L2J', 'A', [4, 5, 6, 37, 38, 39]],
 ['2LUN', 'A', [4, 5, 6, 23, 24, 25]],
 ['2LWK', 'A', [8, 9, 10, 24, 25, 26]],
 ['2N6S', 'A', [14, 15, 16, 21, 22, 23]],
 ['3D0U', 'A', [112, 113, 114, 134, 135, 136]],
 ['3IGI', 'A', [162, 163, 164, 211, 212, 213]],
 ['3IYR', 'A', [58, 59, 60, 73, 74, 75]],
 ['3J7O', '7', [68, 69, 70, 105, 106, 107]],
 ['3JBV', 'W', [2, 3, 4, 69, 70, 71]],
 ['3RW6', 'H', [23, 24, 25, 32, 33, 34]],
 ['3V7E', 'C', [25, 26, 27, 98, 99, 100]],
 ['4AOB', 'A', [25, 26, 27, 66, 67, 68]],
 ['4P8Z', 'A', [49, 50, 51, 139, 140, 141]],
 ['4Y1M', 'B', [3, 4, 5, 102, 103, 104]],
 ['5AOX', 'C', [8, 9, 10, 17, 18, 19]],
 ['5B2P', 'B', [24, 25, 26, 48, 49, 50]],
 ['5F5F', 'B', [5, 6, 7, 14, 15, 16]],
 ['5F9R', 'A', [35, 36, 37, 48, 49, 50]],
 ['5FJC', 'A', [24, 25, 26, 65, 66, 67]],
 ['5O60', 'A', [655, 656, 657, 666, 667, 668]],
 ['5T7V', 'D', [5, 6, 7, 66, 67, 68]],
 ['5ZEY', 'A', [34, 35, 36, 322, 323, 324]],
 ['6B44', 'M', [46, 47, 48, 58, 59, 60]],
 ['6CHR', 'A', [85, 86, 87, 92, 93, 94]],
 ['6DU5', 'B', [3, 4, 5, 23, 24, 25]],
 ['6JQ6', 'U', [34, 35, 36, 58, 59, 60]],
 ['6O8W', 'u', [50, 51, 52, 62, 63, 64]],
 ['6ORD', 'QY', [2, 3, 4, 69, 70, 71]],
 ['6Q9A', '4', [146, 147, 148, 167, 168, 169]],
 ['6SGB', 'CA', [27, 28, 29, 265, 266, 267]],
 ['6UZ7', '3', [11, 12, 13, 22, 23, 24]],
 ['6Y2L', 'B4', [50, 51, 52, 62, 63, 64]],
 ['6YDW', 'AY', [4, 5, 6, 62, 63, 64]],
 ['6ZMO', 'CB', [5, 6, 7, 77, 78, 79]],
 ['7AC7', '4', [23, 24, 25, 328, 329, 330]],
 ['7AQC', 'T', [1, 2, 3, 70, 71, 72]],
 ['7D1A', 'A', [46, 47, 48, 59, 60, 61]],
 ['7JQQ', 'O', [12, 13, 14, 103, 104, 105]],
 ['7L0Z', 'G', [10, 11, 12, 58, 59, 60]],
 ['7MDZ', '2', [50, 51, 52, 62, 63, 64]],
 ['7NSH', 'BA', [181, 182, 183, 192, 193, 194]],
 ['7O80', 'AT', [4, 5, 6, 75, 76, 77]]]

In [61]:
loops_databse, loops_seqs = get_atom_coordinates_stem(loops_complete, "C1'", loops)

In [62]:
loops_databse_v2 = get_atom_coordinates_stem_v2(loops_complete, "C1'", loops)

In [63]:
print(loops_databse.shape)
loops_databse

(52, 7)

,N1,N2,N3,N4,N5,N6,id
0,"[38.101, 101.357, 7.09]","[40.099, 96.478, 8.875]","[41.604, 92.984, 12.931]","[44.759, 98.64, 21.488]","[47.353, 98.23, 16.584]","[47.84, 99.434, 11.176]",1C2X
1,"[-4.581, 7.929, 28.157]","[-5.474, 5.508, 24.113]","[-4.654, 3.502, 18.893]","[4.431, 7.504, 15.785]","[0.545, 9.87, 15.79]","[-3.495, 10.496, 17.866]",1FYP
2,"[1.186, -13.244, 1.643]","[1.787, -12.271, -4.349]","[-1.666, -11.078, -9.435]","[-11.236, -15.335, -5.166]","[-7.185, -19.58, -7.117]","[-2.226, -21.137, -5.123]",1JO7
3,"[12.704, 48.332, 30.378]","[14.724, 53.264, 29.54]","[16.27, 58.389, 26.535]","[24.296, 53.483, 22.251]","[22.558, 55.742, 27.709]","[20.4, 54.31, 32.3]",1MZP
4,"[-26.651, -0.351, -4.864]","[-26.909, -5.881, -7.816]","[-27.603, -11.187, -8.196]","[-19.024, -15.438, -3.324]","[-19.313, -11.758, -6.856]","[-19.79, -7.098, -9.285]",1P5M
5,"[-12.491, 24.489, -18.976]","[-13.618, 20.331, -22.239]","[-14.625, 15.196, -24.823]","[-10.45, 9.002, -17.036]","[-9.013, 12.122, -21.641]","[-6.774, 16.46, -23.112]",1P5P
6,"[1.728, -9.677, 5.786]","[-2.29, -7.309, 3.744]","[-6.768, -5.326, 2.586]","[-8.564, 4.464, 2.365]","[-7.288, 0.466, 5.316]","[-4.032, -1.692, 8.494]",1RHT
7,"[3.989, 2.224, -4.763]","[-0.769, 4.951, -4.583]","[-5.154, 6.859, -2.032]","[-6.993, 1.184, 6.768]","[-6.776, -1.965, 4.493]","[-5.376, -1.339, -0.631]",1XWU
8,"[-296.281, -15.922, 551.335]","[-291.997, -12.255, 550.66]","[-287.778, -12.226, 547.708]","[-283.386, -21.638, 545.583]","[-285.033, -19.426, 550.657]","[-286.83, -17.336, 556.793]",2GV4
9,"[-9.004, -14.948, 3.699]","[-9.328, -17.623, -2.079]","[-8.46, -22.174, -4.69]","[0.826, -26.545, -2.964]","[-1.381, -21.376, -4.354]","[-2.776, -16.083, -4.606]",2HGH
10,"[-2.472, 3.146, -23.595]","[0.166, 6.289, -19.887]","[0.546, 9.647, -15.299]","[-8.29, 10.699, -9.504]","[-6.345, 12.41, -13.865]","[-3.912, 12.67, -18.951]",2L2J
11,"[-1.877, 5.858, 1.603]","[-7.414, 3.021, -0.578]","[-8.269, -1.728, 2.804]","[-0.102, -5.316, 8.899]","[1.517, -6.518, 2.429]","[2.99, -3.168, -1.59]",2LUN
12,"[-3.389, 7.555, 10.985]","[-8.634, 6.146, 11.793]","[-13.182, 3.969, 9.825]","[-14.197, 4.761, -0.724]","[-14.326, 8.542, 3.061]","[-12.097, 11.711, 6.799]",2LWK
13,"[0.95, 13.743, -10.165]","[-1.934, 17.416, -8.535]","[-6.222, 20.329, -6.072]","[-3.327, 20.484, 3.985]","[-4.989, 16.974, 1.532]","[-5.631, 13.233, -2.068]",2N6S
14,"[19.962, 39.867, 23.975]","[16.881, 35.542, 24.28]","[12.207, 34.105, 26.758]","[5.971, 41.191, 32.191]","[10.254, 38.988, 34.502]","[15.148, 37.419, 33.332]",3D0U
15,"[-23.692, 107.564, 376.203]","[-21.66, 111.957, 373.423]","[-19.036, 113.189, 368.999]","[-12.097, 104.802, 365.283]","[-11.771, 108.155, 369.973]","[-12.357, 109.97, 374.899]",3IGI
16,"[-11.552, -80.295, 47.77]","[-9.508, -82.093, 52.35]","[-9.689, -83.189, 58.003]","[-14.942, -76.486, 62.809]","[-10.249, -76.455, 59.688]","[-5.194, -76.954, 56.047]",3IYR
17,"[268.976, 213.825, 229.511]","[273.081, 213.375, 226.452]","[276.635, 214.785, 222.064]","[273.711, 223.61, 216.643]","[272.45, 217.822, 217.182]","[270.288, 213.091, 219.03]",3J7O
18,"[159.978, 222.211, 228.11]","[161.802, 226.243, 231.085]","[164.842, 230.574, 231.018]","[173.575, 227.572, 228.055]","[170.09, 223.251, 231.256]","[167.43, 219.115, 231.134]",3JBV
19,"[8.58, -28.321, 10.103]","[4.117, -31.338, 11.44]","[0.272, -33.849, 8.465]","[-1.115, -29.348, -1.163]","[-3.707, -27.27, 3.864]","[-1.477, -25.496, 8.363]",3RW6
20,"[54.777, 5.818, -21.871]","[58.63, 2.012, -22.16]","[61.17, -2.819, -24.729]","[53.66, -8.452, -20.27]","[58.419, -5.784, -18.727]","[59.903, -1.146, -16.536]",3V7E
21,"[-1.902, 17.254, 19.704]","[-1.483, 22.277, 15.931]","[1.353, 23.836, 11.807]","[11.065, 20.437, 14.336]","[7.187, 23.462, 16.422]","[3.378, 26.24, 19.919]",4AOB
22,"[-7.352, -3.15, -22.795]","[-9.879, -7.384, -25.783]","[-12.392, -12.193, -25.292]","[-7.878, -17.435, -17.27]","[-5.49, -16.454, -22.107]","[-4.028, -12.822, -25.777]",4P8Z
23,"[43.822, 28.794, 21.142]","[38.706, 28.094, 19.656]","[34.739, 24.867, 19.108]","[38.363, 15.476, 17.449]","[37.373, 20.162, 13.733]","[39.012, 24.868, 12.705]",4Y1M
24,"[27.664, -27.473, 30.86]","[25.803, -32.323, 32.11]","[23.587, -37.089, 30.551]","[17.08, -34.764, 22.295]","[16.155, -34.396, 28.399]","[17.932, -31.282, 32.543]",5AOX
25,"[-15.301, 7.235, 5.525]","[-13.834, 9.267, 0.488]","[-13.831, 10.257, -4.587]","[-12.301, 0.33, -7.799]","[-9.279, 4.618, -5.928]","[-8.16, 7.436, -1.466]",5B2P
26,"[36.088, -7.386, 30.661]","[36.61, -8.19, 35.823]","[37.711, -6.602, 40.641]","[43.395, 2.506, 40.806]","[45.23, -1.7, 39.147]","[44.955, -6.533, 36.547]",5F5F
27,"[-12.757, -39.241, -107.736]","[-6.828, -39.549, -108.002]","[-4.178, -43.329, -109.239]","[-8.393, -50.634, -102.849]","[-4.606, -46.562, -101.344]","[-7.739, -42.785, -100.04]",5F9R
28,"[-1.321, -17.738, 19.749]","[-1.675, -22.47, 16.321]","[-3.926, -24.319, 11.6]","[-13.49, -20.038, 13.25]","[-10.419, -23.537, 15.743]","[-7.299, -26.417, 19.81]",5FJC
29,"[212.782, 199.592, 185.831]","[209.274, 200.754, 181.595]","[204.838, 200.875, 179.266]","[199.839, 192.57, 183.496]","[203.296, 194.115, 178.877]","[208.686, 194.517, 177.432]",5O60
30,"[210.391, 209.9, 151.963]","[213.587, 205.96, 152.552]","[217.423, 200.709, 149.719]","[212.492, 198.909, 138.603]","[210.41, 199.148, 144.165]","[207.798, 200.033, 148.992]",5T7V
31,"[128.356, 178.935, 174.944]","[125.814, 177.778, 170.148]","[124.777, 175.296, 165.479]","[116.318, 169.171, 169.471]","[122.138, 167.631, 168.337]","[126.332, 169.683, 171.695]",5ZEY
32,"[75.907, 60.637, 135.885]","[81.327, 57.638, 135.354]","[82.904, 52.974, 136.376]","[79.445, 50.825, 145.729]","[84.923, 56.118, 145.994]","[78.513, 58.844, 146.699]",6B44
33,"[-44.334, -65.017, 13.893]","[-40.01, -68.095, 14.473]","[-34.079, -69.461, 14.017]","[-27.048, -61.237, 15.321]","[-29.892, -62.739, 10.991]","[-34.686, -64.192, 9.113]",6CHR
34,"[39.342, 32.385, -32.429]","[44.203, 30.634, -28.88]","[48.308, 32.456, -24.132]","[50.339, 43.351, -26.514]","[51.479, 39.599, -29.702]","[50.899, 33.908, -33.538]",6DU5
35,"[-8.645, 39.667, 56.727]","[-16.986, 38.168, 56.669]","[-11.144, 33.295, 58.362]","[-1.149, 33.511, 60.56]","[4.431, 28.919, 55.263]","[-3.805, 29.815, 55.724]",6JQ6
36,"[202.988, 194.889, 259.882]","[202.117, 190.183, 261.241]","[202.072, 185.958, 264.845]","[205.284, 188.722, 274.581]","[207.969, 187.23, 270.124]","[209.71, 188.305, 264.541]",6O8W
37,"[-55.088, 99.468, 150.853]","[-57.674, 103.681, 146.831]","[-59.701, 103.197, 142.145]","[-54.518, 96.653, 134.586]","[-52.943, 102.074, 136.268]","[-51.713, 104.009, 141.6]",6ORD
38,"[253.8, 374.396, 227.53]","[253.764, 372.524, 221.164]","[247.357, 370.238, 219.629]","[240.617, 365.344, 228.18]","[246.108, 363.531, 225.761]","[252.033, 364.403, 226.084]",6Q9A
39,"[298.535, 280.572, 322.998]","[299.998, 279.808, 327.352]","[301.928, 276.098, 330.555]","[305.304, 268.429, 323.989]","[300.315, 270.03, 326.511]","[295.304, 272.102, 325.767]",6SGB
40,"[162.868, 203.216, 200.409]","[162.039, 204.64, 205.825]","[159.355, 204.374, 210.068]","[148.916, 201.936, 208.19]","[151.292, 207.969, 208.832]","[155.66, 209.746, 205.997]",6UZ7
41,"[273.963, 213.691, 204.828]","[276.335, 209.5, 207.509]","[276.462, 204.746, 209.642]","[266.603, 201.505, 211.672]","[270.397, 204.876, 214.481]","[273.551, 209.855, 214.407]",6Y2L
42,"[195.459, 264.445, 190.047]","[190.958, 261.969, 190.776]","[186.673, 263.569, 193.045]","[185.323, 266.161, 203.031]","[188.46, 261.983, 202.749]","[192.331, 261.55, 199.813]",6YDW
43,"[250.072, 169.303, 192.015]","[255.049, 171.937, 192.329]","[260.385, 172.55, 192.017]","[264.839, 162.781, 192.815]","[262.454, 166.281, 196.516]","[258.096, 168.469, 198.681]",6ZMO
44,"[208.696, 270.502, 198.812]","[208.92, 267.521, 194.364]","[207.367, 263.59, 190.833]","[200.6, 256.787, 194.996]","[206.447, 257.439, 195.138]","[210.637, 260.322, 196.96]",7AC7
45,"[195.947, 239.482, 164.937]","[191.719, 236.1, 165.288]","[185.608, 235.309, 166.31]","[184.242, 240.266, 175.394]","[187.112, 236.316, 173.425]","[192.433, 233.479, 172.935]",7AQC
46,"[132.232, 67.044, 131.805]","[128.885, 71.271, 132.292]","[123.566, 73.872, 133.869]","[117.624, 70.528, 125.996]","[121.089, 74.718, 126.562]","[127.157, 74.612, 126.266]",7D1A
47,"[143.129, 224.423, 247.356]","[144.184, 229.234, 245.365]","[146.763, 234.781, 242.871]","[156.371, 230.28, 240.799]","[153.552, 231.106, 247.53]","[150.143, 231.97, 250.813]",7JQQ
48,"[-51.09046, 3.66905, 10.12183]","[-51.44278, 3.56072, 4.67711]","[-50.99023, 4.66756, -0.50036]","[-49.22337, 15.1071, -0.15254]","[-53.34153, 10.60533, -0.36937]","[-56.67587, 7.42875, 2.29247]",7L0Z
49,"[189.404, 204.435, 192.209]","[190.749, 198.88, 191.195]","[191.122, 193.477, 192.514]","[192.743, 192.254, 202.996]","[196.841, 193.445, 198.571]","[198.131, 197.861, 194.939]",7MDZ
50,"[275.286, 271.245, 272.96]","[273.044, 273.063, 268.257]","[268.415, 272.667, 265.11]","[263.054, 263.979, 267.777]","[267.893, 265.575, 263.958]","[273.393, 266.297, 263.612]",7NSH
51,"[281.29, 274.052, 301.798]","[279.713, 270.546, 298.079]","[279.69, 265.921, 294.981]","[287.52, 257.267, 305.222]","[289.132, 257.781, 300.055]","[288.858, 260.928, 295.747]",7O80

In [64]:
loops_databse_v2

,N1,N2,N3,N4,N5,N6,id
0,[[[[[0. 0. 0.]]]]],[[[[[ 3.9369645 2.0253534 -3.3735983]]]]],[[[[[ 6.9954658 1.8274195 -8.013702 ]]]]],[[[[[ 8.062045 -8.389526 -11.119026]]]]],[[[[[10.285981 -5.9919624 -6.6188083]]]]],[[[[[ 9.8983345 -3.8792508 -1.4885626]]]]],1C2X
1,[[[[[0. 0. 0.]]]]],[[[[[4.2384396 2.1391737 0.6871562]]]]],[[[[[ 9.353357 4.199296 -0.5531506]]]]],[[[[[ 10.832678 2.0572145 -10.624694 ]]]]],[[[[[11.323257 -1.0389197 -7.327383 ]]]]],[[[[[ 9.872229 -2.4338276 -3.2076745]]]]],1FYP
2,[[[[[0. 0. 0.]]]]],[[[[[-5.979668 -1.1284903 0.42669964]]]]],[[[[[-11.010523 0.5861099 3.737968 ]]]]],[[[[[-5.125078 4.218672 12.687678]]]]],[[[[[-5.6644306 -1.928798 12.294312 ]]]]],[[[[[-3.472025 -5.6034274 8.733073 ]]]]],1JO7
3,[[[[[0. 0. 0.]]]]],[[[[[ 0.00861922 4.9040027 -2.248986 ]]]]],[[[[[ 0.6972548 9.239259 -6.5405016]]]]],[[[[[10.948248 8.914289 -5.256109]]]]],[[[[[ 5.919031 10.898003 -2.3090189]]]]],[[[[[2.4825225 9.509244 1.4388635]]]]],1MZP
4,[[[[[0. 0. 0.]]]]],[[[[[3.6892161 3.8547091 3.3004055]]]]],[[[[[5.7471027 8.591401 4.7524805]]]]],[[[[[11.922135 11.559349 -3.5219922]]]]],[[[[[11.678452 7.1051736 -1.0316354]]]]],[[[[[10.33325 2.2517262 0.54242396]]]]],1P5M
5,[[[[[0. 0. 0.]]]]],[[[[[2.426238 0.9571078 4.7332425]]]]],[[[[[5.5946083 2.8294423 9.262604 ]]]]],[[[[[12.432937 8.95887 3.5968285]]]]],[[[[[11.479122 3.546817 5.271739]]]]],[[[[[ 9.999232 -1.0475538 3.6295218]]]]],1P5P
6,[[[[[0. 0. 0.]]]]],[[[[[ 3.2465036 -0.90534973 -3.8160279 ]]]]],[[[[[ 6.543574 -2.7561004 -7.1371403]]]]],[[[[[ 4.33244 -4.549021 -16.677315]]]]],[[[[[ 3.3580873 -5.815622 -11.802177 ]]]]],[[[[[ 0.04139519 -6.2912445 -8.042986 ]]]]],1RHT
7,[[[[[0. 0. 0.]]]]],[[[[[ 3.931691 3.7720208 -0.6489651]]]]],[[[[[ 7.21455 6.865559 -3.6538188]]]]],[[[[[ 8.4549055 2.551494 -13.291139 ]]]]],[[[[[ 9.370919 -0.7426822 -11.434194 ]]]]],[[[[[ 8.907875 -0.90158933 -6.10807 ]]]]],1XWU
8,[[[[[0. 0. 0.]]]]],[[[[[ 5.408593 1.5165197 -0.8381461]]]]],[[[[[ 9.913471 -0.89440036 -0.19909024]]]]],[[[[[10.473856 -7.923416 7.7173605]]]]],[[[[[ 8.520942 -2.4889376 7.7752404]]]]],[[[[[6.088993 3.755176 8.362644]]]]],2GV4
9,[[[[[0. 0. 0.]]]]],[[[[[ 4.621832 -1.4770215 4.135572 ]]]]],[[[[[8.898694 0.51391935 6.590558 ]]]]],[[[[[15.722783 5.308111 0.36463928]]]]],[[[[[12.798107 0.31798935 0.62246466]]]]],[[[[[ 9.622799 -4.041027 -0.34798145]]]]],2HGH
10,[[[[[0. 0. 0.]]]]],[[[[[4.8816957 2.3771677 1.0511343]]]]],[[[[[10.571791 2.6480591 1.1916223]]]]],[[[[[15.77087 -5.3142724 -3.5343127]]]]],[[[[[13.244953 -4.412655 0.7709961]]]]],[[[[[ 9.292897 -2.8237584 4.473854 ]]]]],2L2J
11,[[[[[0. 0. 0.]]]]],[[[[[3.3043103 5.57512 1.2096581]]]]],[[[[[ 4.7633805 7.794361 -4.0503836]]]]],[[[[[ 4.0374293 1.444959 -12.761339 ]]]]],[[[[[ 9.161006 -0.87696934 -8.981858 ]]]]],[[[[[ 9.213974 -3.532701 -4.2396145]]]]],2LUN
12,[[[[[0. 0. 0.]]]]],[[[[[ 5.13701 -1.2971665 1.441059 ]]]]],[[[[[10.212928 -2.407982 -0.07479835]]]]],[[[[[11.051671 -6.5783334 -9.813563 ]]]]],[[[[[ 8.966099 -8.633542 -5.334131]]]]],[[[[[ 5.2323484 -9.004214 -1.4733834]]]]],2LWK
13,[[[[[0. 0. 0.]]]]],[[[[[ 0.77508366 3.9712539 -2.8449388 ]]]]],[[[[[ 2.2565238 7.3540154 -7.238245 ]]]]],[[[[[ -6.1021004 6.668318 -13.500156 ]]]]],[[[[[ -2.83145 3.5368114 -12.728109 ]]]]],[[[[[ 0.3610835 0.08143288 -10.440022 ]]]]],2N6S
14,[[[[[0. 0. 0.]]]]],[[[[[ 4.3156714 3.0210726 -0.7343811]]]]],[[[[[ 8.25873 3.545482 -4.506517]]]]],[[[[[ 8.097729 -1.7710085 -14.010497 ]]]]],[[[[[ 9.8450775 -4.167924 -9.567573 ]]]]],[[[[[ 8.855045 -4.359031 -4.394063]]]]],3D0U
15,[[[[[0. 0. 0.]]]]],[[[[[ 2.442203 0.81632257 -4.952283 ]]]]],[[[[[ 6.6584787 -0.6811495 -7.772864 ]]]]],[[[[[15.687914 -3.674374 -1.3067913]]]]],[[[[[13.208222 1.47087 -2.156837]]]]],[[[[[10.056054 5.675797 -1.6225272]]]]],3IGI
16,[[[[[0. 0. 0.]]]]],[[[[[ 4.474002 0.10989761 -2.891084 ]]]]],[[[[[ 7.7564263 -1.4014382 -7.377947 ]]]]],[[[[[ 5.9725695 -10.586758 -10.218658 ]]]]],[[[[[ 7.880239 -8.113974 -5.5269656]]]]],[[[[[ 9.803014 -4.8682466 -0.5442867]]]]],3IYR
17,[[[[[0. 0. 0.]]]]],[[[[[-0.19642156 1.9930389 -4.732874 ]]]]],[[[[[ 0.9358542 5.853255 -8.938866 ]]]]],[[[[[ 7.3731737 13.936001 -5.930928 ]]]]],[[[[[ 1.7338936 12.075104 -5.588771 ]]]]],[[[[[-2.8088455 9.4384165 -3.890776 ]]]]],3J7O
18,[[[[[0. 0. 0.]]]]],[[[[[ 1.6744152 -1.2368125 4.9093065]]]]],[[[[[ 5.948523 -1.5829619 8.010253 ]]]]],[[[[[12.014603 -7.5918384 3.4110332]]]]],[[[[[ 5.7739887 -8.6162405 2.377583 ]]]]],[[[[[ 1.9578176 -8.361614 -0.71579933]]]]],3JBV
19,[[[[[0. 0. 0.]]]]],[[[[[4.7852144 2.2049303 1.7459198]]]]],[[[[[ 9.142848 4.2329416 -0.86902905]]]]],[[[[[ 10.398455 0.07878351 -10.669415 ]]]]],[[[[[12.332369 -2.6399286 -5.65186 ]]]]],[[[[[ 9.589103 -4.274207 -1.3898659]]]]],3RW6
20,[[[[[0. 0. 0.]]]]],[[[[[-1.8460269 0.5044007 5.074695 ]]]]],[[[[[-6.1499352 -0.06211829 9.2634115 ]]]]],[[[[[-10.54937 8.379665 5.0927176]]]]],[[[[[-6.0929465 7.119126 8.363571 ]]]]],[[[[[-0.82920885 6.364149 7.8768916 ]]]]],3V7E
21,[[[[[0. 0. 0.]]]]],[[[[[ 3.2623425 0.7149813 -5.3373733]]]]],[[[[[ 8.104795 2.0925684 -6.7980742]]]]],[[[[[10.267764 10.081169 -0.18174624]]]]],[[[[[ 6.5204964 8.690137 -3.726307 ]]]]],[[[[[ 1.5509733 7.8132677 -6.724593 ]]]]],4AOB
22,[[[[[0. 0. 0.]]]]],[[[[[3.7831516 2.2189784 3.7422628]]]]],[[[[[7.6161337 6.043527 4.345427 ]]]]],[[[[[12.665765 7.0970383 -4.906524 ]]]]],[[[[[13.071078 2.7451785 -1.5961593]]]]],[[[[[10.534554 -1.1372266 1.1039801]]]]],4P8Z
23,[[[[[0. 0. 0.]]]]],[[[[[3.3391128 0.37106013 4.19336 ]]]]],[[[[[8.036425 1.5550274 5.920908 ]]]]],[[[[[14.776262 -0.03150821 -1.5713589 ]]]]],[[[[[12.271744 -3.764326 2.495682]]]]],[[[[[ 7.816535 -5.843443 3.806375]]]]],4Y1M
24,[[[[[0. 0. 0.]]]]],[[[[[0.3077078 5.308567 0.5222758]]]]],[[[[[-0.02006536 10.310134 -1.6987087 ]]]]],[[[[[ 3.593265 9.306498 -11.790525]]]]],[[[[[ 6.6420727 10.030554 -6.4585114]]]]],[[[[[ 7.653895 7.039134 -1.9802221]]]]],5AOX
25,[[[[[0. 0. 0.]]]]],[[[[[-0.94181913 -3.167551 -4.5532494 ]]]]],[[[[[-2.7244143 -6.9213905 -7.6300616]]]]],[[[[[ 1.9061251 -14.958179 -2.6129603]]]]],[[[[[ 3.2272217 -11.089193 -6.39525 ]]]]],[[[[[ 4.2163267 -5.8151393 -6.9509077]]]]],5B2P
26,[[[[[0. 0. 0.]]]]],[[[[[-0.15477097 -5.195424 0.74080086]]]]],[[[[[-1.3283786 -9.415019 3.5273209]]]]],[[[[[-2.9184685 -7.2120166 13.915254 ]]]]],[[[[[ 1.4597374 -6.831726 11.794727 ]]]]],[[[[[ 4.8576155 -5.6627054 7.6376476]]]]],5F5F
27,[[[[[0. 0. 0.]]]]],[[[[[ 2.50625 -2.6576266 4.687685 ]]]]],[[[[[ 0.4655251 -3.627779 8.899015 ]]]]],[[[[[-3.4892478 5.911163 11.20763 ]]]]],[[[[[ 2.0026412 4.266913 11.776093 ]]]]],[[[[[3.84244 5.5008903 7.2072544]]]]],5F9R
28,[[[[[0. 0. 0.]]]]],[[[[[-3.3701632 3.5168047 3.2469068]]]]],[[[[[-6.454853 8.119964 2.983761]]]]],[[[[[ 0.4688902 13.693873 -2.8052673]]]]],[[[[[ 0.5064709 11.336091 1.9200414]]]]],[[[[[1.934906 8.018539 6.5592976]]]]],5FJC
29,[[[[[0. 0. 0.]]]]],[[[[[-2.9232976 0.65413797 4.7567163 ]]]]],[[[[[-3.5592554 1.8968275 9.57006 ]]]]],[[[[[ 6.085302 0.30343127 13.607299 ]]]]],[[[[[ 0.8575368 -2.4433382 12.713546 ]]]]],[[[[[-1.8284311 -5.529235 8.897198 ]]]]],5O60
30,[[[[[0. 0. 0.]]]]],[[[[[-4.8414016 -1.1038291 -1.1946678]]]]],[[[[[-10.1045685 -1.2120402 -5.9487457]]]]],[[[[[ -6.679407 6.866765 -14.558122]]]]],[[[[[-7.2729745 6.984091 -8.64529 ]]]]],[[[[[-6.8886433 7.4645333 -3.1201398]]]]],5T7V
31,[[[[[0. 0. 0.]]]]],[[[[[-2.7423186 1.3038967 4.645602 ]]]]],[[[[[-4.802842 0.7420428 9.592693 ]]]]],[[[[[ 3.1882896 6.6852765 14.674629 ]]]]],[[[[[ 2.4006953 0.62271476 14.280941 ]]]]],[[[[[ 3.2422729 -2.036862 9.251534 ]]]]],5ZEY
32,[[[[[0. 0. 0.]]]]],[[[[[-0.25351897 3.4229214 5.1837974 ]]]]],[[[[[-0.98016727 8.299666 6.1705375 ]]]]],[[[[[ 5.1099415 13.398987 -0.23016071]]]]],[[[[[9.180515 9.702393 5.048108]]]]],[[[[[ 9.18712 6.422781 -1.1373801]]]]],6B44
33,[[[[[0. 0. 0.]]]]],[[[[[ 2.3968024 1.5847137 -4.500168 ]]]]],[[[[[ 7.152895 3.149577 -7.990358]]]]],[[[[[16.51079 -2.1290224 -6.1639633]]]]],[[[[[14.31806 2.0726228 -3.5888224]]]]],[[[[[ 9.892497 4.1061034 -1.3752506]]]]],6CHR
34,[[[[[0. 0. 0.]]]]],[[[[[ 4.4528894 -2.1656146 -3.8435159]]]]],[[[[[ 9.507448 -6.268199 -4.4218225]]]]],[[[[[14.620948 -5.504222 5.6662087]]]]],[[[[[14.062527 -1.5419229 2.5793304]]]]],[[[[[11.181053 3.0535665 -1.6653531]]]]],6DU5
35,[[[[[0. 0. 0.]]]]],[[[[[-1.8130869 8.188874 -1.2156031]]]]],[[[[[-1.4979535 2.4128225 -6.438559 ]]]]],[[[[[-1.2068095 -7.812641 -6.8032684]]]]],[[[[[ 5.7520623 -11.686736 -10.907728 ]]]]],[[[[[ 3.2062736 -3.865962 -9.811608 ]]]]],6JQ6
36,[[[[[0. 0. 0.]]]]],[[[[[ 2.796782 2.6163666 -3.175642 ]]]]],[[[[[ 5.6207037 3.3484275 -7.9012203]]]]],[[[[[ 4.9893026 -4.955596 -14.488382 ]]]]],[[[[[ 8.224247 -3.8462293 -10.292601 ]]]]],[[[[[ 9.013856 -3.0206594 -4.45722 ]]]]],6O8W
37,[[[[[0. 0. 0.]]]]],[[[[[-3.2895947 -4.9027567 -2.3989143]]]]],[[[[[-2.0324485 -9.786007 -3.3342981]]]]],[[[[[ 7.9717026 -12.072928 -7.972501 ]]]]],[[[[[ 3.1871257 -9.977915 -10.695685 ]]]]],[[[[[ 0.16783762 -5.1577377 -9.539326 ]]]]],6ORD
38,[[[[[0. 0. 0.]]]]],[[[[[-4.0222616 -0.3366007 5.2668543]]]]],[[[[[-2.4203439 4.9373918 9.538928 ]]]]],[[[[[8.737726 9.172628 9.780987]]]]],[[[[[ 6.4817934 3.506039 11.226678 ]]]]],[[[[[ 4.8156033 -1.7545743 8.877179 ]]]]],6Q9A
39,[[[[[0. 0. 0.]]]]],[[[[[-3.4521556 0.9811896 2.9666848]]]]],[[[[[-8.696904 1.2323034 3.3886275]]]]],[[[[[-12.29116 -4.315352 -4.9557004]]]]],[[[[[-10.514499 1.1108449 -3.8541567]]]]],[[[[[-6.636769 4.882871 -4.6860123]]]]],6SGB
40,[[[[[0. 0. 0.]]]]],[[[[[5.2236557 1.99348 0.88742465]]]]],[[[[[10.032719 2.4640157 -0.50152236]]]]],[[[[[13.285198 -5.708087 -6.910998]]]]],[[[[[14.039579 -5.498714 -0.44248915]]]]],[[[[[ 9.883452 -4.384006 2.9865706]]]]],6UZ7
41,[[[[[0. 0. 0.]]]]],[[[[[0.2122488 3.606043 4.162917 ]]]]],[[[[[-0.4133811 8.283889 6.3748484]]]]],[[[[[-0.69382906 15.740957 -1.1177139 ]]]]],[[[[[ 3.5827274 12.963462 1.6472868]]]]],[[[[[6.20062 7.7942066 2.7284503]]]]],6Y2L
42,[[[[[0. 0. 0.]]]]],[[[[[ 3.3791425 0.6944155 -3.8756075]]]]],[[[[[ 2.554195 1.1566753 -8.893104 ]]]]],[[[[[ -1.3894132 -5.9456434 -15.394367 ]]]]],[[[[[ 1.8121967 -8.31291 -11.999981 ]]]]],[[[[[ 1.7602726 -7.690339 -7.162442 ]]]]],6YDW
43,[[[[[0. 0. 0.]]]]],[[[[[4.9755235 1.8504941 1.904423 ]]]]],[[[[[9.164393 2.3173947 5.248303 ]]]]],[[[[[ 5.8586764 -0.67108226 15.048778 ]]]]],[[[[[ 5.0529866 3.9240403 11.9069195]]]]],[[[[[2.6188104 6.399242 7.8553967]]]]],6ZMO
44,[[[[[0. 0. 0.]]]]],[[[[[-1.6926975 -2.9178534 4.164401 ]]]]],[[[[[-2.9725914 -3.954189 9.419915 ]]]]],[[[[[ 0.73184896 3.252182 16.034231 ]]]]],[[[[[ 2.9962382 -1.4668583 13.34427 ]]]]],[[[[[ 4.663369 -3.6633284 8.69846 ]]]]],7AC7
45,[[[[[0. 0. 0.]]]]],[[[[[ 4.449054 2.66179 -1.5993513]]]]],[[[[[ 7.1928244 6.4170074 -5.7688203]]]]],[[[[[ 5.0795965 1.6009774 -14.785303 ]]]]],[[[[[ 7.461418 0.57283497 -10.204227 ]]]]],[[[[[ 8.439156 -3.1864088 -5.565934 ]]]]],7AQC
46,[[[[[0. 0. 0.]]]]],[[[[[-1.3471739 -1.5483403 5.0094843]]]]],[[[[[-0.19366288 -4.250997 10.386179 ]]]]],[[[[[ -0.9433789 -14.225589 7.484571 ]]]]],[[[[[ -4.6261034 -10.455134 8.935047 ]]]]],[[[[[-6.894974 -5.9525537 5.544107 ]]]]],7D1A
47,[[[[[0. 0. 0.]]]]],[[[[[ 3.9907322 0.2873366 -3.4948847]]]]],[[[[[ 9.36566 1.6670511 -7.079177 ]]]]],[[[[[13.554704 8.2937765 0.36423552]]]]],[[[[[ 7.2461886 9.520969 -3.189929 ]]]]],[[[[[ 3.4351456 8.441113 -5.9204473]]]]],7JQQ
48,[[[[[0. 0. 0.]]]]],[[[[[2.2349193 4.9781833 0.06055519]]]]],[[[[[ 4.7207694 9.484826 -1.2611177]]]]],[[[[[10.757982 6.1395855 -9.297794 ]]]]],[[[[[10.222073 6.9334006 -3.2682967]]]]],[[[[[9.0210705 4.8088965 1.4580077]]]]],7L0Z
49,[[[[[0. 0. 0.]]]]],[[[[[4.2639523 3.6137779 1.5666641]]]]],[[[[[7.5479126 8.076645 0.95861554]]]]],[[[[[ 9.167473 10.190265 -9.380883]]]]],[[[[[12.063097 6.144306 -5.770011]]]]],[[[[[10.797888 1.1424007 -2.9885292]]]]],7MDZ
50,[[[[[0. 0. 0.]]]]],[[[[[-4.267947 -0.98082685 3.357458 ]]]]],[[[[[-5.6039796 -1.550062 8.777702 ]]]]],[[[[[ 3.0974383 -3.6413708 14.367556 ]]]]],[[[[[-1.2125697 -6.8364115 10.937737 ]]]]],[[[[[-2.5957959 -8.623933 5.860096 ]]]]],7NSH
51,[[[[[0. 0. 0.]]]]],[[[[[4.278528 1.0754805 3.024483 ]]]]],[[[[[9.329599 2.979444 4.3848133]]]]],[[[[[10.029053 13.518522 -6.9957347]]]]],[[[[[13.926993 9.798341 -6.269885]]]]],[[[[[14.953522 4.975367 -4.214991]]]]],7O80

In [65]:
structure = parser.get_structure('1KUQ', f"./mmCIF_files/1C2X.cif")
model = structure[0]

In [66]:
loops[loops['ID'] == '1C2X']

     ID  start_1  end_1 seq_1 braq_1  start_2  end_2 seq_2 braq_2 chain
1  1C2X        8     10   CGG    (.(      110    112   CUG    ).)     C

In [67]:
chain = model['C']
res = chain[8]
print(res)
at = res["C1'"]
at.get_coord()

<Residue C het=  resseq=8 icode= >

array([ 38.101, 101.357,   7.09 ], dtype=float32)

In [68]:
loops_database = loops_databse.drop('id', axis=1)

for column in loops_database.columns:
    loops_database[column] = loops_database[column].apply(lambda x: ','.join(map(str, x)))
    
loops_database['class'] = 0
loops_database.to_csv("loops_database_C1'.csv")

In [69]:
loops_database_v22 = loops_databse_v2.drop('id', axis=1)

for column in loops_database_v22.columns:
    loops_database_v22[column] = loops_database_v22[column].apply(lambda x: ','.join(map(str,np.array(x).flatten())))
    
loops_database_v22['class'] = 0
loops_database_v22.to_csv("./modified_coord/loops_C1'.csv")

In [70]:
with open("loops_database_C1'_seqs.csv", 'w', newline='') as f:
     
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for item in loops_seqs:
        write.writerow([item])

In [71]:
loops_database

,N1,N2,N3,N4,N5,N6,class
0,"38.101,101.357,7.09","40.099,96.478,8.875","41.604,92.984,12.931","44.759,98.64,21.488","47.353,98.23,16.584","47.84,99.434,11.176",0
1,"-4.581,7.929,28.157","-5.474,5.508,24.113","-4.654,3.502,18.893","4.431,7.504,15.785","0.545,9.87,15.79","-3.495,10.496,17.866",0
2,"1.186,-13.244,1.643","1.787,-12.271,-4.349","-1.666,-11.078,-9.435","-11.236,-15.335,-5.166","-7.185,-19.58,-7.117","-2.226,-21.137,-5.123",0
3,"12.704,48.332,30.378","14.724,53.264,29.54","16.27,58.389,26.535","24.296,53.483,22.251","22.558,55.742,27.709","20.4,54.31,32.3",0
4,"-26.651,-0.351,-4.864","-26.909,-5.881,-7.816","-27.603,-11.187,-8.196","-19.024,-15.438,-3.324","-19.313,-11.758,-6.856","-19.79,-7.098,-9.285",0
5,"-12.491,24.489,-18.976","-13.618,20.331,-22.239","-14.625,15.196,-24.823","-10.45,9.002,-17.036","-9.013,12.122,-21.641","-6.774,16.46,-23.112",0
6,"1.728,-9.677,5.786","-2.29,-7.309,3.744","-6.768,-5.326,2.586","-8.564,4.464,2.365","-7.288,0.466,5.316","-4.032,-1.692,8.494",0
7,"3.989,2.224,-4.763","-0.769,4.951,-4.583","-5.154,6.859,-2.032","-6.993,1.184,6.768","-6.776,-1.965,4.493","-5.376,-1.339,-0.631",0
8,"-296.281,-15.922,551.335","-291.997,-12.255,550.66","-287.778,-12.226,547.708","-283.386,-21.638,545.583","-285.033,-19.426,550.657","-286.83,-17.336,556.793",0
9,"-9.004,-14.948,3.699","-9.328,-17.623,-2.079","-8.46,-22.174,-4.69","0.826,-26.545,-2.964","-1.381,-21.376,-4.354","-2.776,-16.083,-4.606",0
10,"-2.472,3.146,-23.595","0.166,6.289,-19.887","0.546,9.647,-15.299","-8.29,10.699,-9.504","-6.345,12.41,-13.865","-3.912,12.67,-18.951",0
11,"-1.877,5.858,1.603","-7.414,3.021,-0.578","-8.269,-1.728,2.804","-0.102,-5.316,8.899","1.517,-6.518,2.429","2.99,-3.168,-1.59",0
12,"-3.389,7.555,10.985","-8.634,6.146,11.793","-13.182,3.969,9.825","-14.197,4.761,-0.724","-14.326,8.542,3.061","-12.097,11.711,6.799",0
13,"0.95,13.743,-10.165","-1.934,17.416,-8.535","-6.222,20.329,-6.072","-3.327,20.484,3.985","-4.989,16.974,1.532","-5.631,13.233,-2.068",0
14,"19.962,39.867,23.975","16.881,35.542,24.28","12.207,34.105,26.758","5.971,41.191,32.191","10.254,38.988,34.502","15.148,37.419,33.332",0
15,"-23.692,107.564,376.203","-21.66,111.957,373.423","-19.036,113.189,368.999","-12.097,104.802,365.283","-11.771,108.155,369.973","-12.357,109.97,374.899",0
16,"-11.552,-80.295,47.77","-9.508,-82.093,52.35","-9.689,-83.189,58.003","-14.942,-76.486,62.809","-10.249,-76.455,59.688","-5.194,-76.954,56.047",0
17,"268.976,213.825,229.511","273.081,213.375,226.452","276.635,214.785,222.064","273.711,223.61,216.643","272.45,217.822,217.182","270.288,213.091,219.03",0
18,"159.978,222.211,228.11","161.802,226.243,231.085","164.842,230.574,231.018","173.575,227.572,228.055","170.09,223.251,231.256","167.43,219.115,231.134",0
19,"8.58,-28.321,10.103","4.117,-31.338,11.44","0.272,-33.849,8.465","-1.115,-29.348,-1.163","-3.707,-27.27,3.864","-1.477,-25.496,8.363",0
20,"54.777,5.818,-21.871","58.63,2.012,-22.16","61.17,-2.819,-24.729","53.66,-8.452,-20.27","58.419,-5.784,-18.727","59.903,-1.146,-16.536",0
21,"-1.902,17.254,19.704","-1.483,22.277,15.931","1.353,23.836,11.807","11.065,20.437,14.336","7.187,23.462,16.422","3.378,26.24,19.919",0
22,"-7.352,-3.15,-22.795","-9.879,-7.384,-25.783","-12.392,-12.193,-25.292","-7.878,-17.435,-17.27","-5.49,-16.454,-22.107","-4.028,-12.822,-25.777",0
23,"43.822,28.794,21.142","38.706,28.094,19.656","34.739,24.867,19.108","38.363,15.476,17.449","37.373,20.162,13.733","39.012,24.868,12.705",0
24,"27.664,-27.473,30.86","25.803,-32.323,32.11","23.587,-37.089,30.551","17.08,-34.764,22.295","16.155,-34.396,28.399","17.932,-31.282,32.543",0
25,"-15.301,7.235,5.525","-13.834,9.267,0.488","-13.831,10.257,-4.587","-12.301,0.33,-7.799","-9.279,4.618,-5.928","-8.16,7.436,-1.466",0
26,"36.088,-7.386,30.661","36.61,-8.19,35.823","37.711,-6.602,40.641","43.395,2.506,40.806","45.23,-1.7,39.147","44.955,-6.533,36.547",0
27,"-12.757,-39.241,-107.736","-6.828,-39.549,-108.002","-4.178,-43.329,-109.239","-8.393,-50.634,-102.849","-4.606,-46.562,-101.344","-7.739,-42.785,-100.04",0
28,"-1.321,-17.738,19.749","-1.675,-22.47,16.321","-3.926,-24.319,11.6","-13.49,-20.038,13.25","-10.419,-23.537,15.743","-7.299,-26.417,19.81",0
29,"212.782,199.592,185.831","209.274,200.754,181.595","204.838,200.875,179.266","199.839,192.57,183.496","203.296,194.115,178.877","208.686,194.517,177.432",0
30,"210.391,209.9,151.963","213.587,205.96,152.552","217.423,200.709,149.719","212.492,198.909,138.603","210.41,199.148,144.165","207.798,200.033,148.992",0
31,"128.356,178.935,174.944","125.814,177.778,170.148","124.777,175.296,165.479","116.318,169.171,169.471","122.138,167.631,168.337","126.332,169.683,171.695",0
32,"75.907,60.637,135.885","81.327,57.638,135.354","82.904,52.974,136.376","79.445,50.825,145.729","84.923,56.118,145.994","78.513,58.844,146.699",0
33,"-44.334,-65.017,13.893","-40.01,-68.095,14.473","-34.079,-69.461,14.017","-27.048,-61.237,15.321","-29.892,-62.739,10.991","-34.686,-64.192,9.113",0
34,"39.342,32.385,-32.429","44.203,30.634,-28.88","48.308,32.456,-24.132","50.339,43.351,-26.514","51.479,39.599,-29.702","50.899,33.908,-33.538",0
35,"-8.645,39.667,56.727","-16.986,38.168,56.669","-11.144,33.295,58.362","-1.149,33.511,60.56","4.431,28.919,55.263","-3.805,29.815,55.724",0
36,"202.988,194.889,259.882","202.117,190.183,261.241","202.072,185.958,264.845","205.284,188.722,274.581","207.969,187.23,270.124","209.71,188.305,264.541",0
37,"-55.088,99.468,150.853","-57.674,103.681,146.831","-59.701,103.197,142.145","-54.518,96.653,134.586","-52.943,102.074,136.268","-51.713,104.009,141.6",0
38,"253.8,374.396,227.53","253.764,372.524,221.164","247.357,370.238,219.629","240.617,365.344,228.18","246.108,363.531,225.761","252.033,364.403,226.084",0
39,"298.535,280.572,322.998","299.998,279.808,327.352","301.928,276.098,330.555","305.304,268.429,323.989","300.315,270.03,326.511","295.304,272.102,325.767",0
40,"162.868,203.216,200.409","162.039,204.64,205.825","159.355,204.374,210.068","148.916,201.936,208.19","151.292,207.969,208.832","155.66,209.746,205.997",0
41,"273.963,213.691,204.828","276.335,209.5,207.509","276.462,204.746,209.642","266.603,201.505,211.672","270.397,204.876,214.481","273.551,209.855,214.407",0
42,"195.459,264.445,190.047","190.958,261.969,190.776","186.673,263.569,193.045","185.323,266.161,203.031","188.46,261.983,202.749","192.331,261.55,199.813",0
43,"250.072,169.303,192.015","255.049,171.937,192.329","260.385,172.55,192.017","264.839,162.781,192.815","262.454,166.281,196.516","258.096,168.469,198.681",0
44,"208.696,270.502,198.812","208.92,267.521,194.364","207.367,263.59,190.833","200.6,256.787,194.996","206.447,257.439,195.138","210.637,260.322,196.96",0
45,"195.947,239.482,164.937","191.719,236.1,165.288","185.608,235.309,166.31","184.242,240.266,175.394","187.112,236.316,173.425","192.433,233.479,172.935",0
46,"132.232,67.044,131.805","128.885,71.271,132.292","123.566,73.872,133.869","117.624,70.528,125.996","121.089,74.718,126.562","127.157,74.612,126.266",0
47,"143.129,224.423,247.356","144.184,229.234,245.365","146.763,234.781,242.871","156.371,230.28,240.799","153.552,231.106,247.53","150.143,231.97,250.813",0
48,"-51.09046,3.66905,10.12183","-51.44278,3.56072,4.67711","-50.99023,4.66756,-0.50036","-49.22337,15.1071,-0.15254","-53.34153,10.60533,-0.36937","-56.67587,7.42875,2.29247",0
49,"189.404,204.435,192.209","190.749,198.88,191.195","191.122,193.477,192.514","192.743,192.254,202.996","196.841,193.445,198.571","198.131,197.861,194.939",0
50,"275.286,271.245,272.96","273.044,273.063,268.257","268.415,272.667,265.11","263.054,263.979,267.777","267.893,265.575,263.958","273.393,266.297,263.612",0
51,"281.29,274.052,301.798","279.713,270.546,298.079","279.69,265.921,294.981","287.52,257.267,305.222","289.132,257.781,300.055","288.858,260.928,295.747",0

<h3>Single ends</h3>

In [72]:
ends = pd.read_csv('./rnasolo-3.218-dbn-csv/single_ends.txt', sep=' ', header=None, names=['ID', 'start', 'end', 'seq', 'braq'])
ends['chain'] = list(map(lambda x: x.split('_')[2].rsplit('-motifs.txt:SingleStrand3p')[0], ends['ID']))
ends.loc[ends['chain'].str.len() > 6, 'chain']  = ends[ends['chain'].str.len() > 6 ]['chain'].map(lambda x: x[:x.find('-')])
ends['ID'] = list(map(lambda x: x[:x.find('_')], ends['ID']))
ends = ends[~ends['chain'].str.contains('-')]
#ends = ends[~ends['ID'].duplicated()]
ends = ends.reset_index(drop=True)
ends

      ID  start  end     seq    braq chain
0   1F7U     59   64  AAGCCA  ).....     B
1   1KXK      1    6  GUCUAC  .....(     A
2   1QTQ     69   74  CAGCCA  ).....     B
3   1XOK     22   27  GCCCCU  ).....     A
4   2R8S      1    6  GGAAUU  .....(     R
..   ...    ...  ...     ...     ...   ...
77  7NHM     72   77  CAACCA  ).....     D
78  7NWI     71   76  ACACCA  ).....     2
79  7OGM     44   49  UUUUUU  ).....     P
80  7OSM     70   75  GCACCA  ).....  ASIT
81  7PLA      1    6  UAAUAG  .....(     B

[82 rows x 6 columns]

In [73]:
pdbl = PDB.PDBList()   
pdbl.download_pdb_files(ends['ID'], file_format='mmCif', pdir='./mmCIF_files/')

Downloading PDB structure '1f7u'...
Structure exists: './mmCIF_files/1kxk.cif'
Downloading PDB structure '1qtq'...
Downloading PDB structure '1xok'...
Structure exists: './mmCIF_files/2r8s.cif'
Downloading PDB structure '3dkn'...
Downloading PDB structure '3j0l'...
Downloading PDB structure '3j16'...
Downloading PDB structure '3j0p'...
Downloading PDB structure '3j5s'...
Downloading PDB structure '3j92'...
Downloading PDB structure '3trz'...
Downloading PDB structure '3ts2'...
Downloading PDB structure '3ts2'...
Downloading PDB structure '3zn8'...
Downloading PDB structure '4ato'...
Downloading PDB structure '4ato'...
Structure exists: './mmCIF_files/4enc.cif'
Downloading PDB structure '4ilm'...
Downloading PDB structure '4jxz'...
Downloading PDB structure '4k4u'...
Downloading PDB structure '4qoz'...
Downloading PDB structure '4qoz'...
Downloading PDB structure '4tue'...
Downloading PDB structure '4tuw'...
Downloading PDB structure '4v4b'...
Downloading PDB structure '4v4r'...
Downloading PDB structure '4v5g'...
Structure exists: './mmCIF_files/4v8m.cif'
Structure exists: './mmCIF_files/4v8m.cif'
Downloading PDB structure '4v8n'...
Structure exists: './mmCIF_files/4v9f.cif'
Structure exists: './mmCIF_files/4v9f.cif'
Downloading PDB structure '4v9q'...
Downloading PDB structure '4wt8'...
Downloading PDB structure '5bkl'...
Downloading PDB structure '5e6m'...
Downloading PDB structure '5e81'...
Downloading PDB structure '5e81'...
Downloading PDB structure '5it9'...
Structure exists: './mmCIF_files/5j7l.cif'
Downloading PDB structure '5k36'...
Downloading PDB structure '5myj'...
Downloading PDB structure '5nfv'...
Downloading PDB structure '5v93'...
Downloading PDB structure '5w1h'...
Downloading PDB structure '5xwy'...
Downloading PDB structure '5xyi'...
Downloading PDB structure '6cfj'...
Structure exists: './mmCIF_files/6czr.cif'
Downloading PDB structure '6d6v'...
Downloading PDB structure '6hiw'...
Downloading PDB structure '6htq'...
Downloading PDB structure '6k0b'...
Downloading PDB structure '6okk'...
Downloading PDB structure '6om6'...
Downloading PDB structure '6p5n'...
Downloading PDB structure '6pmo'...
Structure exists: './mmCIF_files/6q9a.cif'
Downloading PDB structure '6s0x'...
Downloading PDB structure '6szv'...
Downloading PDB structure '6t0v'...
Downloading PDB structure '6t2c'...
Downloading PDB structure '6ty9'...
Structure exists: './mmCIF_files/6uz7.cif'
Downloading PDB structure '6w2t'...
Downloading PDB structure '6xyw'...
Structure exists: './mmCIF_files/6y2l.cif'
Downloading PDB structure '6zmw'...
Downloading PDB structure '6zvi'...
Downloading PDB structure '7ane'...
Structure exists: './mmCIF_files/7d1a.cif'
Downloading PDB structure '7el1'...
Downloading PDB structure '7k4l'...
Downloading PDB structure '7kjt'...
Downloading PDB structure '7lma'...
Downloading PDB structure '7lv0'...
Downloading PDB structure '7nhm'...
Downloading PDB structure '7nwi'...
Downloading PDB structure '7ogm'...
Downloading PDB structure '7osm'...
Downloading PDB structure '7pla'...

In [74]:
ends_complete = []
for index, row in ends.iterrows():
    seqs = list(range(int(row['start']), int(row['end']+1)))
    ends_complete.append([row['ID'], row['chain'], seqs])

print(len(ends_complete))
ends_complete

82

[['1F7U', 'B', [59, 60, 61, 62, 63, 64]],
 ['1KXK', 'A', [1, 2, 3, 4, 5, 6]],
 ['1QTQ', 'B', [69, 70, 71, 72, 73, 74]],
 ['1XOK', 'A', [22, 23, 24, 25, 26, 27]],
 ['2R8S', 'R', [1, 2, 3, 4, 5, 6]],
 ['3DKN', 'F', [1, 2, 3, 4, 5, 6]],
 ['3J0L', '1', [45, 46, 47, 48, 49, 50]],
 ['3J0P', 'W', [72, 73, 74, 75, 76, 77]],
 ['3J16', 'J', [1, 2, 3, 4, 5, 6]],
 ['3J5S', 'B', [1, 2, 3, 4, 5, 6]],
 ['3J92', '2', [69, 70, 71, 72, 73, 74]],
 ['3TRZ', 'U', [15, 16, 17, 18, 19, 20]],
 ['3TS2', 'U', [18, 19, 20, 21, 22, 23]],
 ['3TS2', 'V', [18, 19, 20, 21, 22, 23]],
 ['3ZN8', 'G', [83, 84, 85, 86, 87, 88]],
 ['4ATO', 'G', [1, 2, 3, 4, 5, 6]],
 ['4ATO', 'G', [28, 29, 30, 31, 32, 33]],
 ['4ENC', 'A', [47, 48, 49, 50, 51, 52]],
 ['4ILM', 'C', [1, 2, 3, 4, 5, 6]],
 ['4JXZ', 'B', [66, 67, 68, 69, 70, 71]],
 ['4K4U', 'B', [1, 2, 3, 4, 5, 6]],
 ['4QOZ', 'A', [1, 2, 3, 4, 5, 6]],
 ['4QOZ', 'A', [21, 22, 23, 24, 25, 26]],
 ['4TUE', 'QV', [72, 73, 74, 75, 76, 77]],
 ['4TUW', 'C', [23, 24, 25, 26, 27, 28]],
 ['4V4B', 'AA', [1461, 1462, 1463, 1464, 1465, 1466]],
 ['4V4R', 'AV', [71, 72, 73, 74, 75, 76]],
 ['4V5G', 'AY', [64, 65, 66, 67, 68, 69]],
 ['4V8M', 'BH', [1, 2, 3, 4, 5, 6]],
 ['4V8M', 'BH', [130, 131, 132, 133, 134, 135]],
 ['4V8N', 'CV', [72, 73, 74, 75, 76, 77]],
 ['4V9F', '0', [1, 2, 3, 4, 5, 6]],
 ['4V9F', '0', [2798, 2799, 2800, 2801, 2802, 2803]],
 ['4V9Q', 'DV', [72, 73, 74, 75, 76, 77]],
 ['4WT8', 'D4', [71, 72, 73, 74, 75, 76]],
 ['5BKL', 'bb', [1, 2, 3, 4, 5, 6]],
 ['5E6M', 'C', [68, 69, 70, 71, 72, 73]],
 ['5E81', '2K', [67, 68, 69, 70, 71, 72]],
 ['5E81', '3L', [67, 68, 69, 70, 71, 72]],
 ['5IT9', 'i', [187, 188, 189, 190, 191, 192]],
 ['5J7L', 'AA', [1518, 1519, 1520, 1521, 1522, 1523]],
 ['5K36', 'L', [12, 13, 14, 15, 16, 17]],
 ['5MYJ', 'AA', [1530, 1531, 1532, 1533, 1534, 1535]],
 ['5NFV', 'B', [1, 2, 3, 4, 5, 6]],
 ['5V93', 'a', [1514, 1515, 1516, 1517, 1518, 1519]],
 ['5W1H', 'B', [1, 2, 3, 4, 5, 6]],
 ['5XWY', 'B', [1, 2, 3, 4, 5, 6]],
 ['5XYI', '2', [1485, 1486, 1487, 1488, 1489, 1490]],
 ['6CFJ', '1x', [67, 68, 69, 70, 71, 72]],
 ['6CZR', '1a', [1, 2, 3, 4, 5, 6]],
 ['6D6V', 'B', [154, 155, 156, 157, 158, 159]],
 ['6HIW', 'CA', [616, 617, 618, 619, 620, 621]],
 ['6HTQ', 'w', [70, 71, 72, 73, 74, 75]],
 ['6K0B', 'X', [253, 254, 255, 256, 257, 258]],
 ['6OKK', 'g', [69, 70, 71, 72, 73, 74]],
 ['6OM6', '5', [69, 70, 71, 72, 73, 74]],
 ['6P5N', '1', [202, 203, 204, 205, 206, 207]],
 ['6PMO', 'A', [1, 2, 3, 4, 5, 6]],
 ['6Q9A', '7', [71, 72, 73, 74, 75, 76]],
 ['6S0X', 'a', [1, 2, 3, 4, 5, 6]],
 ['6SZV', 'V', [9, 10, 11, 12, 13, 14]],
 ['6T0V', 'V', [9, 10, 11, 12, 13, 14]],
 ['6T2C', 'V', [24, 25, 26, 27, 28, 29]],
 ['6TY9', 'T', [1, 2, 3, 4, 5, 6]],
 ['6UZ7', '3', [71, 72, 73, 74, 75, 76]],
 ['6W2T', 'A', [334, 335, 336, 337, 338, 339]],
 ['6XYW', '1', [2837, 2838, 2839, 2840, 2841, 2842]],
 ['6Y2L', 'B4', [71, 72, 73, 74, 75, 76]],
 ['6ZMW', 'w', [70, 71, 72, 73, 74, 75]],
 ['6ZVI', 'e', [72, 73, 74, 75, 76, 77]],
 ['7ANE', '2', [599, 600, 601, 602, 603, 604]],
 ['7D1A', 'A', [1, 2, 3, 4, 5, 6]],
 ['7EL1', 'B', [67, 68, 69, 70, 71, 72]],
 ['7K4L', 'A', [1, 2, 3, 4, 5, 6]],
 ['7KJT', 'A', [65, 66, 67, 68, 69, 70]],
 ['7LMA', 'B', [151, 152, 153, 154, 155, 156]],
 ['7LV0', '5', [72, 73, 74, 75, 76, 77]],
 ['7NHM', 'D', [72, 73, 74, 75, 76, 77]],
 ['7NWI', '2', [71, 72, 73, 74, 75, 76]],
 ['7OGM', 'P', [44, 45, 46, 47, 48, 49]],
 ['7OSM', 'ASIT', [70, 71, 72, 73, 74, 75]],
 ['7PLA', 'B', [1, 2, 3, 4, 5, 6]]]

In [75]:
ends_databse, ends_seqs = get_atom_coordinates_hairpins(ends_complete, "C1'", ends)

In [76]:
ends_databse, ends_seqs = get_atom_coordinates_hairpins(ends_complete, "C1'", ends)

In [77]:
print(ends_databse.shape)
ends_databse

(28, 7)

,N1,N2,N3,N4,N5,N6,id
1,[[[[[0. 0. 0.]]]]],[[[[[4.7392836 1.6047585 0.3247044]]]]],[[[[[ 9.301666 4.043298 -0.6491785]]]]],[[[[[11.785527 7.5683985 -3.2119083]]]]],[[[[[13.804838 9.696486 -8.285176]]]]],[[[[[11.400997 13.94923 -9.538257]]]]],1KXK
15,[[[[[0. 0. 0.]]]]],[[[[[-2.6993585e+00 -4.6278558e+00 -3.2709837e...,[[[[[-2.296773 -9.943279 -1.3772607]]]]],[[[[[ 2.5057361e+00 -1.4523361e+01 -1.3960838e...,[[[[[ -0.3371731 -21.187784 -1.543951 ]]]]],[[[[[ 2.2402074 -25.474472 -1.1554918]]]]],4ATO
17,[[[[[0. 0. 0.]]]]],[[[[[ 3.9674602 3.7266514 -0.15177464]]]]],[[[[[ 6.7623878 7.953205 -2.7240477]]]]],[[[[[ 5.7517066 11.717857 -6.6278057]]]]],[[[[[ 6.6940002 19.982117 -7.426035 ]]]]],[[[[[ 1.0052726 17.040554 -8.105388 ]]]]],4ENC
18,[[[[[0. 0. 0.]]]]],[[[[[4.4171324 0.08777595 3.9546573 ]]]]],[[[[[6.3533916 5.0112076 8.572324 ]]]]],[[[[[10.582216 3.3232284 15.867943 ]]]]],[[[[[15.360696 3.1921291 15.542921 ]]]]],[[[[[21.416489 0.47280788 17.979017 ]]]]],4ILM
21,[[[[[0. 0. 0.]]]]],[[[[[0.4363533 4.282511 2.8982973]]]]],[[[[[2.700162 8.812694 3.750507]]]]],[[[[[ 5.0236855 13.131694 1.0604465]]]]],[[[[[ 4.889003 16.053795 -3.28165 ]]]]],[[[[[ 4.1028686 22.8459 -8.226617 ]]]]],4QOZ
24,[[[[[0. 0. 0.]]]]],[[[[[-0.11005095 -2.9451692 4.237674 ]]]]],[[[[[ 1.6605628 -7.2839336 7.2457314]]]]],[[[[[ 6.5709705 -10.129158 7.8612366]]]]],[[[[[ 11.671274 -10.051995 8.738542]]]]],[[[[[11.217145 -4.5850854 12.720346 ]]]]],4TUW
26,[[[[[0. 0. 0.]]]]],[[[[[ 5.5932193 -0.46163952 -0.9843978 ]]]]],[[[[[9.9222355 1.0104154 0.66989076]]]]],[[[[[13.523029 -4.981833 3.591352]]]]],[[[[[19.561628 -8.743424 3.513214]]]]],[[[[[24.479202 -7.684703 5.1691885]]]]],4V4R
28,[[[[[0. 0. 0.]]]]],[[[[[-5.649952 0.08372605 3.7145052 ]]]]],[[[[[-7.677737 4.01614 2.209635]]]]],[[[[[-10.853732 8.013066 2.005413]]]]],[[[[[-11.2384 12.243876 -0.41678762]]]]],[[[[[-10.337126 14.403427 -4.621217]]]]],4V8M
34,[[[[[0. 0. 0.]]]]],[[[[[-4.8347416 3.5165513 -0.07206714]]]]],[[[[[-9.227182 5.999819 -1.5242133]]]]],[[[[[-14.440483 2.202835 2.983201]]]]],[[[[[-20.103237 1.979733 4.9295535]]]]],[[[[[-25.078999 2.5314698 4.1350956]]]]],4WT8
41,[[[[[0. 0. 0.]]]]],[[[[[-2.5640314 -7.415701 3.3087695]]]]],[[[[[-7.985015 -5.0667133 9.691292 ]]]]],[[[[[ -9.503412 -10.909735 7.026582]]]]],[[[[[-10.8685255 -15.758442 10.6258955]]]]],[[[[[-12.017687 -17.079185 16.020657]]]]],5K36
46,[[[[[0. 0. 0.]]]]],[[[[[-5.4285297 0.27897537 -1.8964052 ]]]]],[[[[[-8.978109 5.2000995 1.2864428]]]]],[[[[[-14.043205 6.5605783 -0.07922077]]]]],[[[[[-16.7309 1.3830068 0.95607185]]]]],[[[[[-14.611994 3.157785 9.316658]]]]],5XWY
50,[[[[[0. 0. 0.]]]]],[[[[[-6.8171773 -4.5826087 0.3692264]]]]],[[[[[-10.961857 -1.900209 -7.6682773]]]]],[[[[[-11.505335 -6.115375 -1.0097982]]]]],[[[[[-13.558575 -9.6015415 1.6981727]]]]],[[[[[-5.5331154 -8.91588 -0.9280007]]]]],6D6V
51,[[[[[0. 0. 0.]]]]],[[[[[ 3.5464623 -2.4165993 4.107751 ]]]]],[[[[[10.169506 1.1072612 10.399937 ]]]]],[[[[[10.694972 -6.002014 14.590964]]]]],[[[[[15.236248 -0.65792507 18.699871 ]]]]],[[[[[18.81351 2.740355 12.699826]]]]],6HIW
54,[[[[[0. 0. 0.]]]]],[[[[[-1.5562817 -5.2303724 -0.40726772]]]]],[[[[[-5.0258617 -8.135008 -3.8161998]]]]],[[[[[-7.611704 -9.631033 -8.078852]]]]],[[[[[-11.799381 -17.588312 -9.525653]]]]],[[[[[-17.569212 -14.775775 -14.588478]]]]],6OKK
55,[[[[[0. 0. 0.]]]]],[[[[[4.5732646 2.5937736 0.39710426]]]]],[[[[[ 7.9842005 7.3770323 -1.2282898]]]]],[[[[[8.937556 9.431403 5.71579 ]]]]],[[[[[12.041223 13.55471 10.471947]]]]],[[[[[13.309862 18.778389 10.258316]]]]],6OM6
58,[[[[[0. 0. 0.]]]]],[[[[[ 0.7738962 2.4126563 -4.846445 ]]]]],[[[[[ 1.9130331 2.5839796 -10.011283 ]]]]],[[[[[ -3.6748724 7.3105025 -11.540256 ]]]]],[[[[[ -5.249647 12.377535 -15.899076]]]]],[[[[[ -6.3007927 12.619062 -20.883183 ]]]]],6Q9A
60,[[[[[0. 0. 0.]]]]],[[[[[ 3.365078 3.215941 -1.9957255]]]]],[[[[[-1.664123 9.288926 1.5654554]]]]],[[[[[-6.423154 11.732423 0.6677828]]]]],[[[[[-13.823707 7.400654 2.3603392]]]]],[[[[[-10.661161 3.4195323 7.3750424]]]]],6SZV
61,[[[[[0. 0. 0.]]]]],[[[[[ 3.2125645 3.4098616 -1.8305626]]]]],[[[[[-1.8512259 8.984746 2.0997486]]]]],[[[[[-6.946838 11.14159 0.7793231]]]]],[[[[[-13.788456 6.062044 2.2688837]]]]],[[[[[-11.063946 2.3682368 7.269955 ]]]]],6T0V
64,[[[[[0. 0. 0.]]]]],[[[[[-4.3480873 3.807314 2.0543764]]]]],[[[[[-8.409418 6.0626554 -0.9874706]]]]],[[[[[-13.470207 5.3834476 -3.9440832]]]]],[[[[[-21.095362 9.86759 -5.7581224]]]]],[[[[[-20.736652 10.869913 -13.28603 ]]]]],6UZ7
67,[[[[[0. 0. 0.]]]]],[[[[[-3.3472435 -3.026158 3.6686306]]]]],[[[[[-5.5044327 -3.3815162 8.000416 ]]]]],[[[[[-12.458981 -4.359601 6.8542438]]]]],[[[[[-17.859732 -7.175166 8.949301]]]]],[[[[[-20.159586 -5.7147975 13.582968 ]]]]],6Y2L
68,[[[[[0. 0. 0.]]]]],[[[[[ 2.0516284 -5.761902 0.44727677]]]]],[[[[[ 2.4035025 -10.784292 2.6946318]]]]],[[[[[ 4.3477435 -14.915492 5.5581913]]]]],[[[[[ 7.7164125 -16.60353 7.6318903]]]]],[[[[[ 12.607513 -15.98263 10.149201]]]]],6ZMW
69,[[[[[0. 0. 0.]]]]],[[[[[2.5376186 4.036087 1.6050746]]]]],[[[[[6.625713 8.49572 1.6050525]]]]],[[[[[ 7.810256 11.402888 -2.560935]]]]],[[[[[12.18489 19.542282 -2.5227072]]]]],[[[[[15.703356 20.164766 -9.4875 ]]]]],6ZVI
71,[[[[[0. 0. 0.]]]]],[[[[[-7.8961205 -0.19844861 -0.09738151]]]]],[[[[[-11.562883 1.346351 -7.7750874]]]]],[[[[[-11.04253 6.6850996 -7.5973306]]]]],[[[[[-9.404783 10.374036 -3.3181443]]]]],[[[[[-3.5884657 15.246567 -4.013546 ]]]]],7D1A
72,[[[[[0. 0. 0.]]]]],[[[[[ 3.7663243 4.2935166 -0.11479306]]]]],[[[[[ 3.813916 12.760635 0.67559767]]]]],[[[[[-1.8050342 13.496552 6.4532924]]]]],[[[[[-2.8424938 13.610335 11.657376 ]]]]],[[[[[-1.5851865 12.108632 16.707664 ]]]]],7EL1
73,[[[[[0. 0. 0.]]]]],[[[[[ 4.006945 -0.18098092 5.7341237 ]]]]],[[[[[ 5.286071 -0.9914228 11.0982485]]]]],[[[[[ 5.0029964 -0.371997 16.401855 ]]]]],[[[[[ 3.1708794 -2.437755 23.860062 ]]]]],[[[[[ 4.5702424 2.5906692 25.955273 ]]]]],7K4L
77,[[[[[0. 0. 0.]]]]],[[[[[ 0.04408479 4.8187447 -2.322442 ]]]]],[[[[[-2.6228404 9.435992 -2.6779454]]]]],[[[[[ 3.8060286 13.80798 -2.4268074]]]]],[[[[[ 6.2041464 19.51902 -3.7590995]]]]],[[[[[ 4.5081043 24.11918 -3.554603 ]]]]],7NHM
78,[[[[[0. 0. 0.]]]]],[[[[[-3.9770977 4.7810245 0.86862826]]]]],[[[[[-3.5313535 10.005204 -4.657605 ]]]]],[[[[[-6.190122 15.835979 -9.158998]]]]],[[[[[-10.580742 15.29184 -4.6535664]]]]],[[[[[-16.685808 19.60167 -1.9646478]]]]],7NWI
79,[[[[[0. 0. 0.]]]]],[[[[[-2.9753408 -2.0000682 -3.8878837]]]]],[[[[[-7.779141 -1.248187 -4.4403133]]]]],[[[[[-12.694907 -0.9159646 -11.58294 ]]]]],[[[[[-8.793595 7.7229414 -9.791215 ]]]]],[[[[[ -2.1296363 5.533547 -15.104141 ]]]]],7OGM

In [78]:
structure = parser.get_structure('1KXK', f"./mmCIF_files/1KXK.cif")
model = structure[0]
ends[ends['ID'] == '1KXK']

     ID  start  end     seq    braq chain
1  1KXK      1    6  GUCUAC  .....(     A

In [79]:
chain = model['A']
res = chain[1]
print(res)
at = res["C1'"]
at.get_coord()

<Residue G het=  resseq=1 icode= >

array([ -2.762,  49.383, 184.09 ], dtype=float32)

In [80]:
ends_database = ends_databse.drop('id', axis=1)
for column in ends_database.columns:
    ends_database[column] = ends_database[column].apply(lambda x: ','.join(map(str, x)))
    
ends_database['class'] = 0
ends_database.to_csv("ends_database_C1'.csv")
ends_database

,N1,N2,N3,N4,N5,N6,class
1,[[0. 0. 0.]],[[4.7392836 1.6047585 0.3247044]],[[ 9.301666 4.043298 -0.6491785]],[[11.785527 7.5683985 -3.2119083]],[[13.804838 9.696486 -8.285176]],[[11.400997 13.94923 -9.538257]],0
15,[[0. 0. 0.]],[[-2.6993585e+00 -4.6278558e+00 -3.2709837e-03]],[[-2.296773 -9.943279 -1.3772607]],[[ 2.5057361e+00 -1.4523361e+01 -1.3960838e-02]],[[ -0.3371731 -21.187784 -1.543951 ]],[[ 2.2402074 -25.474472 -1.1554918]],0
17,[[0. 0. 0.]],[[ 3.9674602 3.7266514 -0.15177464]],[[ 6.7623878 7.953205 -2.7240477]],[[ 5.7517066 11.717857 -6.6278057]],[[ 6.6940002 19.982117 -7.426035 ]],[[ 1.0052726 17.040554 -8.105388 ]],0
18,[[0. 0. 0.]],[[4.4171324 0.08777595 3.9546573 ]],[[6.3533916 5.0112076 8.572324 ]],[[10.582216 3.3232284 15.867943 ]],[[15.360696 3.1921291 15.542921 ]],[[21.416489 0.47280788 17.979017 ]],0
21,[[0. 0. 0.]],[[0.4363533 4.282511 2.8982973]],[[2.700162 8.812694 3.750507]],[[ 5.0236855 13.131694 1.0604465]],[[ 4.889003 16.053795 -3.28165 ]],[[ 4.1028686 22.8459 -8.226617 ]],0
24,[[0. 0. 0.]],[[-0.11005095 -2.9451692 4.237674 ]],[[ 1.6605628 -7.2839336 7.2457314]],[[ 6.5709705 -10.129158 7.8612366]],[[ 11.671274 -10.051995 8.738542]],[[11.217145 -4.5850854 12.720346 ]],0
26,[[0. 0. 0.]],[[ 5.5932193 -0.46163952 -0.9843978 ]],[[9.9222355 1.0104154 0.66989076]],[[13.523029 -4.981833 3.591352]],[[19.561628 -8.743424 3.513214]],[[24.479202 -7.684703 5.1691885]],0
28,[[0. 0. 0.]],[[-5.649952 0.08372605 3.7145052 ]],[[-7.677737 4.01614 2.209635]],[[-10.853732 8.013066 2.005413]],[[-11.2384 12.243876 -0.41678762]],[[-10.337126 14.403427 -4.621217]],0
34,[[0. 0. 0.]],[[-4.8347416 3.5165513 -0.07206714]],[[-9.227182 5.999819 -1.5242133]],[[-14.440483 2.202835 2.983201]],[[-20.103237 1.979733 4.9295535]],[[-25.078999 2.5314698 4.1350956]],0
41,[[0. 0. 0.]],[[-2.5640314 -7.415701 3.3087695]],[[-7.985015 -5.0667133 9.691292 ]],[[ -9.503412 -10.909735 7.026582]],[[-10.8685255 -15.758442 10.6258955]],[[-12.017687 -17.079185 16.020657]],0
46,[[0. 0. 0.]],[[-5.4285297 0.27897537 -1.8964052 ]],[[-8.978109 5.2000995 1.2864428]],[[-14.043205 6.5605783 -0.07922077]],[[-16.7309 1.3830068 0.95607185]],[[-14.611994 3.157785 9.316658]],0
50,[[0. 0. 0.]],[[-6.8171773 -4.5826087 0.3692264]],[[-10.961857 -1.900209 -7.6682773]],[[-11.505335 -6.115375 -1.0097982]],[[-13.558575 -9.6015415 1.6981727]],[[-5.5331154 -8.91588 -0.9280007]],0
51,[[0. 0. 0.]],[[ 3.5464623 -2.4165993 4.107751 ]],[[10.169506 1.1072612 10.399937 ]],[[10.694972 -6.002014 14.590964]],[[15.236248 -0.65792507 18.699871 ]],[[18.81351 2.740355 12.699826]],0
54,[[0. 0. 0.]],[[-1.5562817 -5.2303724 -0.40726772]],[[-5.0258617 -8.135008 -3.8161998]],[[-7.611704 -9.631033 -8.078852]],[[-11.799381 -17.588312 -9.525653]],[[-17.569212 -14.775775 -14.588478]],0
55,[[0. 0. 0.]],[[4.5732646 2.5937736 0.39710426]],[[ 7.9842005 7.3770323 -1.2282898]],[[8.937556 9.431403 5.71579 ]],[[12.041223 13.55471 10.471947]],[[13.309862 18.778389 10.258316]],0
58,[[0. 0. 0.]],[[ 0.7738962 2.4126563 -4.846445 ]],[[ 1.9130331 2.5839796 -10.011283 ]],[[ -3.6748724 7.3105025 -11.540256 ]],[[ -5.249647 12.377535 -15.899076]],[[ -6.3007927 12.619062 -20.883183 ]],0
60,[[0. 0. 0.]],[[ 3.365078 3.215941 -1.9957255]],[[-1.664123 9.288926 1.5654554]],[[-6.423154 11.732423 0.6677828]],[[-13.823707 7.400654 2.3603392]],[[-10.661161 3.4195323 7.3750424]],0
61,[[0. 0. 0.]],[[ 3.2125645 3.4098616 -1.8305626]],[[-1.8512259 8.984746 2.0997486]],[[-6.946838 11.14159 0.7793231]],[[-13.788456 6.062044 2.2688837]],[[-11.063946 2.3682368 7.269955 ]],0
64,[[0. 0. 0.]],[[-4.3480873 3.807314 2.0543764]],[[-8.409418 6.0626554 -0.9874706]],[[-13.470207 5.3834476 -3.9440832]],[[-21.095362 9.86759 -5.7581224]],[[-20.736652 10.869913 -13.28603 ]],0
67,[[0. 0. 0.]],[[-3.3472435 -3.026158 3.6686306]],[[-5.5044327 -3.3815162 8.000416 ]],[[-12.458981 -4.359601 6.8542438]],[[-17.859732 -7.175166 8.949301]],[[-20.159586 -5.7147975 13.582968 ]],0
68,[[0. 0. 0.]],[[ 2.0516284 -5.761902 0.44727677]],[[ 2.4035025 -10.784292 2.6946318]],[[ 4.3477435 -14.915492 5.5581913]],[[ 7.7164125 -16.60353 7.6318903]],[[ 12.607513 -15.98263 10.149201]],0
69,[[0. 0. 0.]],[[2.5376186 4.036087 1.6050746]],[[6.625713 8.49572 1.6050525]],[[ 7.810256 11.402888 -2.560935]],[[12.18489 19.542282 -2.5227072]],[[15.703356 20.164766 -9.4875 ]],0
71,[[0. 0. 0.]],[[-7.8961205 -0.19844861 -0.09738151]],[[-11.562883 1.346351 -7.7750874]],[[-11.04253 6.6850996 -7.5973306]],[[-9.404783 10.374036 -3.3181443]],[[-3.5884657 15.246567 -4.013546 ]],0
72,[[0. 0. 0.]],[[ 3.7663243 4.2935166 -0.11479306]],[[ 3.813916 12.760635 0.67559767]],[[-1.8050342 13.496552 6.4532924]],[[-2.8424938 13.610335 11.657376 ]],[[-1.5851865 12.108632 16.707664 ]],0
73,[[0. 0. 0.]],[[ 4.006945 -0.18098092 5.7341237 ]],[[ 5.286071 -0.9914228 11.0982485]],[[ 5.0029964 -0.371997 16.401855 ]],[[ 3.1708794 -2.437755 23.860062 ]],[[ 4.5702424 2.5906692 25.955273 ]],0
77,[[0. 0. 0.]],[[ 0.04408479 4.8187447 -2.322442 ]],[[-2.6228404 9.435992 -2.6779454]],[[ 3.8060286 13.80798 -2.4268074]],[[ 6.2041464 19.51902 -3.7590995]],[[ 4.5081043 24.11918 -3.554603 ]],0
78,[[0. 0. 0.]],[[-3.9770977 4.7810245 0.86862826]],[[-3.5313535 10.005204 -4.657605 ]],[[-6.190122 15.835979 -9.158998]],[[-10.580742 15.29184 -4.6535664]],[[-16.685808 19.60167 -1.9646478]],0
79,[[0. 0. 0.]],[[-2.9753408 -2.0000682 -3.8878837]],[[-7.779141 -1.248187 -4.4403133]],[[-12.694907 -0.9159646 -11.58294 ]],[[-8.793595 7.7229414 -9.791215 ]],[[ -2.1296363 5.533547 -15.104141 ]],0

In [81]:
ends_database = ends_databse.drop('id', axis=1)
for column in ends_database.columns:
    ends_database[column] = ends_database[column].apply(lambda x: ','.join(map(str,np.array(x).flatten())))
    
ends_database['class'] = 0
ends_database.to_csv("./modified_coord/ends_C1'.csv")
ends_database

,N1,N2,N3,N4,N5,N6,class
1,"0.0,0.0,0.0","4.7392836,1.6047585,0.3247044","9.301666,4.043298,-0.6491785","11.785527,7.5683985,-3.2119083","13.804838,9.696486,-8.285176","11.400997,13.94923,-9.538257",0
15,"0.0,0.0,0.0","-2.6993585,-4.627856,-0.0032709837","-2.296773,-9.943279,-1.3772607","2.505736,-14.523361,-0.013960838","-0.3371731,-21.187784,-1.543951","2.2402074,-25.474472,-1.1554918",0
17,"0.0,0.0,0.0","3.9674602,3.7266514,-0.15177464","6.7623878,7.953205,-2.7240477","5.7517066,11.717857,-6.6278057","6.6940002,19.982117,-7.426035","1.0052726,17.040554,-8.105388",0
18,"0.0,0.0,0.0","4.4171324,0.087775946,3.9546573","6.3533916,5.0112076,8.572324","10.582216,3.3232284,15.867943","15.360696,3.1921291,15.542921","21.416489,0.47280788,17.979017",0
21,"0.0,0.0,0.0","0.4363533,4.282511,2.8982973","2.700162,8.812694,3.750507","5.0236855,13.131694,1.0604465","4.889003,16.053795,-3.28165","4.1028686,22.8459,-8.226617",0
24,"0.0,0.0,0.0","-0.110050954,-2.9451692,4.237674","1.6605628,-7.2839336,7.2457314","6.5709705,-10.129158,7.8612366","11.671274,-10.051995,8.738542","11.217145,-4.5850854,12.720346",0
26,"0.0,0.0,0.0","5.5932193,-0.46163952,-0.9843978","9.9222355,1.0104154,0.66989076","13.523029,-4.981833,3.591352","19.561628,-8.743424,3.513214","24.479202,-7.684703,5.1691885",0
28,"0.0,0.0,0.0","-5.649952,0.08372605,3.7145052","-7.677737,4.01614,2.209635","-10.853732,8.013066,2.005413","-11.2384,12.243876,-0.41678762","-10.337126,14.403427,-4.621217",0
34,"0.0,0.0,0.0","-4.8347416,3.5165513,-0.07206714","-9.227182,5.999819,-1.5242133","-14.440483,2.202835,2.983201","-20.103237,1.979733,4.9295535","-25.078999,2.5314698,4.1350956",0
41,"0.0,0.0,0.0","-2.5640314,-7.415701,3.3087695","-7.985015,-5.0667133,9.691292","-9.503412,-10.909735,7.026582","-10.8685255,-15.758442,10.6258955","-12.017687,-17.079185,16.020657",0
46,"0.0,0.0,0.0","-5.4285297,0.27897537,-1.8964052","-8.978109,5.2000995,1.2864428","-14.043205,6.5605783,-0.07922077","-16.7309,1.3830068,0.95607185","-14.611994,3.157785,9.316658",0
50,"0.0,0.0,0.0","-6.8171773,-4.5826087,0.3692264","-10.961857,-1.900209,-7.6682773","-11.505335,-6.115375,-1.0097982","-13.558575,-9.6015415,1.6981727","-5.5331154,-8.91588,-0.9280007",0
51,"0.0,0.0,0.0","3.5464623,-2.4165993,4.107751","10.169506,1.1072612,10.399937","10.694972,-6.002014,14.590964","15.236248,-0.65792507,18.699871","18.81351,2.740355,12.699826",0
54,"0.0,0.0,0.0","-1.5562817,-5.2303724,-0.40726772","-5.0258617,-8.135008,-3.8161998","-7.611704,-9.631033,-8.078852","-11.799381,-17.588312,-9.525653","-17.569212,-14.775775,-14.588478",0
55,"0.0,0.0,0.0","4.5732646,2.5937736,0.39710426","7.9842005,7.3770323,-1.2282898","8.937556,9.431403,5.71579","12.041223,13.55471,10.471947","13.309862,18.778389,10.258316",0
58,"0.0,0.0,0.0","0.7738962,2.4126563,-4.846445","1.9130331,2.5839796,-10.011283","-3.6748724,7.3105025,-11.540256","-5.249647,12.377535,-15.899076","-6.3007927,12.619062,-20.883183",0
60,"0.0,0.0,0.0","3.365078,3.215941,-1.9957255","-1.664123,9.288926,1.5654554","-6.423154,11.732423,0.6677828","-13.823707,7.400654,2.3603392","-10.661161,3.4195323,7.3750424",0
61,"0.0,0.0,0.0","3.2125645,3.4098616,-1.8305626","-1.8512259,8.984746,2.0997486","-6.946838,11.14159,0.7793231","-13.788456,6.062044,2.2688837","-11.063946,2.3682368,7.269955",0
64,"0.0,0.0,0.0","-4.3480873,3.807314,2.0543764","-8.409418,6.0626554,-0.9874706","-13.470207,5.3834476,-3.9440832","-21.095362,9.86759,-5.7581224","-20.736652,10.869913,-13.28603",0
67,"0.0,0.0,0.0","-3.3472435,-3.026158,3.6686306","-5.5044327,-3.3815162,8.000416","-12.458981,-4.359601,6.8542438","-17.859732,-7.175166,8.949301","-20.159586,-5.7147975,13.582968",0
68,"0.0,0.0,0.0","2.0516284,-5.761902,0.44727677","2.4035025,-10.784292,2.6946318","4.3477435,-14.915492,5.5581913","7.7164125,-16.60353,7.6318903","12.607513,-15.98263,10.149201",0
69,"0.0,0.0,0.0","2.5376186,4.036087,1.6050746","6.625713,8.49572,1.6050525","7.810256,11.402888,-2.560935","12.18489,19.542282,-2.5227072","15.703356,20.164766,-9.4875",0
71,"0.0,0.0,0.0","-7.8961205,-0.19844861,-0.09738151","-11.562883,1.346351,-7.7750874","-11.04253,6.6850996,-7.5973306","-9.404783,10.374036,-3.3181443","-3.5884657,15.246567,-4.013546",0
72,"0.0,0.0,0.0","3.7663243,4.2935166,-0.11479306","3.813916,12.760635,0.67559767","-1.8050342,13.496552,6.4532924","-2.8424938,13.610335,11.657376","-1.5851865,12.108632,16.707664",0
73,"0.0,0.0,0.0","4.006945,-0.18098092,5.7341237","5.286071,-0.9914228,11.0982485","5.0029964,-0.371997,16.401855","3.1708794,-2.437755,23.860062","4.5702424,2.5906692,25.955273",0
77,"0.0,0.0,0.0","0.044084787,4.8187447,-2.322442","-2.6228404,9.435992,-2.6779454","3.8060286,13.80798,-2.4268074","6.2041464,19.51902,-3.7590995","4.5081043,24.11918,-3.554603",0
78,"0.0,0.0,0.0","-3.9770977,4.7810245,0.86862826","-3.5313535,10.005204,-4.657605","-6.190122,15.835979,-9.158998","-10.580742,15.29184,-4.6535664","-16.685808,19.60167,-1.9646478",0
79,"0.0,0.0,0.0","-2.9753408,-2.0000682,-3.8878837","-7.779141,-1.248187,-4.4403133","-12.694907,-0.9159646,-11.58294","-8.793595,7.7229414,-9.791215","-2.1296363,5.533547,-15.104141",0

In [82]:
with open("ends_database_C1'_seqs.csv", 'w', newline='') as f:
     
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for item in ends_seqs:
        write.writerow([item])

<h3>Mix</h3>

In [83]:
import os
from Bio.PDB.MMCIFParser import MMCIFParser

files = os.listdir('./rnasolo-3.218-dbn-csv/rnasolo-3.218/dbn/')
files = [file for file in files if file.endswith('.dbn')]
files.sort()
print(files)
print(len(files))

FileNotFoundError: [WinError 3] System nie może odnaleźć określonej ścieżki: './rnasolo-3.218-dbn-csv/rnasolo-3.218/dbn/'

In [ ]:
import random
import re
mixs_seqs = []
for file in files:
    try:
        f = open(f"./rnasolo-3.218-dbn-csv/rnasolo-3.218/dbn/{file}", "r")
        seq = f.read().split('\n')
        if len(seq) == 2:
             if len(seq[1]) > 11:
                num = random.randint(2, len(seq[1])-7)
                br = seq[1][num:num+6]
                if '(' in br and '.' in br:
                    if len(re.findall(r'\(', br)) >= 2 and len(re.findall(r'\.', br)) >= 2:
                        mixs_seqs.append([file.rstrip('.dbn'), seq[0][num:num+6], seq[1][num:num+6], num, num+5])
    finally:
        f.close()
print(mixs_seqs)
print(len(mixs_seqs))

[['1A9L_1_A', 'CUCCAG', '((((..', 6, 11], ['1AFX_2_A', 'UGUGAA', '((....', 2, 7], ['1AJF_1_A', 'GGGGAA', '(((...', 4, 9], ['1AKX_1_A', 'GCCUGG', '((....', 11, 16], ['1ANR_2_A', 'AGCCUG', '(((...', 10, 15], ['1ARJ_7_N', 'CUGAGC', '..((((', 7, 12], ['1ATO_1_A', 'CCUCCU', '((....', 4, 9], ['1ATV_1_A', 'GACCAG', '((((..', 2, 7], ['1ATW_1_A', 'CCAGAU', '((....', 3, 8], ['1BGZ_1_A', 'UGCUUC', '(((...', 7, 12], ['1CQL_10_A', 'AGGUCA', '.(((..', 10, 15], ['1D4R_1_B-A', 'GGGAGC', '(....(', 10, 15], ['1D6K_4_B', 'CCGAUG', '((....', 3, 8], ['1E4P_8_A', 'ACGAAA', '((....', 8, 13], ['1E7K_1_C', 'GAGGCC', '..(())', 6, 11], ['1EBR_1_A', 'GGCGCA', '..((((', 4, 9], ['1EC6_1_C', 'GGACCU', '((....', 2, 7], ['1EHT_3_A', 'ACCAGC', '.((.((', 6, 11], ['1ESH_1_A', 'UGCAUA', '(((...', 2, 7], ['1F1T_1_A', 'CGGCGA', '((((..', 8, 13], ['1F27_1_A', 'GUCAGA', '((....', 3, 8], ['1F5U_1_A', 'GAGACG', '((....', 5, 10], ['1F85_1_A', 'CCUGAU', '(((...', 2, 7], ['1FMN_1_A', 'UGCUUC', '(((...', 13, 18], ['1FYP_1_A', 'CGUCGC', '((.(.(', 2, 7], ['1GAX_1_D', 'UCGCCU', '((((..', 26, 31], ['1HJI_1_A', 'CUGAAA', '((....', 3, 8], ['1HMH_1_E', 'GAGGCC', '..((((', 12, 17], ['1I46_1_A', 'UGCGUA', '(((...', 2, 7], ['1I4C_1_A', 'GCUUAG', '((...)', 3, 8], ['1ICG_1_A-B', 'UCGGCG', '..((()', 3, 8], ['1IHA_1_A-B', 'UUCGGC', '(..(((', 2, 7], ['1IK1_1_A', 'UACUAU', '(((...', 2, 7], ['1IKD_24_A', 'GCUCUU', '((((..', 3, 8], ['1JO7_18_A', 'GGCUUC', '(((...', 11, 16], ['1JZC_1_A', 'GCAUGG', '((...)', 3, 8], ['1K4A_1_A', 'UCAGAA', '((....', 3, 8], ['1K4B_1_A', 'UCAGUU', '((....', 3, 8], ['1K5I_2_A', 'GGGCUC', '(((...', 6, 11], ['1KKS_1_A', 'CCCUUU', '((((..', 6, 11], ['1KOD_1_B-A', 'GUGUAC', '..(())', 7, 12], ['1KPD_1_A', 'GCAGUG', '((...[', 3, 8], ['1KUQ_1_B', 'AGAGGC', '...(((', 26, 31], ['1LC6_7_A', 'CCCUGC', '.(((..', 5, 10], ['1LNT_1_A-B', 'AGGUCG', '...(((', 5, 10], ['1LU3_1_A', 'AGACUG', '((....', 3, 8], ['1M5L_1_A', 'GGACUC', '...(((', 5, 10], ['1MFK_1_A', 'CAGGUC', '((....', 8, 13], ['1MFQ_1_A', 'GUCGGA', '.(((..', 82, 87], ['1MFY_1_A', 'GCUUCG', '((....', 12, 17], ['1MIS_1_A-B', 'GGACGC', '(..(((', 2, 7], ['1N78_1_C', 'GCCCUC', '(((...', 28, 33], ['1NUV_1_A-B', 'GAGCCA', '...(((', 6, 11], ['1NUV_1_E-F', 'CGAGCC', '....((', 5, 10], ['1OOA_1_C', 'AAACUG', '.((((.', 8, 13], ['1OQ0_1_A', 'GAGUUG', '((((..', 2, 7], ['1OSW_3_A', 'GGCGCU', '(.(((.', 3, 8], ['1OW9_1_A', 'CGAAGA', '(...((', 3, 8], ['1P5N_8_A', 'AGAAAG', '(....(', 3, 8], ['1P5P_1_A', 'UUCACG', '..(((.', 20, 25], ['1QD3_1_A', 'GAUUUG', '((...(', 4, 9], ['1QWA_1_A', 'CCUCCC', '(((...', 5, 10], ['1QWB_4_A', 'ACACGA', '((((..', 2, 7], ['1RAW_1_A', 'GAAGGG', '((((..', 2, 7], ['1RFR_3_A', 'GUAUCA', '((((..', 9, 14], ['1RKJ_1_B', 'UGCCUC', '((((..', 3, 8], ['1RY1_1_Q-R', 'GUGUCA', '(.(...', 7, 12], ['1S03_1_A', 'GCGAAA', '(.((..', 8, 13], ['1S03_1_B', 'GCGAAA', '(.((..', 8, 13], ['1S9S_4_A', 'UACUAG', '..((((', 5, 10], ['1TFN_1_A', 'GACGAU', '(.((..', 6, 11], ['1TJZ_15_A', 'UGACGC', '(..(((', 2, 7], ['1TLR_1_A', 'AGACUU', '.(((..', 6, 11], ['1TXS_4_A', 'CUAGCA', '(..(((', 3, 8], ['1U63_1_D', 'GAGGCU', '..((((', 10, 15], ['1UN6_1_F', 'CUGGGA', '(.((..', 31, 36], ['1UTS_2_B', 'AGCCUG', '(((...', 10, 15], ['1UUU_7_A', 'GUACGU', '((((..', 3, 8], ['1X8W_1_C', 'AAAGGG', '...(((', 17, 22], ['1XNQ_1_X-W', 'UgCGAA', '..((..', 3, 8], ['1XNR_1_X-W', 'UgCGAA', '.(((..', 3, 8], ['1XSH_1_A', 'UCUUCG', '((....', 10, 15], ['1ZBH_1_F', 'CUUUUC', '((....', 4, 9], ['1ZBN_1_A', 'UCGUGU', '(((.(.', 3, 8], ['1ZCI_1_A-B', 'UGAAGU', '((..[[', 4, 9], ['1ZIF_6_A', 'GCGAAA', '((....', 2, 7], ['1ZL3_1_B', 'CGGUCG', '(((...', 5, 10], ['1ZX7_1_C-E-D-F', 'UGAAGU', '((..(.', 4, 9], ['1ZZ5_1_A-C-B-D', 'GUGAAG', '(((..(', 3, 8], ['28SR_1_A', 'UCAGGU', '(....(', 4, 9], ['2A9X_1_2', 'CGUGUA', '((.(.(', 4, 9], ['2AU4_1_A', 'GGCGCU', '.((((.', 15, 20], ['2BGG_1_P-Q', 'CGACGC', '((((..', 2, 7], ['2BTE_1_B', 'GUGCGC', '))((..', 38, 43], ['2C4Q_1_R', 'GGAUAC', '((...)', 5, 10], ['2CSX_1_C', 'GUCGGA', '...(((', 46, 51], ['2D1B_1_A', 'UGAAGU', '((....', 12, 17], ['2DD2_1_A-B', 'GAAGGC', '...(((', 3, 8], ['2DD3_1_A-B', 'AAGGCU', '..(((.', 4, 9], ['2DU3_1_D', 'GGUGGC', '((..((', 5, 10], ['2ES5_1_A', 'UCUGGC', '((..).', 8, 13], ['2FDT_7_A', 'ACGUCG', '(.(.((', 6, 11], ['2G91_1_A-B', 'GCCGGU', '((..))', 5, 10], ['2GIO_1_A', 'UUGCUC', '.(.(((', 7, 12], ['2GJW_1_I-J-L', 'GCUGCA', '((((..', 13, 18], ['2GV3_6_A', 'AGACUC', '(((...', 4, 9], ['2IHX_1_B', 'AUGACC', '....((', 37, 42], ['2IRO_1_A-B', 'AUGCUG', '..((.)', 4, 9], ['2IY5_1_T', 'UGUCCG', '....((', 44, 49], ['2IZN_1_R', 'GCGAUU', '.((...', 3, 8], ['2JSE_1_A', 'GGCCGA', '.(((..', 5, 10], ['2JTP_16_A', 'AAGAAG', '((...(', 9, 14], ['2JUK_8_A', 'UCCCAC', '((((..', 5, 10], ['2JWV_1_A', 'UUGAAA', '....((', 5, 10], ['2JYH_1_B', 'CGGGGA', '((((..', 15, 20], ['2KF0_2_A', 'CCCUGC', '.(((..', 5, 10], ['2KHY_9_A', 'UCACAA', '((....', 4, 9], ['2KMJ_4_A', 'GAGCUU', '((((..', 9, 14], ['2KPC_6_A', 'AGCACA', '((((..', 2, 7], ['2KRP_1_A', 'CGGCUA', '(((...', 2, 7], ['2KU0_4_A', 'UACUGU', '..((((', 8, 13], ['2KVN_19_A', 'GAUUGA', '((....', 3, 8], ['2KXM_1_A', 'UGCUUG', '((...(', 3, 8], ['2L6I_1_A', 'UCUCUU', '((((..', 2, 7], ['2L8F_1_A-B', 'CCCGUC', '.(((.)', 6, 11], ['2LA5_6_A', 'CGGUGU', '(.((..', 4, 9], ['2LBJ_5_A', 'CUUGCC', '((....', 4, 9], ['2LDT_4_A', 'GGCCGC', '((((..', 9, 14], ['2LKR_3_A', 'UUUACA', '....((', 47, 52], ['2M12_2_A', 'UAUUGG', '(..(..', 5, 10], ['2M22_6_A', 'GAUCUG', '(.(((.', 4, 9], ['2M23_1_A', 'AUGUAU', '((((..', 5, 10], ['2M57_5_A', 'GCGGUA', '((((..', 10, 15], ['2MF0_6_G', 'CAUCGC', '..((((', 41, 46], ['2MFC_1_B', 'UCGACG', '((....', 5, 10], ['2MIY_5_A', 'GGAUAA', '((....', 39, 44], ['2MNC_1_A', 'UUGAAU', '(.(...', 3, 8], ['2MXL_1_A', 'UACCAG', '((((..', 13, 18], ['2N3Q_8_A', 'GUGCUU', '((((..', 33, 38], ['2N6T_1_A', 'UAGAGU', '(...((', 3, 8], ['2N7X_15_A', 'GUUUUG', '(..((.', 4, 9], ['2NBY_6_A', 'GAAGGU', '((.((.', 5, 10], ['2NBZ_1_A', 'UGCUUU', '((....', 14, 19], ['2NC0_1_A', 'AUGGAG', '(((...', 10, 15], ['2NCI_1_A', 'AAGGCU', '..(((.', 9, 14], ['2NUG_1_E-F-C-D', 'GCAAGG', '..((((', 20, 25], ['2O3X_1_A-B', 'AAGUCG', '..(.((', 14, 19], ['2OIU_1_Q', 'CGACCA', '(....(', 20, 25], ['2OM7_1_C', 'AAGUCG', '..(.((', 32, 37], ['2OM7_1_H', 'CGAGCG', '...((.', 12, 17], ['2OM7_1_I', 'GGAGGU', '(.(((.', 4, 9], ['2OM7_1_J', 'GGGAGC', '((...(', 29, 34], ['2OOM_3_A', 'AGCCUG', '(((...', 2, 7], ['2P89_3_A', 'CAGUUC', '(((...', 12, 17], ['2PN3_1_A-B', 'CUACUG', '...(((', 8, 13], ['2PN9_1_A-B', 'ACGGUC', '(((..]', 17, 22], ['2QH3_1_A', 'CCUUAC', '((....', 6, 11], ['2QH4_19_A', 'CACAGA', '((((..', 2, 7], ['2R8S_1_R', 'AAAGGG', '...(((', 11, 16], ['2RKJ_1_C', 'UCCGAU', '(((...', 113, 118], ['2RLU_1_A', 'CGGGUC', '((....', 5, 10], ['2RN1_3_A', 'CCCUGG', '((....', 3, 8], ['2VPL_1_B', 'GAGGCU', '..((((', 9, 14], ['2WW9_1_D', 'GUAAUG', '.(.((.', 22, 27], ['2WW9_1_F', 'CGUCAA', '(((...', 3, 8], ['2WW9_1_G', 'GCACCU', '(((...', 4, 9], ['2WWB_1_E', 'GAACUU', '(..((.', 6, 11], ['2WWB_1_F', 'GUCAAC', '((...(', 4, 9], ['2WWB_1_G', 'ACGUCG', '.((...', 2, 7], ['2XEB_1_A-B', 'UAGCCA', '(.(((.', 5, 10], ['2Y8Y_1_B', 'ACGCGU', '((....', 5, 10], ['2Y9H_1_J', 'CACGCG', '((....', 4, 9], ['397D_1_A-B', 'GAUCUG', '((...(', 5, 10], ['3AM1_1_B', 'GGGGUA', '((((..', 5, 10], ['3AVU_1_T-G', 'UCCAGU', '(.((.)', 3, 8], ['3AVX_1_T-G', 'UCAACG', '((...)', 7, 12], ['3BO0_1_G', 'CACUAC', '(((...', 13, 18], ['3BO1_1_D', 'GUGAUA', '((....', 7, 12], ['3C3Z_1_A-B', 'GCUGAA', '((((..', 2, 7], ['3DH3_1_F-E', 'GUCGUG', '(((...', 26, 31], ['3EGZ_1_B', 'GGAGAG', '((...(', 3, 8], ['3EPH_1_E', 'GUCCUU', '...((.', 43, 48], ['3FTM_1_D-C', 'GAGGCU', '..((((', 4, 9], ['3H5X_1_T-P', 'GGGUGC', '(((..)', 4, 9], ['3HHN_1_E', 'AGGGCU', '.).(.(', 49, 54], ['3HJY_1_D-C-E', 'UCCGGA', '((((..', 4, 9], ['3IWN_1_A', 'AAACGG', '(..(((', 50, 55], ['3J0O_1_2', 'GAGUAA', '(((...', 57, 62], ['3J0O_1_8', 'GUCGUG', '(((...', 4, 9], ['3J16_1_J', 'AUUUGA', '...((.', 135, 140], ['3J16_1_K', 'ACUUAG', '(((...', 132, 137], ['3J45_1_2', 'ACGUUA', '.((...', 15, 20], ['3J45_1_4', 'UGAUGG', '....((', 18, 23], ['3J6B_1_e', 'GGGAGU', '((....', 4, 9], ['3J79_1_B', 'GAUCCC', '((...(', 29, 34], ['3J7Q_1_5-8', 'GGCGAA', '((....', 1219, 1224], ['3J7R_1_S6', 'CCCCGA', '.(.(..', 10, 15], ['3J92_1_2', 'GUCGUC', '...(((', 44, 49], ['3JCS_1_5', 'GGCUGG', '....((', 32, 37], ['3K1V_1_A', 'AGGUUC', '(((...', 2, 7], ['3NMU_1_E-K', 'CCGAAA', '((....', 16, 21], ['3OIN_1_C', 'GCUUCA', '((....', 2, 7], ['3P22_1_A', 'UCGAAA', '((....', 14, 19], ['3R2D_1_R-S', 'UCCUUG', '.((..(', 3, 8], ['3RG5_1_B', 'UCAGUG', '((((..', 13, 18], ['3TUP_1_T', 'GCUCAG', '((((..', 9, 14], ['3U4M_1_B', 'AUAGGU', '[..(((', 12, 17], ['3UZS_1_C', 'CCAUAC', '((....', 6, 11], ['3WFS_1_A', 'GGUAGC', '((..((', 5, 10], ['402D_1_A-B', 'CAGCGC', '..((()', 3, 8], ['418D_1_A-B', 'ACACGU', '((..))', 4, 9], ['486D_1_A', 'GUGAUA', '((((..', 3, 8], ['486D_1_C', 'GAUUUA', '((((..', 3, 8], ['4A4T_1_A', 'GGCUUA', '(((...', 6, 11], ['4A4U_1_A', 'GGCUGA', '(((...', 6, 11], ['4AL5_1_B', 'CCGUAU', '((....', 4, 9], ['4B3R_1_Z-W', 'GGAUUG', '(((..]', 5, 10], ['4BY9_1_A', 'AGCAAU', '(((...', 3, 8], ['4C8Y_1_C', 'CCCGAG', '(((..)', 2, 7], ['4C8Z_1_C', 'CCCGUA', '(((...', 3, 8], ['4C9D_1_D', 'CCUCGU', '.(((..', 2, 7], ['4D61_1_j', 'AGGAUG', '.((.(.', 98, 103], ['4E48_1_A-B', 'UGCUGC', '.((.((', 5, 10], ['4E58_1_D-C-E', 'CCCGCG', '(..(.(', 2, 7], ['4GXY_1_A', 'GAAGCC', '...(((', 34, 39], ['4JAH_1_A-B', 'GUAACG', '((.((.', 2, 7], ['4JF2_1_A', 'GCUUCG', '((....', 57, 62], ['4KJI_1_C', 'CCGAAG', '(((...', 2, 7], ['4KQY_1_A', 'GAGAAG', '..((((', 11, 16], ['4KR6_1_C', 'UGGGAA', '(((...', 16, 21], ['4LCK_1_F', 'UGCGAU', '(((...', 3, 8], ['4LX6_1_A', 'AGCCUU', '((]]..', 45, 50], ['4MGN_1_A', 'CUUCCG', '((((..', 23, 28], ['4N0T_1_B', 'CCUGGA', '((.)).', 38, 43], ['4NGF_1_G-H', 'CGUUUU', '((....', 12, 17], ['4P3T_1_A-B', 'CGCUUG', '(((..)', 19, 24], ['4P3U_1_B-A', 'GACGAA', '(.(((.', 9, 14], ['4P43_1_B-A', 'CGAAGU', '(((.(.', 12, 17], ['4P8Z_1_A', 'GCAAUC', '))..((', 37, 42], ['4P95_1_A', 'GGCUAA', '((...[', 46, 51], ['4PHY_1_A-B', 'UCACUG', '.(.(((', 18, 23], ['4PR6_1_B', 'ACACCA', '.((((.', 42, 47], ['4QEI_1_C', 'UGGUGU', '..(((.', 6, 11], ['4TUE_1_QV', 'GUCGUC', '...(((', 46, 51], ['4TUW_1_C', 'CUUUUC', '((....', 11, 16], ['4UER_1_A', 'ACACUG', '.(...(', 1451, 1456], ['4UJD_1_BC', 'CGCAGA', '(.((..', 23, 28], ['4UYK_1_R', 'CGGAAA', '(((...', 35, 40], ['4V49_1_B0', 'AGGCUG', '((((..', 2382, 2387], ['4V4N_1_A3', 'CAUAGC', '....((', 7, 12], ['4V4N_1_B1', 'UCGGGG', '..((((', 47, 52], ['4V6D_1_CV', 'GGCUCA', '((....', 3, 8], ['4V6U_1_A2', 'UACCGU', '(.((..', 1024, 1029], ['4V6U_1_B1', 'CAGUGC', '..((((', 1976, 1981], ['4V6U_1_B3', 'GGUCUC', '((...(', 28, 33], ['4V7E_1_Aa-Ac', 'GCUGCU', '((.((.', 1998, 2003], ['4V7E_1_Ae', 'GGGCGC', '.(((.(', 25, 30], ['4V7H_1_AA', 'CAAGUC', '((((..', 1551, 1556], ['4V7H_1_B5-B4', 'CGAGUG', '(..(.(', 824, 829], ['4V88_1_A6', 'AGCGAG', '....((', 1477, 1482], ['4V8M_1_BE', 'CAUCCA', '(...((', 29, 34], ['4V8M_1_BG', 'UUGUGA', '((....', 6, 11], ['4V8N_1_CV', 'GGCGCU', '...(((', 46, 51], ['4V8P_1_D1-C2', 'UGAAGC', '((((..', 2802, 2807], ['4V9Q_1_DV', 'UCGUCG', '..((((', 47, 52], ['4WF9_1_X', 'GUUAAG', '((...(', 640, 645], ['4WF9_1_Y', 'UGUUCC', '(((...', 29, 34], ['4WQ1_1_3K', 'CAGACU', '(((...', 26, 31], ['4WSM_1_1K', 'GCUUAC', '))..((', 53, 58], ['4WT8_1_DV', 'AUAGCU', '(..((.', 6, 11], ['4WZM_1_B-C', 'GCCCUG', '.(((.)', 4, 9], ['4Y1M_1_B', 'AAGAAA', '((....', 78, 83], ['4YAZ_1_R', 'AAACCA', '...(((', 15, 20], ['4YYE_1_C', 'UAUUAG', '(((..(', 4, 9], ['4Z7K_1_C', 'ACUUGC', '....((', 5, 10], ['4ZLD_1_B', 'CUUCUG', '((((..', 3, 8], ['5A18_1_A', 'GAGCAU', '(..(..', 9, 14], ['5B2P_1_B', 'UUCAGU', '(.(((.', 23, 28], ['5B63_1_D', 'UAGCUC', '..((((', 7, 12], ['5BJO_1_E', 'CUGAGG', ').((..', 16, 21], ['5BKL_1_bb-qq', 'AAAAAA', '..((.(', 3, 8], ['5BKN_1_bb-qq', 'AAAAAA', '.(.((.', 5, 10], ['5BTM_1_A', 'AAGGAU', '..((((', 13, 18], ['5BTP_1_B', 'GGAAUU', '((....', 21, 26], ['5C9H_1_C-D', 'UGUCUC', '((....', 5, 10], ['5CCB_1_N', 'UAGCUC', '..((((', 8, 13], ['5D5L_1_A', 'AUACUU', '((....', 25, 30], ['5D8H_1_A', 'GUUGGC', '(..(((', 18, 23], ['5DCV_1_D', 'AGCGGU', '(((...', 10, 15], ['5DDO_1_B', 'CCAGGA', '((((..', 7, 12], ['5DHC_1_C-D', 'AGUCUA', '(((..)', 5, 10], ['5E3H_1_B-C', 'CGUACG', '((..))', 9, 14], ['5E81_1_3L', 'GCUCAG', '((((..', 9, 14], ['5EL4_1_3L', 'AGGUUC', '((....', 47, 52], ['5EW4_1_B-A', 'CCCCGG', '((..((', 10, 15], ['5F5F_1_B', 'CUGCGU', '((.(..', 3, 8], ['5F5F_1_F', 'UGCGUU', '(.(...', 4, 9], ['5F5H_1_C', 'ACCGUU', '(((...', 4, 9], ['5FLX_1_z', 'CAGAAA', '((....', 25, 30], ['5G2X_1_A', 'UACUAA', '....((', 529, 534], ['5G4T_1_A-B', 'AGAACU', '....((', 5, 10], ['5G4U_1_I-J', 'GUGAGC', '(...((', 12, 17], ['5H1K_1_C-D', 'UUGACA', '..(.(.', 7, 12], ['5IBB_1_1L', 'GCUCAU', '(((...', 9, 14], ['5ID6_1_G', 'ACUAAG', '((....', 7, 12], ['5J1O_2_B', 'AGCCUG', '((((..', 10, 15], ['5J2W_1_B', 'CCUGGG', '((...)', 12, 17], ['5J7L_1_DA', 'AAAGCU', '...(((', 815, 820], ['5KQE_11_A', 'UGCUUC', '(((...', 16, 21], ['5L1Z_1_N', 'AGCCUG', '((....', 6, 11], ['5M3H_1_V-R', 'UACCUC', '..((((', 2, 7], ['5MRC_1_A', 'AUUUAA', '(((...', 1548, 1553], ['5MYJ_1_AA', 'UUUGGA', '.(.(..', 149, 154], ['5MYJ_1_BB', 'UUCCCA', '(...(.', 30, 35], ['5N5C_4_A', 'CUUAAA', '((((..', 4, 9], ['5T5H_1_B', 'GAAAGA', '(.((..', 379, 384], ['5T7V_1_D', 'GGAUAG', '(.(..(', 4, 9], ['5TBW_1_1-4', 'UUCCAC', '..((((', 1438, 1443], ['5TPY_1_A', 'GCGAAA', '((....', 11, 16], ['5UDZ_1_W', 'UAGUGA', '((....', 4, 9], ['5UZ6_1_A', 'GGUGGA', '....((', 2, 7], ['5V17_1_A', 'GCACAC', '((....', 18, 23], ['5V1K_1_A-B', 'GAAAGC', '....((', 3, 8], ['5V3F_1_A', 'GCGAAG', '((....', 2, 7], ['5V93_1_a', 'AGUCGA', '.(((..', 55, 60], ['5VJ9_1_C', 'GGACGA', '((....', 4, 9], ['5VPO_1_XV', 'UCGUUC', '((((..', 2, 7], ['5VW1_1_C', 'CAACUU', '..((((', 56, 61], ['5VYC_1_i2', 'GAGGUG', '((....', 828, 833], ['5WLH_1_B', 'CCCAAG', '(((...', 8, 13], ['5XTM_1_D', 'UGGGAU', '((((..', 3, 8], ['5XWP_1_C', 'CCCAAA', '(((...', 6, 11], ['5XXB_1_3', 'GGUUAG', '((....', 68, 73], ['5XY3_1_3', 'GCUCCA', '(...(.', 30, 35], ['5Y58_1_X', 'GAUGGC', '(((...', 9, 14], ['5Y85_1_D', 'GGUGCA', '((....', 9, 14], ['5ZAM_1_C', 'GGUUGG', '(.((..', 10, 15], ['5ZWM_1_H-I-F', 'GGAGUC', '..((((', 370, 375], ['5ZWO_1_H-I-F', 'CGGACG', '.(.(((', 284, 289], ['6AAX_1_B', 'UACUGG', '((((..', 8, 13], ['6AGB_1_A', 'ACCUAU', '.((...', 53, 58], ['6AH3_1_T', 'AGACUG', '((....', 32, 37], ['6AZ1_1_1', 'AGCUGG', '.(((..', 304, 309], ['6AZ4_1_A', 'UAAGGA', '...(((', 13, 18], ['6BG9_1_A-B', 'GACUCG', '..((((', 5, 10], ['6BU9_1_B-C', 'UAGUAG', '..((((', 5, 10], ['6CK5_1_A', 'GGUUCC', '(...((', 16, 21], ['6CYT_1_N', 'CCUGGG', '((...)', 7, 12], ['6CZR_1_1a', 'CCAGCG', '((..((', 1095, 1100], ['6D12_1_C', 'CUGCAU', '((((..', 3, 8], ['6DME_1_A', 'UACCUA', '((((..', 6, 11], ['6DN2_1_Y-X', 'UUGGUG', '((((..', 61, 66], ['6DTD_1_C', 'UUGCAU', '(((..(', 2, 7], ['6DU4_1_B', 'UGGCGU', '((((..', 3, 8], ['6DVK_1_H', 'AUGGAU', '..((((', 6, 11], ['6E8T_1_D', 'GAAGGA', '(((...', 4, 9], ['6ERI_1_AA', 'GGUAGC', '....((', 1923, 1928], ['6EZ0_1_A', 'GCGGGG', '(((..(', 3, 8], ['6FF4_1_6', 'CCUGCG', '(((...', 61, 66], ['6FQL_1_B', 'AUUUAA', '((...)', 3, 8], ['6FYY_1_1', 'AGGGCU', '((((..', 22, 27], ['6G63_1_B', 'AAAAAA', '((.(..', 6, 11], ['6GAZ_1_AV', 'CAGCUA', '.((((.', 8, 13], ['6GBM_1_A', 'AUUACA', '((.(..', 5, 10], ['6GSK_1_1K', 'CGCACC', '..((((', 21, 26], ['6GSL_1_1L', 'GGUgCG', '((....', 27, 32], ['6GSL_1_3L', 'UCGGAG', '..((((', 45, 50], ['6GZ4_1_Bw', 'GUCCUG', '...(((', 45, 50], ['6HTQ_1_u', 'GGAUUG', '(((...', 28, 33], ['6HTQ_1_v', 'GGGUUC', '(((...', 61, 66], ['6IA2_1_A-B', 'GGAGUU', '.(.(((', 9, 14], ['6KUK_1_V-R', 'GCAGUA', '((....', 9, 14], ['6KUR_1_V-R', 'GCAGCA', '...((.', 11, 16], ['6LQP_1_SA-5A-3A', 'ACUGUG', '.((.(.', 836, 841], ['6LSF_1_C-B', 'CUCUCA', '(.((..', 5, 10], ['6LT7_1_C', 'GCUACA', '((....', 8, 13], ['6LTU_1_B', 'AAAUCC', '....((', 2, 7], ['6LXD_1_D', 'CAGCAG', '((.(..', 10, 15], ['6M0X_1_B', 'UACUCG', '((.((.', 28, 33], ['6MCB_1_B', 'ACGCGU', '....((', 15, 20], ['6ME0_1_A', 'AUGGUG', '..((((', 221, 226], ['6MFN_1_E-C', 'ACAGUU', '((((..', 3, 8], ['6MJ0_1_B', 'CUGCGA', '((((..', 44, 49], ['6MKN_1_X-W', 'UgCGAA', '.(((..', 3, 8], ['6N4O_1_C-D', 'GCAAUG', '...(((', 8, 13], ['6N8F_1_A-B', 'CUUACG', '..((((', 5, 10], ['6N8H_1_A-B', 'GGCAUC', '((..((', 2, 7], ['6NEQ_1_A', 'ACUUGG', '..)(((', 513, 518], ['6NOA_5_A', 'AACUGC', '((.((.', 14, 19], ['6NY2_1_B', 'UGGAGC', '((..]]', 16, 21], ['6O5F_1_D-C', 'AGAGUG', '.((.((', 14, 19], ['6OGZ_1_B-C', 'UAAUAU', '((....', 16, 21], ['6OL3_1_C', 'CGGUUA', '(((..[', 71, 76], ['6P7M_1_B', 'UUUCUA', '..((((', 2, 7], ['6PMO_1_A', 'UGGGUG', '..(.((', 3, 8], ['6PZQ_1_J-I', 'UAAUAG', '((....', 2, 7], ['6Q8V_1_A', 'GACCGG', '..(())', 6, 11], ['6Q9A_1_4', 'UAGUUU', '...(((', 245, 250], ['6Q9A_1_7', 'GCGGUU', '((((..', 49, 54], ['6QDV_1_2-6', 'GCAUGG', ')).((.', 173, 178], ['6QIT_1_A-B', 'CAGCGC', '..(())', 4, 9], ['6QKL_1_N', 'UCGGCU', '.((((.', 888, 893], ['6QW6_1_4', 'CAGUAU', '....((', 15, 20], ['6QX9_1_2', 'UGGAGC', '....((', 52, 57], ['6R5Q_1_3', 'GACUUA', '((....', 28, 33], ['6R6G_1_AF', 'CCGGCC', '..((((', 136, 141], ['6R6P_1_2', 'CACGUU', '.)).((', 22, 27], ['6RM3_1_L70', 'CCAUAU', '(....(', 8, 13], ['6RM3_1_S60', 'CGGCUU', '((((..', 762, 767], ['6SXO_1_L8', 'GCAGCU', '((.[[.', 3, 8], ['6SY6_1_D', 'GGCCUU', '.(((..', 14, 19], ['6T0S_1_V-M', 'GAUUUU', '...(((', 11, 16], ['6T0V_1_R-M', 'UUCUGC', '((....', 11, 16], ['6TNU_1_m', 'CUCAGU', '(((...', 10, 15], ['6UFG_1_A', 'AACGGC', '...(((', 36, 41], ['6UFM_1_B', 'UCGGAA', '((((..', 30, 35], ['6VAR_6_A', 'GCUGUG', '((...)', 29, 34], ['6VZC_1_A', 'UGCUUC', '(((...', 9, 14], ['6WDR_1_2', 'UUGAGU', '....((', 691, 696], ['6WQN_1_2', 'CCUGUU', '.((.(.', 26, 31], ['6XXB_1_A', 'AUUAUA', '((((..', 4, 9], ['6YDP_1_BA', 'ACCCCA', '((....', 392, 397], ['6YWS_1_A', 'AAGGGA', '..(((.', 834, 839], ['6Z1P_1_Ab-Aa', 'GUAUAA', '([((..', 1900, 1905], ['6Z1P_1_Bb-Ba', 'GAUAGC', '((((..', 414, 419], ['6Z6B_1_HHH-XXX', 'AGUACA', '(((...', 5, 10], ['6Z6M_1_CC', 'GGACUU', '(((...', 28, 33], ['6Z8K_1_P-T', 'GUGCGU', '((.().', 6, 11], ['6ZDP_1_B', 'UUCCUA', '..((..', 17, 22], ['6ZJ3_1_LE', 'CAACCA', '...(.(', 494, 499], ['6ZJ3_1_LH-LG', 'GCUCUG', '((((..', 456, 461], ['6ZJ3_1_LK', 'AGAGCA', '...(((', 11, 16], ['6ZJ3_1_LO', 'GGUGGG', '(..((.', 81, 86], ['6ZM6_1_w', 'UAGUUU', '..(((.', 7, 12], ['6ZQA_1_D3-D2-D4', 'ACGAUA', '.((((.', 579, 584], ['6ZQD_1_D4-D2', 'CCCAGA', '((....', 175, 180], ['6ZU5_1_S60', 'GCGGCG', '((..((', 160, 165], ['6ZYM_1_6', 'CCUGCG', '(((...', 61, 66], ['7A0S_1_X', 'UAGACU', '))..((', 643, 648], ['7B5K_1_z', 'UGGCUC', '..((((', 7, 12], ['7C79_1_A', 'UCACAA', '((....', 20, 25], ['7CTT_1_T-Q', 'UAACUA', '((..))', 14, 19], ['7D12_1_A', 'AGCAGC', '.((.((', 2, 7], ['7D6Z_1_3', 'UCAGUC', '((....', 10, 15], ['7D7W_1_A', 'GACGAA', '(((...', 23, 28], ['7DCO_1_B', 'UCAAGA', '((....', 38, 43], ['7DCO_1_H-F', 'ACAAAG', '..((((', 90, 95], ['7EAG_1_C-D-E-F-A-B', 'GCUGGA', '(((...', 67, 72], ['7EL1_1_B', 'GGCAAA', '(((...', 56, 61], ['7EOG_1_A', 'CUGGCG', '(..(((', 5, 10], ['7EZ2_1_N', 'CAAGUC', '...(((', 200, 205], ['7JIL_1_1', 'GUGAUG', '((...(', 1397, 1402], ['7JIL_1_2', 'GCACAA', '(.((..', 897, 902], ['7JJU_1_A-B', 'AGCAUA', '(((...', 10, 15], ['7JU1_2_X', 'UCUGAG', '...(((', 6, 11], ['7K4L_2_A', 'CGUUUC', '(((...', 15, 20], ['7KGB_1_A', 'CGGGUU', '.(((..', 1502, 1507], ['7KGB_1_B', 'CCGAUG', '((....', 68, 73], ['7KJT_1_A', 'CCUGAA', '((((..', 26, 31], ['7LO9_1_A-B', 'CGAUAG', '(....(', 2, 7], ['7LYF_1_A', 'UAGUCU', '(((..(', 36, 41], ['7M50_1_bb-qq', 'AAAAAU', '(.((.)', 4, 9], ['7MLW_1_F', 'CGCUAG', '.((..(', 4, 9], ['7NHK_1_D', 'AGGUUC', '(((..]', 51, 56], ['7NHM_1_D', 'AGCAGU', '(((...', 10, 15], ['7O1A_1_B8', 'GUCGGA', '...(((', 44, 49], ['7O5B_1_U', 'GCGGGU', '.(((..', 49, 54], ['7O7Y_1_AT', 'GUCCUG', '...(((', 33, 38], ['7O7Z_1_AH', 'AGGCAC', '((((..', 61, 66], ['7OJK_1_D-E', 'AGGAUG', '(((...', 4, 9], ['7OJN_1_R-M', 'GCGUAC', '(((..)', 8, 13], ['7OLC_1_3', 'CCAUAC', '(....(', 8, 13], ['7OM7_1_H-G', 'UUCAAA', '((..))', 4, 9], ['7ONU_1_T', 'GACUGU', '((....', 25, 30], ['7OQE_1_2', 'CCUCGC'

In [ ]:
mixs2 = pd.DataFrame(columns=['ID', 'start', 'end', 'seq', 'braq', 'chain'])
for i, mix in enumerate(mixs_seqs):
    mixs2.loc[i] = [ mix[0][:mix[0].find('_')], mix[-2], mix[-1], mix[1], mix[2], mix[0].split('_')[2]]
mixs = mixs2[~mixs2['chain'].str.contains('-')]
mixs = mixs[~mixs['ID'].duplicated()]
mixs = mixs.reset_index(drop=True)
mixs

       ID  start  end     seq    braq chain
0    1A9L      6   11  CUCCAG  ((((..     A
1    1AFX      2    7  UGUGAA  ((....     A
2    1AJF      4    9  GGGGAA  (((...     A
3    1AKX     11   16  GCCUGG  ((....     A
4    1ANR     10   15  AGCCUG  (((...     A
..    ...    ...  ...     ...     ...   ...
348  7PD3      5   10  UGUAGC  ((....     B
349  7PLA     99  104  UCACCC  (..(((     B
350  7QEP     23   28  AGCACC  ...(((     2
351  7RYG     17   22  GAGUGA  (((...     B
352  7SAM     94   99  GGGCUU  .(.(((     A

[353 rows x 6 columns]

In [ ]:
mixs = pd.DataFrame(columns=['ID', 'start', 'end', 'seq', 'braq', 'chain'])
for i, mix in enumerate(mixs_seqs):
    mixs.loc[i] = [ mix[0][:mix[0].find('_')], mix[-2], mix[-1], mix[1], mix[2], mix[0].split('_')[2]]
mixs = mixs[~mixs['chain'].str.contains('-')]
mixs = mixs[~mixs['ID'].duplicated()]
mixs = mixs.reset_index(drop=True)
mixs

       ID  start  end     seq    braq chain
0    1A9L      6   11  CUCCAG  ((((..     A
1    1AFX      2    7  UGUGAA  ((....     A
2    1AJF      4    9  GGGGAA  (((...     A
3    1AKX     11   16  GCCUGG  ((....     A
4    1ANR     10   15  AGCCUG  (((...     A
..    ...    ...  ...     ...     ...   ...
348  7PD3      5   10  UGUAGC  ((....     B
349  7PLA     99  104  UCACCC  (..(((     B
350  7QEP     23   28  AGCACC  ...(((     2
351  7RYG     17   22  GAGUGA  (((...     B
352  7SAM     94   99  GGGCUU  .(.(((     A

[353 rows x 6 columns]

In [ ]:
pdbl = PDB.PDBList()   
pdbl.download_pdb_files(mixs['ID'], file_format='mmCif', pdir='./mmCIF_files/')

In [ ]:
#zrobic to i dodac do funkcji wydobywajacej jesli plik w folderze -> jeśli nie wystarczy plikow to wznowić pobieranie wyzej
mix_complete = []
for index, row in mixs.iterrows():
    seqs = list(range(int(row['start']), int(row['end']+1)))
    mix_complete.append([row['ID'], row['chain'], seqs])

print(len(mix_complete))
mix_complete

353

[['1A9L', 'A', [6, 7, 8, 9, 10, 11]],
 ['1AFX', 'A', [2, 3, 4, 5, 6, 7]],
 ['1AJF', 'A', [4, 5, 6, 7, 8, 9]],
 ['1AKX', 'A', [11, 12, 13, 14, 15, 16]],
 ['1ANR', 'A', [10, 11, 12, 13, 14, 15]],
 ['1ARJ', 'N', [7, 8, 9, 10, 11, 12]],
 ['1ATO', 'A', [4, 5, 6, 7, 8, 9]],
 ['1ATV', 'A', [2, 3, 4, 5, 6, 7]],
 ['1ATW', 'A', [3, 4, 5, 6, 7, 8]],
 ['1BGZ', 'A', [7, 8, 9, 10, 11, 12]],
 ['1CQL', 'A', [10, 11, 12, 13, 14, 15]],
 ['1D6K', 'B', [3, 4, 5, 6, 7, 8]],
 ['1E4P', 'A', [8, 9, 10, 11, 12, 13]],
 ['1E7K', 'C', [6, 7, 8, 9, 10, 11]],
 ['1EBR', 'A', [4, 5, 6, 7, 8, 9]],
 ['1EC6', 'C', [2, 3, 4, 5, 6, 7]],
 ['1EHT', 'A', [6, 7, 8, 9, 10, 11]],
 ['1ESH', 'A', [2, 3, 4, 5, 6, 7]],
 ['1F1T', 'A', [8, 9, 10, 11, 12, 13]],
 ['1F27', 'A', [3, 4, 5, 6, 7, 8]],
 ['1F5U', 'A', [5, 6, 7, 8, 9, 10]],
 ['1F85', 'A', [2, 3, 4, 5, 6, 7]],
 ['1FMN', 'A', [13, 14, 15, 16, 17, 18]],
 ['1FYP', 'A', [2, 3, 4, 5, 6, 7]],
 ['1GAX', 'D', [26, 27, 28, 29, 30, 31]],
 ['1HJI', 'A', [3, 4, 5, 6, 7, 8]],
 ['1HMH', 'E', [12, 13, 14, 15, 16, 17]],
 ['1I46', 'A', [2, 3, 4, 5, 6, 7]],
 ['1I4C', 'A', [3, 4, 5, 6, 7, 8]],
 ['1IK1', 'A', [2, 3, 4, 5, 6, 7]],
 ['1IKD', 'A', [3, 4, 5, 6, 7, 8]],
 ['1JO7', 'A', [11, 12, 13, 14, 15, 16]],
 ['1JZC', 'A', [3, 4, 5, 6, 7, 8]],
 ['1K4A', 'A', [3, 4, 5, 6, 7, 8]],
 ['1K4B', 'A', [3, 4, 5, 6, 7, 8]],
 ['1K5I', 'A', [6, 7, 8, 9, 10, 11]],
 ['1KKS', 'A', [6, 7, 8, 9, 10, 11]],
 ['1KPD', 'A', [3, 4, 5, 6, 7, 8]],
 ['1KUQ', 'B', [26, 27, 28, 29, 30, 31]],
 ['1LC6', 'A', [5, 6, 7, 8, 9, 10]],
 ['1LU3', 'A', [3, 4, 5, 6, 7, 8]],
 ['1M5L', 'A', [5, 6, 7, 8, 9, 10]],
 ['1MFK', 'A', [8, 9, 10, 11, 12, 13]],
 ['1MFQ', 'A', [82, 83, 84, 85, 86, 87]],
 ['1MFY', 'A', [12, 13, 14, 15, 16, 17]],
 ['1N78', 'C', [28, 29, 30, 31, 32, 33]],
 ['1OOA', 'C', [8, 9, 10, 11, 12, 13]],
 ['1OQ0', 'A', [2, 3, 4, 5, 6, 7]],
 ['1OSW', 'A', [3, 4, 5, 6, 7, 8]],
 ['1OW9', 'A', [3, 4, 5, 6, 7, 8]],
 ['1P5N', 'A', [3, 4, 5, 6, 7, 8]],
 ['1P5P', 'A', [20, 21, 22, 23, 24, 25]],
 ['1QD3', 'A', [4, 5, 6, 7, 8, 9]],
 ['1QWA', 'A', [5, 6, 7, 8, 9, 10]],
 ['1QWB', 'A', [2, 3, 4, 5, 6, 7]],
 ['1RAW', 'A', [2, 3, 4, 5, 6, 7]],
 ['1RFR', 'A', [9, 10, 11, 12, 13, 14]],
 ['1RKJ', 'B', [3, 4, 5, 6, 7, 8]],
 ['1S03', 'A', [8, 9, 10, 11, 12, 13]],
 ['1S9S', 'A', [5, 6, 7, 8, 9, 10]],
 ['1TFN', 'A', [6, 7, 8, 9, 10, 11]],
 ['1TJZ', 'A', [2, 3, 4, 5, 6, 7]],
 ['1TLR', 'A', [6, 7, 8, 9, 10, 11]],
 ['1TXS', 'A', [3, 4, 5, 6, 7, 8]],
 ['1U63', 'D', [10, 11, 12, 13, 14, 15]],
 ['1UN6', 'F', [31, 32, 33, 34, 35, 36]],
 ['1UTS', 'B', [10, 11, 12, 13, 14, 15]],
 ['1UUU', 'A', [3, 4, 5, 6, 7, 8]],
 ['1X8W', 'C', [17, 18, 19, 20, 21, 22]],
 ['1XSH', 'A', [10, 11, 12, 13, 14, 15]],
 ['1ZBH', 'F', [4, 5, 6, 7, 8, 9]],
 ['1ZBN', 'A', [3, 4, 5, 6, 7, 8]],
 ['1ZIF', 'A', [2, 3, 4, 5, 6, 7]],
 ['1ZL3', 'B', [5, 6, 7, 8, 9, 10]],
 ['28SR', 'A', [4, 5, 6, 7, 8, 9]],
 ['2A9X', '2', [4, 5, 6, 7, 8, 9]],
 ['2AU4', 'A', [15, 16, 17, 18, 19, 20]],
 ['2BTE', 'B', [38, 39, 40, 41, 42, 43]],
 ['2C4Q', 'R', [5, 6, 7, 8, 9, 10]],
 ['2CSX', 'C', [46, 47, 48, 49, 50, 51]],
 ['2D1B', 'A', [12, 13, 14, 15, 16, 17]],
 ['2DU3', 'D', [5, 6, 7, 8, 9, 10]],
 ['2ES5', 'A', [8, 9, 10, 11, 12, 13]],
 ['2FDT', 'A', [6, 7, 8, 9, 10, 11]],
 ['2GIO', 'A', [7, 8, 9, 10, 11, 12]],
 ['2GV3', 'A', [4, 5, 6, 7, 8, 9]],
 ['2IHX', 'B', [37, 38, 39, 40, 41, 42]],
 ['2IY5', 'T', [44, 45, 46, 47, 48, 49]],
 ['2IZN', 'R', [3, 4, 5, 6, 7, 8]],
 ['2JSE', 'A', [5, 6, 7, 8, 9, 10]],
 ['2JTP', 'A', [9, 10, 11, 12, 13, 14]],
 ['2JUK', 'A', [5, 6, 7, 8, 9, 10]],
 ['2JWV', 'A', [5, 6, 7, 8, 9, 10]],
 ['2JYH', 'B', [15, 16, 17, 18, 19, 20]],
 ['2KF0', 'A', [5, 6, 7, 8, 9, 10]],
 ['2KHY', 'A', [4, 5, 6, 7, 8, 9]],
 ['2KMJ', 'A', [9, 10, 11, 12, 13, 14]],
 ['2KPC', 'A', [2, 3, 4, 5, 6, 7]],
 ['2KRP', 'A', [2, 3, 4, 5, 6, 7]],
 ['2KU0', 'A', [8, 9, 10, 11, 12, 13]],
 ['2KVN', 'A', [3, 4, 5, 6, 7, 8]],
 ['2KXM', 'A', [3, 4, 5, 6, 7, 8]],
 ['2L6I', 'A', [2, 3, 4, 5, 6, 7]],
 ['2LA5', 'A', [4, 5, 6, 7, 8, 9]],
 ['2LBJ', 'A', [4, 5, 6, 7, 8, 9]],
 ['2LDT', 'A', [9, 10, 11, 12, 13, 14]],
 ['2LKR', 'A', [47, 48, 49, 50, 51, 52]],
 ['2M12', 'A', [5, 6, 7, 8, 9, 10]],
 ['2M22', 'A', [4, 5, 6, 7, 8, 9]],
 ['2M23', 'A', [5, 6, 7, 8, 9, 10]],
 ['2M57', 'A', [10, 11, 12, 13, 14, 15]],
 ['2MF0', 'G', [41, 42, 43, 44, 45, 46]],
 ['2MFC', 'B', [5, 6, 7, 8, 9, 10]],
 ['2MIY', 'A', [39, 40, 41, 42, 43, 44]],
 ['2MNC', 'A', [3, 4, 5, 6, 7, 8]],
 ['2MXL', 'A', [13, 14, 15, 16, 17, 18]],
 ['2N3Q', 'A', [33, 34, 35, 36, 37, 38]],
 ['2N6T', 'A', [3, 4, 5, 6, 7, 8]],
 ['2N7X', 'A', [4, 5, 6, 7, 8, 9]],
 ['2NBY', 'A', [5, 6, 7, 8, 9, 10]],
 ['2NBZ', 'A', [14, 15, 16, 17, 18, 19]],
 ['2NC0', 'A', [10, 11, 12, 13, 14, 15]],
 ['2NCI', 'A', [9, 10, 11, 12, 13, 14]],
 ['2OIU', 'Q', [20, 21, 22, 23, 24, 25]],
 ['2OM7', 'C', [32, 33, 34, 35, 36, 37]],
 ['2OOM', 'A', [2, 3, 4, 5, 6, 7]],
 ['2P89', 'A', [12, 13, 14, 15, 16, 17]],
 ['2QH3', 'A', [6, 7, 8, 9, 10, 11]],
 ['2QH4', 'A', [2, 3, 4, 5, 6, 7]],
 ['2R8S', 'R', [11, 12, 13, 14, 15, 16]],
 ['2RKJ', 'C', [113, 114, 115, 116, 117, 118]],
 ['2RLU', 'A', [5, 6, 7, 8, 9, 10]],
 ['2RN1', 'A', [3, 4, 5, 6, 7, 8]],
 ['2VPL', 'B', [9, 10, 11, 12, 13, 14]],
 ['2WW9', 'D', [22, 23, 24, 25, 26, 27]],
 ['2WWB', 'E', [6, 7, 8, 9, 10, 11]],
 ['2Y8Y', 'B', [5, 6, 7, 8, 9, 10]],
 ['2Y9H', 'J', [4, 5, 6, 7, 8, 9]],
 ['3AM1', 'B', [5, 6, 7, 8, 9, 10]],
 ['3BO0', 'G', [13, 14, 15, 16, 17, 18]],
 ['3BO1', 'D', [7, 8, 9, 10, 11, 12]],
 ['3EGZ', 'B', [3, 4, 5, 6, 7, 8]],
 ['3EPH', 'E', [43, 44, 45, 46, 47, 48]],
 ['3HHN', 'E', [49, 50, 51, 52, 53, 54]],
 ['3IWN', 'A', [50, 51, 52, 53, 54, 55]],
 ['3J0O', '2', [57, 58, 59, 60, 61, 62]],
 ['3J16', 'J', [135, 136, 137, 138, 139, 140]],
 ['3J45', '2', [15, 16, 17, 18, 19, 20]],
 ['3J6B', 'e', [4, 5, 6, 7, 8, 9]],
 ['3J79', 'B', [29, 30, 31, 32, 33, 34]],
 ['3J7R', 'S6', [10, 11, 12, 13, 14, 15]],
 ['3J92', '2', [44, 45, 46, 47, 48, 49]],
 ['3JCS', '5', [32, 33, 34, 35, 36, 37]],
 ['3K1V', 'A', [2, 3, 4, 5, 6, 7]],
 ['3OIN', 'C', [2, 3, 4, 5, 6, 7]],
 ['3P22', 'A', [14, 15, 16, 17, 18, 19]],
 ['3RG5', 'B', [13, 14, 15, 16, 17, 18]],
 ['3TUP', 'T', [9, 10, 11, 12, 13, 14]],
 ['3U4M', 'B', [12, 13, 14, 15, 16, 17]],
 ['3UZS', 'C', [6, 7, 8, 9, 10, 11]],
 ['3WFS', 'A', [5, 6, 7, 8, 9, 10]],
 ['486D', 'A', [3, 4, 5, 6, 7, 8]],
 ['4A4T', 'A', [6, 7, 8, 9, 10, 11]],
 ['4A4U', 'A', [6, 7, 8, 9, 10, 11]],
 ['4AL5', 'B', [4, 5, 6, 7, 8, 9]],
 ['4BY9', 'A', [3, 4, 5, 6, 7, 8]],
 ['4C8Y', 'C', [2, 3, 4, 5, 6, 7]],
 ['4C8Z', 'C', [3, 4, 5, 6, 7, 8]],
 ['4C9D', 'D', [2, 3, 4, 5, 6, 7]],
 ['4D61', 'j', [98, 99, 100, 101, 102, 103]],
 ['4GXY', 'A', [34, 35, 36, 37, 38, 39]],
 ['4JF2', 'A', [57, 58, 59, 60, 61, 62]],
 ['4KJI', 'C', [2, 3, 4, 5, 6, 7]],
 ['4KQY', 'A', [11, 12, 13, 14, 15, 16]],
 ['4KR6', 'C', [16, 17, 18, 19, 20, 21]],
 ['4LCK', 'F', [3, 4, 5, 6, 7, 8]],
 ['4LX6', 'A', [45, 46, 47, 48, 49, 50]],
 ['4MGN', 'A', [23, 24, 25, 26, 27, 28]],
 ['4N0T', 'B', [38, 39, 40, 41, 42, 43]],
 ['4P8Z', 'A', [37, 38, 39, 40, 41, 42]],
 ['4P95', 'A', [46, 47, 48, 49, 50, 51]],
 ['4PR6', 'B', [42, 43, 44, 45, 46, 47]],
 ['4QEI', 'C', [6, 7, 8, 9, 10, 11]],
 ['4TUE', 'QV', [46, 47, 48, 49, 50, 51]],
 ['4TUW', 'C', [11, 12, 13, 14, 15, 16]],
 ['4UER', 'A', [1451, 1452, 1453, 1454, 1455, 1456]],
 ['4UJD', 'BC', [23, 24, 25, 26, 27, 28]],
 ['4UYK', 'R', [35, 36, 37, 38, 39, 40]],
 ['4V49', 'B0', [2382, 2383, 2384, 2385, 2386, 2387]],
 ['4V4N', 'A3', [7, 8, 9, 10, 11, 12]],
 ['4V6D', 'CV', [3, 4, 5, 6, 7, 8]],
 ['4V6U', 'A2', [1024, 1025, 1026, 1027, 1028, 1029]],
 ['4V7E', 'Ae', [25, 26, 27, 28, 29, 30]],
 ['4V7H', 'AA', [1551, 1552, 1553, 1554, 1555, 1556]],
 ['4V88', 'A6', [1477, 1478, 1479, 1480, 1481, 1482]],
 ['4V8M', 'BE', [29, 30, 31, 32, 33, 34]],
 ['4V8N', 'CV', [46, 47, 48, 49, 50, 51]],
 ['4V9Q', 'DV', [47, 48, 49, 50, 51, 52]],
 ['4WF9', 'X', [640, 641, 642, 643, 644, 645]],
 ['4WQ1', '3K', [26, 27, 28, 29, 30, 31]],
 ['4WSM', '1K', [53, 54, 55, 56, 57, 58]],
 ['4WT8', 'DV', [6, 7, 8, 9, 10, 11]],
 ['4Y1M', 'B', [78, 79, 80, 81, 82, 83]],
 ['4YAZ', 'R', [15, 16, 17, 18, 19, 20]],
 ['4YYE', 'C', [4, 5, 6, 7, 8, 9]],
 ['4Z7K', 'C', [5, 6, 7, 8, 9, 10]],
 ['4ZLD', 'B', [3, 4, 5, 6, 7, 8]],
 ['5A18', 'A', [9, 10, 11, 12, 13, 14]],
 ['5B2P', 'B', [23, 24, 25, 26, 27, 28]],
 ['5B63', 'D', [7, 8, 9, 10, 11, 12]],
 ['5BJO', 'E', [16, 17, 18, 19, 20, 21]],
 ['5BTM', 'A', [13, 14, 15, 16, 17, 18]],
 ['5BTP', 'B', [21, 22, 23, 24, 25, 26]],
 ['5CCB', 'N', [8, 9, 10, 11, 12, 13]],
 ['5D5L', 'A', [25, 26, 27, 28, 29, 30]],
 ['5D8H', 'A', [18, 19, 20, 21, 22, 23]],
 ['5DCV', 'D', [10, 11, 12, 13, 14, 15]],
 ['5DDO', 'B', [7, 8, 9, 10, 11, 12]],
 ['5E81', '3L', [9, 10, 11, 12, 13, 14]],
 ['5EL4', '3L', [47, 48, 49, 50, 51, 52]],
 ['5F5F', 'B', [3, 4, 5, 6, 7, 8]],
 ['5F5H', 'C', [4, 5, 6, 7, 8, 9]],
 ['5FLX', 'z', [25, 26, 27, 28, 29, 30]],
 ['5G2X', 'A', [529, 530, 531, 532, 533, 534]],
 ['5IBB', '1L', [9, 10, 11, 12, 13, 14]],
 ['5ID6', 'G', [7, 8, 9, 10, 11, 12]],
 ['5J1O', 'B', [10, 11, 12, 13, 14, 15]],
 ['5J2W', 'B', [12, 13, 14, 15, 16, 17]],
 ['5J7L', 'DA', [815, 816, 817, 818, 819, 820]],
 ['5KQE', 'A', [16, 17, 18, 19, 20, 21]],
 ['5L1Z', 'N', [6, 7, 8, 9, 10, 11]],
 ['5MRC', 'A', [1548, 1549, 1550, 1551, 1552, 1553]],
 ['5MYJ', 'AA', [149, 150, 151, 152, 153, 154]],
 ['5N5C', 'A', [4, 5, 6, 7, 8, 9]],
 ['5T5H', 'B', [379, 380, 381, 382, 383, 384]],
 ['5T7V', 'D', [4, 5, 6, 7, 8, 9]],
 ['5TPY', 'A', [11, 12, 13, 14, 15, 16]],
 ['5UDZ', 'W', [4, 5, 6, 7, 8, 9]],
 ['5UZ6', 'A', [2, 3, 4, 5, 6, 7]],
 ['5V17', 'A', [18, 19, 20, 21, 22, 23]],
 ['5V3F', 'A', [2, 3, 4, 5, 6, 7]],
 ['5V93', 'a', [55, 56, 57, 58, 59, 60]],
 ['5VJ9', 'C', [4, 5, 6, 7, 8, 9]],
 ['5VPO', 'XV', [2, 3, 4, 5, 6, 7]],
 ['5VW1', 'C', [56, 57, 58, 59, 60, 61]],
 ['5VYC', 'i2', [828, 829, 830, 831, 832, 833]],
 ['5WLH', 'B', [8, 9, 10, 11, 12, 13]],
 ['5XTM', 'D', [3, 4, 5, 6, 7, 8]],
 ['5XWP', 'C', [6, 7, 8, 9, 10, 11]],
 ['5XXB', '3', [68, 69, 70, 71, 72, 73]],
 ['5XY3', '3', [30, 31, 32, 33, 34, 35]],
 ['5Y58', 'X', [9, 10, 11, 12, 13, 14]],
 ['5Y85', 'D', [9, 10, 11, 12, 13, 14]],
 ['5ZAM', 'C', [10, 11, 12, 13, 14, 15]],
 ['6AAX', 'B', [8, 9, 10, 11, 12, 13]],
 ['6AGB', 'A', [53, 54, 55, 56, 57, 58]],
 ['6AH3', 'T', [32, 33, 34, 35, 36, 37]],
 ['6AZ1', '1', [304, 305, 306, 307, 308, 309]],
 ['6AZ4', 'A', [13, 14, 15, 16, 17, 18]],
 ['6CK5', 'A', [16, 17, 18, 19, 20, 21]],
 ['6CYT', 'N', [7, 8, 9, 10, 11, 12]],
 ['6CZR', '1a', [1095, 1096, 1097, 1098, 1099, 1100]],
 ['6D12', 'C', [3, 4, 5, 6, 7, 8]],
 ['6DME', 'A', [6, 7, 8, 9, 10, 11]],
 ['6DTD', 'C', [2, 3, 4, 5, 6, 7]],
 ['6DU4', 'B', [3, 4, 5, 6, 7, 8]],
 ['6DVK', 'H', [6, 7, 8, 9, 10, 11]],
 ['6E8T', 'D', [4, 5, 6, 7, 8, 9]],
 ['6ERI', 'AA', [1923, 1924, 1925, 1926, 1927, 1928]],
 ['6EZ0', 'A', [3, 4, 5, 6, 7, 8]],
 ['6FF4', '6', [61, 62, 63, 64, 65, 66]],
 ['6FQL', 'B', [3, 4, 5, 6, 7, 8]],
 ['6FYY', '1', [22, 23, 24, 25, 26, 27]],
 ['6G63', 'B', [6, 7, 8, 9, 10, 11]],
 ['6GAZ', 'AV', [8, 9, 10, 11, 12, 13]],
 ['6GBM', 'A', [5, 6, 7, 8, 9, 10]],
 ['6GSK', '1K', [21, 22, 23, 24, 25, 26]],
 ['6GSL', '1L', [27, 28, 29, 30, 31, 32]],
 ['6GZ4', 'Bw', [45, 46, 47, 48, 49, 50]],
 ['6HTQ', 'u', [28, 29, 30, 31, 32, 33]],
 ['6LT7', 'C', [8, 9, 10, 11, 12, 13]],
 ['6LTU', 'B', [2, 3, 4, 5, 6, 7]],
 ['6LXD', 'D', [10, 11, 12, 13, 14, 15]],
 ['6M0X', 'B', [28, 29, 30, 31, 32, 33]],
 ['6MCB', 'B', [15, 16, 17, 18, 19, 20]],
 ['6ME0', 'A', [221, 222, 223, 224, 225, 226]],
 ['6MJ0', 'B', [44, 45, 46, 47, 48, 49]],
 ['6NEQ', 'A', [513, 514, 515, 516, 517, 518]],
 ['6NOA', 'A', [14, 15, 16, 17, 18, 19]],
 ['6NY2', 'B', [16, 17, 18, 19, 20, 21]],
 ['6OL3', 'C', [71, 72, 73, 74, 75, 76]],
 ['6P7M', 'B', [2, 3, 4, 5, 6, 7]],
 ['6PMO', 'A', [3, 4, 5, 6, 7, 8]],
 ['6Q8V', 'A', [6, 7, 8, 9, 10, 11]],
 ['6Q9A', '4', [245, 246, 247, 248, 249, 250]],
 ['6QKL', 'N', [888, 889, 890, 891, 892, 893]],
 ['6QW6', '4', [15, 16, 17, 18, 19, 20]],
 ['6QX9', '2', [52, 53, 54, 55, 56, 57]],
 ['6R5Q', '3', [28, 29, 30, 31, 32, 33]],
 ['6R6G', 'AF', [136, 137, 138, 139, 140, 141]],
 ['6R6P', '2', [22, 23, 24, 25, 26, 27]],
 ['6RM3', 'L70', [8, 9, 10, 11, 12, 13]],
 ['6SXO', 'L8', [3, 4, 5, 6, 7, 8]],
 ['6SY6', 'D', [14, 15, 16, 17, 18, 19]],
 ['6TNU', 'm', [10, 11, 12, 13, 14, 15]],
 ['6UFG', 'A', [36, 37, 38, 39, 40, 41]],
 ['6UFM', 'B', [30, 31, 32, 33, 34, 35]],
 ['6VAR', 'A', [29, 30, 31, 32, 33, 34]],
 ['6VZC', 'A', [9, 10, 11, 12, 13, 14]],
 ['6WDR', '2', [691, 692, 693, 694, 695, 696]],
 ['6WQN', '2', [26, 27, 28, 29, 30, 31]],
 ['6XXB', 'A', [4, 5, 6, 7, 8, 9]],
 ['6YDP', 'BA', [392, 393, 394, 395, 396, 397]],
 ['6YWS', 'A', [834, 835, 836, 837, 838, 839]],
 ['6Z6M', 'CC', [28, 29, 30, 31, 32, 33]],
 ['6ZDP', 'B', [17, 18, 19, 20, 21, 22]],
 ['6ZJ3', 'LE', [494, 495, 496, 497, 498, 499]],
 ['6ZM6', 'w', [7, 8, 9, 10, 11, 12]],
 ['6ZU5', 'S60', [160, 161, 162, 163, 164, 165]],
 ['6ZYM', '6', [61, 62, 63, 64, 65, 66]],
 ['7A0S', 'X', [643, 644, 645, 646, 647, 648]],
 ['7B5K', 'z', [7, 8, 9, 10, 11, 12]],
 ['7C79', 'A', [20, 21, 22, 23, 24, 25]],
 ['7D12', 'A', [2, 3, 4, 5, 6, 7]],
 ['7D6Z', '3', [10, 11, 12, 13, 14, 15]],
 ['7D7W', 'A', [23, 24, 25, 26, 27, 28]],
 ['7DCO', 'B', [38, 39, 40, 41, 42, 43]],
 ['7EL1', 'B', [56, 57, 58, 59, 60, 61]],
 ['7EOG', 'A', [5, 6, 7, 8, 9, 10]],
 ['7EZ2', 'N', [200, 201, 202, 203, 204, 205]],
 ['7JIL', '1', [1397, 1398, 1399, 1400, 1401, 1402]],
 ['7JU1', 'X', [6, 7, 8, 9, 10, 11]],
 ['7K4L', 'A', [15, 16, 17, 18, 19, 20]],
 ['7KGB', 'A', [1502, 1503, 1504, 1505, 1506, 1507]],
 ['7KJT', 'A', [26, 27, 28, 29, 30, 31]],
 ['7LYF', 'A', [36, 37, 38, 39, 40, 41]],
 ['7MLW', 'F', [4, 5, 6, 7, 8, 9]],
 ['7NHK', 'D', [51, 52, 53, 54, 55, 56]],
 ['7NHM', 'D', [10, 11, 12, 13, 14, 15]],
 ['7O1A', 'B8', [44, 45, 46, 47, 48, 49]],
 ['7O5B', 'U', [49, 50, 51, 52, 53, 54]],
 ['7O7Y', 'AT', [33, 34, 35, 36, 37, 38]],
 ['7O7Z', 'AH', [61, 62, 63, 64, 65, 66]],
 ['7OLC', '3', [8, 9, 10, 11, 12, 13]],
 ['7ONU', 'T', [25, 26, 27, 28, 29, 30]],
 ['7OQE', '2', [92, 93, 94, 95, 96, 97]],
 ['7OT5', 'z', [5, 6, 7, 8, 9, 10]],
 ['7OX9', 'A', [28, 29, 30, 31, 32, 33]],
 ['7PD3', 'B', [5, 6, 7, 8, 9, 10]],
 ['7PLA', 'B', [99, 100, 101, 102, 103, 104]],
 ['7QEP', '2', [23, 24, 25, 26, 27, 28]],
 ['7RYG', 'B', [17, 18, 19, 20, 21, 22]],
 ['7SAM', 'A', [94, 95, 96, 97, 98, 99]]]

In [ ]:
mix_databse, mix_sequences = get_atom_coordinates_hairpins(mix_complete, "C1'", mixs)

In [ ]:
mix_databse_normal, mix_sequences_normal = get_atom_coordinates_hairpins(mix_complete, "C1'", mixs)

In [ ]:
mix_databse

,N1,N2,N3,N4,N5,N6,id
0,[[[[[0. 0. 0.]]]]],[[[[[ 0.8041661 -4.231695 3.9205396]]]]],[[[[[-1.6692054 -9.162296 6.4352946]]]]],[[[[[ -5.333127 -12.891341 5.426225]]]]],[[[[[ -9.668938 -15.040167 3.60736 ]]]]],[[[[[-14.286301 -16.915585 4.959453]]]]],1A9L
1,[[[[[0. 0. 0.]]]]],[[[[[2.2150214 3.3096328 0.5295736]]]]],[[[[[ 1.6075337 7.957532 -0.9737557]]]]],[[[[[ 0.9699897 12.639562 -0.8365039]]]]],[[[[[ 3.7623687 13.40242 -5.625697 ]]]]],[[[[[ 5.630187 10.452166 -8.334042]]]]],1AFX
8,[[[[[0. 0. 0.]]]]],[[[[[ 0.15605938 3.3303156 -3.9849346 ]]]]],[[[[[-1.4434991 -0.8909395 -7.76858 ]]]]],[[[[[ 4.1391993 -0.03929734 -15.690323 ]]]]],[[[[[10.033092 0.17612684 -9.188676 ]]]]],[[[[[13.487843 0.3662275 -6.4784904]]]]],1ATW
9,[[[[[0. 0. 0.]]]]],[[[[[3.0142694 4.4707227 1.1858509]]]]],[[[[[ 5.06909 9.189758 -1.2028017]]]]],[[[[[ 4.280632 11.962079 -5.7178817]]]]],[[[[[ 7.4128475 17.110939 -7.885133 ]]]]],[[[[[ 3.4296734 13.0244465 -11.335644 ]]]]],1BGZ
10,[[[[[0. 0. 0.]]]]],[[[[[2.9372516 2.7519627 0.66500914]]]]],[[[[[7.0581474 5.542484 0.3005259]]]]],[[[[[ 8.809982 9.635785 -1.8804226]]]]],[[[[[ 7.8364873 14.935774 -2.744326 ]]]]],[[[[[ 7.856585 20.061682 -6.727885]]]]],1CQL
...,...,...,...,...,...,...,...
332,[[[[[0. 0. 0.]]]]],[[[[[-0.47233194 -2.9282975 -4.687508 ]]]]],[[[[[ -0.246485 -2.8869483 -10.225336 ]]]]],[[[[[ 1.8193166 0.5098891 -14.109901 ]]]]],[[[[[ 4.9302487 3.4682302 -19.761621 ]]]]],[[[[[ 3.776392 8.825617 -13.341036]]]]],7K4L
337,[[[[[0. 0. 0.]]]]],[[[[[ 2.7760942 -4.215409 -0.8059901]]]]],[[[[[ 5.3282084 -8.258112 -3.4288185]]]]],[[[[[ 8.946509 -10.297053 -7.8326945]]]]],[[[[[13.799988 -8.53124 -9.37788 ]]]]],[[[[[20.524422 -6.54585 -9.039848]]]]],7NHK
338,[[[[[0. 0. 0.]]]]],[[[[[-3.824939 0.59906626 4.209332 ]]]]],[[[[[-4.5126867 1.1054382 9.48693 ]]]]],[[[[[-2.7622252 0.3344388 15.188028 ]]]]],[[[[[ 0.981874 2.1118665 19.070124 ]]]]],[[[[[ 1.3004456 8.925248 20.478476 ]]]]],7NHM
351,[[[[[0. 0. 0.]]]]],[[[[[ 4.8985777 3.137473 -0.1275875]]]]],[[[[[ 9.460717 6.1442494 -2.3533962]]]]],[[[[[13.056042 9.18912 -5.854679]]]]],[[[[[14.632647 13.6115675 -9.166844 ]]]]],[[[[[21.398869 16.247992 -7.485231]]]]],7RYG
352,[[[[[0. 0. 0.]]]]],[[[[[-3.4062576 -5.4804854 2.782512 ]]]]],[[[[[-8.245827 -7.2860346 2.9901767]]]]],[[[[[-13.228863 -7.163368 0.93104553]]]]],[[[[[-16.79267 -6.918027 -3.9202144]]]]],[[[[[-17.49849 -7.3978167 -9.203032 ]]]]],7SAM

In [ ]:
mix_databse = mix_databse[mix_databse['id'].isin(mix_databse_normal['id'])]
mix_databse

,N1,N2,N3,N4,N5,N6,id
0,[[[[[0. 0. 0.]]]]],[[[[[ 0.8041661 -4.231695 3.9205396]]]]],[[[[[-1.6692054 -9.162296 6.4352946]]]]],[[[[[ -5.333127 -12.891341 5.426225]]]]],[[[[[ -9.668938 -15.040167 3.60736 ]]]]],[[[[[-14.286301 -16.915585 4.959453]]]]],1A9L
1,[[[[[0. 0. 0.]]]]],[[[[[2.2150214 3.3096328 0.5295736]]]]],[[[[[ 1.6075337 7.957532 -0.9737557]]]]],[[[[[ 0.9699897 12.639562 -0.8365039]]]]],[[[[[ 3.7623687 13.40242 -5.625697 ]]]]],[[[[[ 5.630187 10.452166 -8.334042]]]]],1AFX
8,[[[[[0. 0. 0.]]]]],[[[[[ 0.15605938 3.3303156 -3.9849346 ]]]]],[[[[[-1.4434991 -0.8909395 -7.76858 ]]]]],[[[[[ 4.1391993 -0.03929734 -15.690323 ]]]]],[[[[[10.033092 0.17612684 -9.188676 ]]]]],[[[[[13.487843 0.3662275 -6.4784904]]]]],1ATW
9,[[[[[0. 0. 0.]]]]],[[[[[3.0142694 4.4707227 1.1858509]]]]],[[[[[ 5.06909 9.189758 -1.2028017]]]]],[[[[[ 4.280632 11.962079 -5.7178817]]]]],[[[[[ 7.4128475 17.110939 -7.885133 ]]]]],[[[[[ 3.4296734 13.0244465 -11.335644 ]]]]],1BGZ
10,[[[[[0. 0. 0.]]]]],[[[[[2.9372516 2.7519627 0.66500914]]]]],[[[[[7.0581474 5.542484 0.3005259]]]]],[[[[[ 8.809982 9.635785 -1.8804226]]]]],[[[[[ 7.8364873 14.935774 -2.744326 ]]]]],[[[[[ 7.856585 20.061682 -6.727885]]]]],1CQL
...,...,...,...,...,...,...,...
332,[[[[[0. 0. 0.]]]]],[[[[[-0.47233194 -2.9282975 -4.687508 ]]]]],[[[[[ -0.246485 -2.8869483 -10.225336 ]]]]],[[[[[ 1.8193166 0.5098891 -14.109901 ]]]]],[[[[[ 4.9302487 3.4682302 -19.761621 ]]]]],[[[[[ 3.776392 8.825617 -13.341036]]]]],7K4L
337,[[[[[0. 0. 0.]]]]],[[[[[ 2.7760942 -4.215409 -0.8059901]]]]],[[[[[ 5.3282084 -8.258112 -3.4288185]]]]],[[[[[ 8.946509 -10.297053 -7.8326945]]]]],[[[[[13.799988 -8.53124 -9.37788 ]]]]],[[[[[20.524422 -6.54585 -9.039848]]]]],7NHK
338,[[[[[0. 0. 0.]]]]],[[[[[-3.824939 0.59906626 4.209332 ]]]]],[[[[[-4.5126867 1.1054382 9.48693 ]]]]],[[[[[-2.7622252 0.3344388 15.188028 ]]]]],[[[[[ 0.981874 2.1118665 19.070124 ]]]]],[[[[[ 1.3004456 8.925248 20.478476 ]]]]],7NHM
351,[[[[[0. 0. 0.]]]]],[[[[[ 4.8985777 3.137473 -0.1275875]]]]],[[[[[ 9.460717 6.1442494 -2.3533962]]]]],[[[[[13.056042 9.18912 -5.854679]]]]],[[[[[14.632647 13.6115675 -9.166844 ]]]]],[[[[[21.398869 16.247992 -7.485231]]]]],7RYG
352,[[[[[0. 0. 0.]]]]],[[[[[-3.4062576 -5.4804854 2.782512 ]]]]],[[[[[-8.245827 -7.2860346 2.9901767]]]]],[[[[[-13.228863 -7.163368 0.93104553]]]]],[[[[[-16.79267 -6.918027 -3.9202144]]]]],[[[[[-17.49849 -7.3978167 -9.203032 ]]]]],7SAM

In [ ]:
mix_databse_normal

,N1,N2,N3,N4,N5,N6,id
0,"[63.503, -2.159, 2.063]","[62.475, -0.6, 7.58]","[59.254, 3.099, 11.143]","[54.76, 5.954, 11.108]","[50.906, 8.879, 9.287]","[48.916, 13.644, 9.296]",1A9L
1,"[-5.776, -2.778, -3.146]","[-2.034, -2.391, -4.556]","[2.325, -3.821, -2.771]","[6.477, -6.051, -2.404]","[8.768, -1.823, 0.458]","[6.995, 1.993, 1.808]",1AFX
8,"[13.681, -3.558, 0.595]","[18.324, -4.9, -1.312]","[20.436, -5.86, 4.102]","[29.34, -1.965, 4.542]","[24.586, 4.563, 1.101]","[22.851, 8.207, -0.639]",1ATW
9,"[5.149, 3.192, -7.233]","[1.026, 6.727, -8.225]","[-1.321, 11.478, -6.196]","[-0.015, 15.306, -2.684]","[-3.527, 20.246, -0.615]","[2.011, 17.757, 2.143]",1BGZ
10,"[11.976, 1.752, 0.447]","[10.986, 5.556, 1.539]","[8.969, 9.517, 3.807]","[9.566, 12.476, 7.74]","[13.169, 15.575, 10.423]","[15.698, 17.651, 16.03]",1CQL
...,...,...,...,...,...,...,...
332,"[16.413, 3.161, 5.897]","[21.372, 1.985, 3.707]","[24.921, 2.838, -0.464]","[25.507, 6.62, -4.495]","[27.82, 11.341, -9.263]","[19.559, 11.943, -7.635]",7K4L
337,"[149.125, 152.478, 203.381]","[144.552, 153.277, 201.242]","[140.778, 154.782, 197.605]","[138.597, 154.961, 191.961]","[137.976, 150.966, 188.395]","[136.002, 144.822, 185.633]",7NHK
338,"[173.614, 150.106, 190.328]","[170.633, 152.992, 186.392]","[165.77, 153.95, 184.388]","[160.047, 152.435, 183.333]","[155.003, 151.713, 185.84]","[152.344, 157.007, 189.502]",7NHM
351,"[332.301, 190.169, 304.007]","[331.647, 185.394, 307.267]","[329.037, 181.425, 310.766]","[325.118, 178.17, 313.682]","[320.701, 174.536, 314.228]","[322.106, 168.923, 318.927]",7RYG
352,"[136.015, 116.201, 98.852]","[142.366, 115.02, 96.086]","[144.361, 113.541, 91.552]","[143.596, 112.884, 86.254]","[141.305, 114.962, 81.084]","[139.261, 118.963, 78.177]",7SAM

In [ ]:
mix_sequences_normal

['CUCCAG',
 'UGUGAA',
 'CCAGAU',
 'UGCUUC',
 'AGGUCA',
 'ACGAAA',
 'ACCAGC',
 'UGCAUA',
 'CCUGAU',
 'CGUCGC',
 'UGCGUA',
 'GCUUAG',
 'GGCUUC',
 'GCAUGG',
 'AGAGGC',
 'AAACUG',
 'GAGUUG',
 'GGCGCU',
 'CGAAGA',
 'AGAAAG',
 'UUCACG',
 'CCUCCC',
 'UGCCUC',
 'GACGAU',
 'CUAGCA',
 'GUACGU',
 'UCGUGU',
 'UCAGGU',
 'GUCGGA',
 'UCUGGC',
 'ACGUCG',
 'UUGCUC',
 'AGACUC',
 'GGCCGA',
 'UUGAAA',
 'UCACAA',
 'CGGCUA',
 'UACUGU',
 'UGCUUG',
 'GAUCUG',
 'GGAUAA',
 'UACCAG',
 'UAGAGU',
 'CGACCA',
 'CGGGUC',
 'CCCUGG',
 'GGGGUA',
 'AAACGG',
 'CCCCGA',
 'GCUCAG',
 'GUGAUA',
 'GGCUGA',
 'AGCAAU',
 'GAGAAG',
 'GCAAUC',
 'GUCGUC',
 'UACCGU',
 'GGGCGC',
 'UCGUCG',
 'AUAGCU',
 'GCUCAG',
 'CUGCGU',
 'GGAUAG',
 'GCUCCA',
 'ACCUAU',
 'UAAGGA',
 'AUGGAU',
 'GCGGGG',
 'UAGUUU',
 'CAGUAU',
 'ACCCCA',
 'GGACUU',
 'UAGUUU',
 'GGCAAA',
 'CGUUUC',
 'AGGUUC',
 'AGCAGU',
 'GAGUGA',
 'GGGCUU']

In [ ]:
print(mix_databse.shape)
mix_databse

(79, 7)

,N1,N2,N3,N4,N5,N6,id
0,[[[[[0. 0. 0.]]]]],[[[[[ 0.8041661 -4.231695 3.9205396]]]]],[[[[[-1.6692054 -9.162296 6.4352946]]]]],[[[[[ -5.333127 -12.891341 5.426225]]]]],[[[[[ -9.668938 -15.040167 3.60736 ]]]]],[[[[[-14.286301 -16.915585 4.959453]]]]],1A9L
1,[[[[[0. 0. 0.]]]]],[[[[[2.2150214 3.3096328 0.5295736]]]]],[[[[[ 1.6075337 7.957532 -0.9737557]]]]],[[[[[ 0.9699897 12.639562 -0.8365039]]]]],[[[[[ 3.7623687 13.40242 -5.625697 ]]]]],[[[[[ 5.630187 10.452166 -8.334042]]]]],1AFX
8,[[[[[0. 0. 0.]]]]],[[[[[ 0.15605938 3.3303156 -3.9849346 ]]]]],[[[[[-1.4434991 -0.8909395 -7.76858 ]]]]],[[[[[ 4.1391993 -0.03929734 -15.690323 ]]]]],[[[[[10.033092 0.17612684 -9.188676 ]]]]],[[[[[13.487843 0.3662275 -6.4784904]]]]],1ATW
9,[[[[[0. 0. 0.]]]]],[[[[[3.0142694 4.4707227 1.1858509]]]]],[[[[[ 5.06909 9.189758 -1.2028017]]]]],[[[[[ 4.280632 11.962079 -5.7178817]]]]],[[[[[ 7.4128475 17.110939 -7.885133 ]]]]],[[[[[ 3.4296734 13.0244465 -11.335644 ]]]]],1BGZ
10,[[[[[0. 0. 0.]]]]],[[[[[2.9372516 2.7519627 0.66500914]]]]],[[[[[7.0581474 5.542484 0.3005259]]]]],[[[[[ 8.809982 9.635785 -1.8804226]]]]],[[[[[ 7.8364873 14.935774 -2.744326 ]]]]],[[[[[ 7.856585 20.061682 -6.727885]]]]],1CQL
...,...,...,...,...,...,...,...
332,[[[[[0. 0. 0.]]]]],[[[[[-0.47233194 -2.9282975 -4.687508 ]]]]],[[[[[ -0.246485 -2.8869483 -10.225336 ]]]]],[[[[[ 1.8193166 0.5098891 -14.109901 ]]]]],[[[[[ 4.9302487 3.4682302 -19.761621 ]]]]],[[[[[ 3.776392 8.825617 -13.341036]]]]],7K4L
337,[[[[[0. 0. 0.]]]]],[[[[[ 2.7760942 -4.215409 -0.8059901]]]]],[[[[[ 5.3282084 -8.258112 -3.4288185]]]]],[[[[[ 8.946509 -10.297053 -7.8326945]]]]],[[[[[13.799988 -8.53124 -9.37788 ]]]]],[[[[[20.524422 -6.54585 -9.039848]]]]],7NHK
338,[[[[[0. 0. 0.]]]]],[[[[[-3.824939 0.59906626 4.209332 ]]]]],[[[[[-4.5126867 1.1054382 9.48693 ]]]]],[[[[[-2.7622252 0.3344388 15.188028 ]]]]],[[[[[ 0.981874 2.1118665 19.070124 ]]]]],[[[[[ 1.3004456 8.925248 20.478476 ]]]]],7NHM
351,[[[[[0. 0. 0.]]]]],[[[[[ 4.8985777 3.137473 -0.1275875]]]]],[[[[[ 9.460717 6.1442494 -2.3533962]]]]],[[[[[13.056042 9.18912 -5.854679]]]]],[[[[[14.632647 13.6115675 -9.166844 ]]]]],[[[[[21.398869 16.247992 -7.485231]]]]],7RYG
352,[[[[[0. 0. 0.]]]]],[[[[[-3.4062576 -5.4804854 2.782512 ]]]]],[[[[[-8.245827 -7.2860346 2.9901767]]]]],[[[[[-13.228863 -7.163368 0.93104553]]]]],[[[[[-16.79267 -6.918027 -3.9202144]]]]],[[[[[-17.49849 -7.3978167 -9.203032 ]]]]],7SAM

In [ ]:
structure = parser.get_structure('1B36', f"./mmCIF_files/1B36.cif")
model = structure[0]
mixs[mixs['ID'] == '1B36']

     ID  start  end     seq    braq chain
6  1B36     13   18  CGCUUC  (((...     A

In [ ]:
chain = model['A']
res = chain[14]
print(res)
at = res["C1'"]
at.get_coord()
##tutaj wszystkie mają pozycję +1, ale funcja dobrze wybrała współrzędne

<Residue C het=  resseq=14 icode= >

array([ 0.109, 22.749, -1.642], dtype=float32)

In [ ]:
mix_database = mix_databse_normal.drop('id', axis=1)
for column in mix_database.columns:
    mix_database[column] = mix_database[column].apply(lambda x: ','.join(map(str, x)))
    
mix_database['class'] = 0
mix_database.to_csv("mix_database_C1_v2'.csv")
mix_database

,N1,N2,N3,N4,N5,N6,class
0,"63.503,-2.159,2.063","62.475,-0.6,7.58","59.254,3.099,11.143","54.76,5.954,11.108","50.906,8.879,9.287","48.916,13.644,9.296",0
1,"-5.776,-2.778,-3.146","-2.034,-2.391,-4.556","2.325,-3.821,-2.771","6.477,-6.051,-2.404","8.768,-1.823,0.458","6.995,1.993,1.808",0
8,"13.681,-3.558,0.595","18.324,-4.9,-1.312","20.436,-5.86,4.102","29.34,-1.965,4.542","24.586,4.563,1.101","22.851,8.207,-0.639",0
9,"5.149,3.192,-7.233","1.026,6.727,-8.225","-1.321,11.478,-6.196","-0.015,15.306,-2.684","-3.527,20.246,-0.615","2.011,17.757,2.143",0
10,"11.976,1.752,0.447","10.986,5.556,1.539","8.969,9.517,3.807","9.566,12.476,7.74","13.169,15.575,10.423","15.698,17.651,16.03",0
...,...,...,...,...,...,...,...
332,"16.413,3.161,5.897","21.372,1.985,3.707","24.921,2.838,-0.464","25.507,6.62,-4.495","27.82,11.341,-9.263","19.559,11.943,-7.635",0
337,"149.125,152.478,203.381","144.552,153.277,201.242","140.778,154.782,197.605","138.597,154.961,191.961","137.976,150.966,188.395","136.002,144.822,185.633",0
338,"173.614,150.106,190.328","170.633,152.992,186.392","165.77,153.95,184.388","160.047,152.435,183.333","155.003,151.713,185.84","152.344,157.007,189.502",0
351,"332.301,190.169,304.007","331.647,185.394,307.267","329.037,181.425,310.766","325.118,178.17,313.682","320.701,174.536,314.228","322.106,168.923,318.927",0
352,"136.015,116.201,98.852","142.366,115.02,96.086","144.361,113.541,91.552","143.596,112.884,86.254","141.305,114.962,81.084","139.261,118.963,78.177",0

In [ ]:
mix_database_v22 = mix_databse.drop('id', axis=1)
for column in mix_database_v22.columns:
    mix_database_v22[column] = mix_database_v22[column].apply(lambda x: ','.join(map(str,np.array(x).flatten())))
mix_database_v22['class'] = 0
mix_database_v22.to_csv("./modified_coord/mix_C1_v3'.csv")
mix_database_v22

,N1,N2,N3,N4,N5,N6,class
0,"0.0,0.0,0.0","0.8041661,-4.231695,3.9205396","-1.6692054,-9.162296,6.4352946","-5.333127,-12.891341,5.426225","-9.668938,-15.040167,3.60736","-14.286301,-16.915585,4.959453",0
1,"0.0,0.0,0.0","2.2150214,3.3096328,0.5295736","1.6075337,7.957532,-0.9737557","0.9699897,12.639562,-0.8365039","3.7623687,13.40242,-5.625697","5.630187,10.452166,-8.334042",0
8,"0.0,0.0,0.0","0.15605938,3.3303156,-3.9849346","-1.4434991,-0.8909395,-7.76858","4.1391993,-0.039297342,-15.690323","10.033092,0.17612684,-9.188676","13.487843,0.3662275,-6.4784904",0
9,"0.0,0.0,0.0","3.0142694,4.4707227,1.1858509","5.06909,9.189758,-1.2028017","4.280632,11.962079,-5.7178817","7.4128475,17.110939,-7.885133","3.4296734,13.0244465,-11.335644",0
10,"0.0,0.0,0.0","2.9372516,2.7519627,0.66500914","7.0581474,5.542484,0.3005259","8.809982,9.635785,-1.8804226","7.8364873,14.935774,-2.744326","7.856585,20.061682,-6.727885",0
...,...,...,...,...,...,...,...
332,"0.0,0.0,0.0","-0.47233194,-2.9282975,-4.687508","-0.246485,-2.8869483,-10.225336","1.8193166,0.5098891,-14.109901","4.9302487,3.4682302,-19.761621","3.776392,8.825617,-13.341036",0
337,"0.0,0.0,0.0","2.7760942,-4.215409,-0.8059901","5.3282084,-8.258112,-3.4288185","8.946509,-10.297053,-7.8326945","13.799988,-8.53124,-9.37788","20.524422,-6.54585,-9.039848",0
338,"0.0,0.0,0.0","-3.824939,0.59906626,4.209332","-4.5126867,1.1054382,9.48693","-2.7622252,0.3344388,15.188028","0.981874,2.1118665,19.070124","1.3004456,8.925248,20.478476",0
351,"0.0,0.0,0.0","4.8985777,3.137473,-0.1275875","9.460717,6.1442494,-2.3533962","13.056042,9.18912,-5.854679","14.632647,13.6115675,-9.166844","21.398869,16.247992,-7.485231",0
352,"0.0,0.0,0.0","-3.4062576,-5.4804854,2.782512","-8.245827,-7.2860346,2.9901767","-13.228863,-7.163368,0.93104553","-16.79267,-6.918027,-3.9202144","-17.49849,-7.3978167,-9.203032",0

In [ ]:
with open("mix_database_C1'_seqs_v2.csv", 'w', newline='') as f:
     
    # using csv.writer method from CSV package
    write = csv.writer(f)
    for item in mix_sequences:
        write.writerow([item])